// 英語冒險王 - 語塊與搭配詞資料庫 (Collocations)
// 每級 15 組「動詞 + 名詞」語塊:
//   v = 動詞(填空考點), rest = 語塊其餘部分, c = 中文, def = 英英釋義, ex = 真實例句
//   ban = 不可當誘答的動詞(避免出現另一種也正確的搭配,如 have a shower)
const COLLOC_BANK = {
  junior: [
    { v: "do", rest: "homework", c: "做功課", def: "to finish the schoolwork your teacher gives you", ex: "Nick does his homework right after school.", ban: [] },
    { v: "take", rest: "a shower", c: "洗澡", def: "to wash your body under running water", ex: "I take a shower every morning before breakfast.", ban: ["have"] },
    { v: "make", rest: "a mistake", c: "犯錯", def: "to do something wrong without meaning to", ex: "Don't be afraid to make a mistake when you speak English.", ban: [] },
    { v: "ride", rest: "a bike", c: "騎腳踏車", def: "to sit on a bicycle and make it move", ex: "Emma rides her bike to school every day.", ban: [] },
    { v: "play", rest: "basketball", c: "打籃球", def: "to take part in a basketball game", ex: "We play basketball in the park on weekends.", ban: [] },
    { v: "take", rest: "a bus", c: "搭公車", def: "to travel somewhere by bus", ex: "It's cheaper to take a bus to the museum.", ban: ["ride"] },
    { v: "keep", rest: "a diary", c: "寫日記", def: "to write about what happens to you every day", ex: "She keeps a diary in English to practice writing.", ban: [] },
    { v: "make", rest: "friends", c: "交朋友", def: "to get to know people and become friendly with them", ex: "Joining a club is a great way to make friends.", ban: [] },
    { v: "take", rest: "a picture", c: "拍照", def: "to use a camera to photograph something", ex: "Tourists love to take pictures of the old bridge.", ban: [] },
    { v: "go", rest: "shopping", c: "去購物", def: "to visit stores to buy things", ex: "Mom and I go shopping at the night market on Fridays.", ban: ["do"] },
    { v: "have", rest: "a cold", c: "感冒", def: "to be sick with a running nose and a cough", ex: "Kevin stayed home because he had a bad cold.", ban: [] },
    { v: "tell", rest: "a joke", c: "講笑話", def: "to say something funny to make people laugh", ex: "Our teacher always tells a joke at the start of class.", ban: ["make"] },
    { v: "save", rest: "money", c: "存錢", def: "to keep money so you can use it later", ex: "I'm saving money to buy a new bike.", ban: ["make"] },
    { v: "surf", rest: "the Internet", c: "上網", def: "to look at different websites online", ex: "He surfs the Internet to find fun English videos.", ban: [] },
    { v: "take", rest: "a walk", c: "散步", def: "to walk somewhere slowly for pleasure or exercise", ex: "Grandpa takes a walk in the park after dinner.", ban: ["have", "go"] },
  ],
  senior: [
    { v: "pay", rest: "attention", c: "集中注意力", def: "to watch, listen to, or think about something carefully", ex: "Please pay attention to the difference between these two words.", ban: [] },
    { v: "make", rest: "a decision", c: "做決定", def: "to choose what to do after thinking about it", ex: "You don't have to make a decision right away.", ban: ["take"] },
    { v: "take", rest: "responsibility", c: "承擔責任", def: "to accept that a task or mistake is yours to deal with", ex: "A good leader takes responsibility for the team's failures.", ban: [] },
    { v: "reach", rest: "a goal", c: "達成目標", def: "to succeed in doing what you planned to do", ex: "She trained for years to reach her goal of running a marathon.", ban: [] },
    { v: "solve", rest: "a problem", c: "解決問題", def: "to find an answer to something difficult", ex: "Working together helps us solve problems faster.", ban: [] },
    { v: "draw", rest: "a conclusion", c: "得出結論", def: "to decide what is true after considering the facts", ex: "It's too early to draw a conclusion from so little data.", ban: ["reach"] },
    { v: "raise", rest: "a question", c: "提出問題", def: "to bring up a matter that needs to be discussed", ex: "The report raises a question about food safety.", ban: [] },
    { v: "broaden", rest: "one's horizons", c: "開拓視野", def: "to increase the range of things you know or experience", ex: "Studying abroad really broadened her horizons.", ban: [] },
    { v: "lose", rest: "one's temper", c: "發脾氣", def: "to suddenly become very angry", ex: "He lost his temper when the train was delayed again.", ban: [] },
    { v: "take", rest: "action", c: "採取行動", def: "to do something in order to deal with a problem", ex: "The city must take action to reduce air pollution.", ban: [] },
    { v: "make", rest: "an effort", c: "努力嘗試", def: "to try hard to do something", ex: "She made a real effort to speak English at the meeting.", ban: [] },
    { v: "keep", rest: "a promise", c: "遵守承諾", def: "to do what you said you would do", ex: "I always keep my promises to my friends.", ban: ["make"] },
    { v: "run", rest: "a risk", c: "冒風險", def: "to do something even though something bad might happen", ex: "If you skip the review, you run the risk of failing the exam.", ban: ["take"] },
    { v: "gain", rest: "experience", c: "累積經驗", def: "to get knowledge or skill by doing something", ex: "He worked part-time to gain experience in sales.", ban: [] },
    { v: "set", rest: "an example", c: "樹立榜樣", def: "to behave in a way that others should copy", ex: "Parents should set an example by reading at home.", ban: [] },
  ],
  college: [
    { v: "reach", rest: "a consensus", c: "達成共識", def: "to come to an agreement that everyone in a group accepts", ex: "After a long debate, the committee finally reached a consensus.", ban: [] },
    { v: "conduct", rest: "research", c: "進行研究", def: "to study a subject carefully in an organized, scientific way", ex: "The team is conducting research on renewable energy.", ban: [] },
    { v: "raise", rest: "awareness", c: "提高意識", def: "to make more people understand a problem", ex: "The campaign aims to raise awareness of ocean pollution.", ban: [] },
    { v: "pose", rest: "a threat", c: "構成威脅", def: "to be likely to cause harm or danger", ex: "Rising sea levels pose a serious threat to coastal cities.", ban: [] },
    { v: "play", rest: "a role", c: "扮演角色", def: "to have an effect or function in a situation", ex: "Diet plays a key role in preventing disease.", ban: [] },
    { v: "meet", rest: "a deadline", c: "趕上期限", def: "to finish something by the time it is due", ex: "We worked overtime to meet the deadline for the project.", ban: [] },
    { v: "draw", rest: "a distinction", c: "加以區分", def: "to point out the difference between two things", ex: "The author draws a clear distinction between facts and opinions.", ban: [] },
    { v: "address", rest: "an issue", c: "處理議題", def: "to deal with a problem in a serious way", ex: "The new policy addresses the issue of youth unemployment.", ban: ["raise"] },
    { v: "exert", rest: "influence", c: "發揮影響力", def: "to use your power to affect people or events", ex: "Social media exerts a powerful influence on public opinion.", ban: [] },
    { v: "undergo", rest: "a transformation", c: "經歷轉變", def: "to experience a complete change", ex: "The city has undergone a remarkable transformation in ten years.", ban: [] },
    { v: "foster", rest: "innovation", c: "促進創新", def: "to encourage new ideas and methods to develop", ex: "Flexible workplaces help foster innovation.", ban: [] },
    { v: "implement", rest: "a policy", c: "實施政策", def: "to put an official plan into effect", ex: "The government will implement the new policy next year.", ban: [] },
    { v: "allocate", rest: "resources", c: "分配資源", def: "to officially decide how money, time, or materials will be used", ex: "Hospitals must allocate resources where they are needed most.", ban: [] },
    { v: "assess", rest: "the impact", c: "評估影響", def: "to judge how strongly something affects a situation", ex: "Scientists are assessing the impact of the new dam on wildlife.", ban: [] },
    { v: "bridge", rest: "the gap", c: "弭平差距", def: "to reduce the difference between two groups or things", ex: "Online courses help bridge the gap between city and rural schools.", ban: [] },
  ],
  master: [
    { v: "formulate", rest: "a hypothesis", c: "提出假說", def: "to develop a possible explanation that can be tested", ex: "The researchers formulated a hypothesis based on early observations.", ban: [] },
    { v: "yield", rest: "results", c: "產生結果", def: "to produce findings or outcomes", ex: "The new method yielded promising results in clinical trials.", ban: [] },
    { v: "mitigate", rest: "a risk", c: "降低風險", def: "to make a danger less severe or less likely", ex: "Backup systems mitigate the risk of losing critical data.", ban: [] },
    { v: "substantiate", rest: "a claim", c: "證實主張", def: "to provide evidence that proves a statement is true", ex: "The author fails to substantiate his central claim with data.", ban: [] },
    { v: "draw", rest: "an analogy", c: "進行類比", def: "to compare two things to show how they are similar", ex: "She draws an analogy between the brain and a computer network.", ban: [] },
    { v: "replicate", rest: "a study", c: "重複驗證研究", def: "to repeat an experiment to confirm its findings", ex: "Other labs were unable to replicate the original study.", ban: [] },
    { v: "synthesize", rest: "information", c: "統整資訊", def: "to combine ideas from different sources into a coherent whole", ex: "A good review synthesizes information from dozens of papers.", ban: [] },
    { v: "delineate", rest: "the scope", c: "界定範圍", def: "to describe exactly the limits of something", ex: "The first chapter delineates the scope of the investigation.", ban: [] },
    { v: "reconcile", rest: "differences", c: "調和分歧", def: "to find a way to make opposing views exist together", ex: "The theory attempts to reconcile differences between the two models.", ban: [] },
    { v: "underpin", rest: "an argument", c: "支撐論點", def: "to form the basis that supports a claim", ex: "Solid statistics underpin every argument in the report.", ban: [] },
    { v: "disseminate", rest: "findings", c: "發布研究成果", def: "to spread research results to a wide audience", ex: "The institute disseminates its findings through open-access journals.", ban: [] },
    { v: "refine", rest: "a model", c: "改良模型", def: "to improve a system or theory with small changes", ex: "Each round of feedback helped us refine the model.", ban: ["formulate"] },
    { v: "derive", rest: "insights", c: "獲得洞見", def: "to obtain deeper understanding from information", ex: "Analysts derive insights from millions of customer records.", ban: ["yield"] },
    { v: "gauge", rest: "the effectiveness", c: "評測成效", def: "to measure how well something works", ex: "Surveys were used to gauge the effectiveness of the training.", ban: [] },
    { v: "bolster", rest: "credibility", c: "增強可信度", def: "to strengthen how believable someone or something is", ex: "Citing primary sources bolsters the credibility of your thesis.", ban: [] },
  ],
  phd: [
    { v: "interrogate", rest: "assumptions", c: "批判檢視假設", def: "to examine accepted beliefs critically and rigorously", ex: "The seminar interrogates assumptions underlying liberal political theory.", ban: [] },
    { v: "problematize", rest: "the notion", c: "質疑既有概念", def: "to treat an accepted idea as something requiring critical questioning", ex: "Her dissertation problematizes the notion of a unified national identity.", ban: [] },
    { v: "elucidate", rest: "a mechanism", c: "闡明機制", def: "to make clear how a complex process works", ex: "The study elucidates the mechanism by which the protein folds.", ban: [] },
    { v: "posit", rest: "a framework", c: "提出理論框架", def: "to put forward a structured theory as a basis for argument", ex: "The paper posits a framework for analyzing digital labor.", ban: [] },
    { v: "transcend", rest: "boundaries", c: "跨越界線", def: "to go beyond the usual limits of fields or categories", ex: "Her research transcends disciplinary boundaries between law and neuroscience.", ban: [] },
    { v: "navigate", rest: "the complexities", c: "應對複雜情勢", def: "to find a way through a highly complicated situation", ex: "Fieldworkers must navigate the complexities of local politics.", ban: [] },
    { v: "grapple", rest: "with a paradox", c: "苦思悖論", def: "to struggle to resolve a seemingly self-contradictory problem", ex: "Physicists still grapple with the paradox of information loss in black holes.", ban: [] },
    { v: "advance", rest: "a thesis", c: "提出核心論點", def: "to put forward a central argument for consideration", ex: "The monograph advances the thesis that empires collapse from within.", ban: ["posit"] },
    { v: "situate", rest: "the discourse", c: "定位論述脈絡", def: "to place a discussion within its historical or theoretical context", ex: "The introduction situates the discourse within postcolonial theory.", ban: [] },
    { v: "distill", rest: "the essence", c: "提煉精髓", def: "to extract the most important core from something complex", ex: "The abstract distills the essence of a decade of fieldwork.", ban: [] },
    { v: "circumvent", rest: "limitations", c: "規避限制", def: "to find a way around restrictions or weaknesses", ex: "The new assay circumvents the limitations of earlier techniques.", ban: [] },
    { v: "engender", rest: "debate", c: "引發爭論", def: "to cause discussion and disagreement to arise", ex: "The findings engendered fierce debate at the conference.", ban: ["catalyze"] },
    { v: "epitomize", rest: "a paradigm", c: "體現典範", def: "to be a perfect example of a general model of thought", ex: "Darwin's finches epitomize the paradigm of adaptive radiation.", ban: [] },
    { v: "demarcate", rest: "the field", c: "劃定領域範圍", def: "to set the boundaries that define an area of study", ex: "Kuhn's work helped demarcate the field of science studies.", ban: [] },
    { v: "catalyze", rest: "change", c: "催化變革", def: "to cause or accelerate significant transformation", ex: "Grassroots movements can catalyze change in national policy.", ban: ["engender"] },
  ],
};

// 語塊全名與音檔 slug
function chunkOf(item) { return `${item.v} ${item.rest}`; }
function chunkSlug(item) { return chunkOf(item).toLowerCase().replace(/[^a-z0-9]+/g, "_"); }
