// ============================================================
//  🎓 托福 TOEFL 專區 - 題庫資料
//  學術字彙 / Reading 學術閱讀 / Listening 校園對話與講座
//  Speaking 獨立口說 / Writing 學術討論寫作
//  選項規則:opts 的第 0 個永遠是正解,畫面顯示時再洗牌
// ============================================================

// ---------- 學術字彙(6 主題 × 10 字,與多益字庫不重複)----------
const TOEFL_WORDS = [
  { theme: "研究方法", emoji: "📊", list: [
    { w: "hypothesis", zh: "假設", pos: "n." },
    { w: "variable", zh: "變項;變數", pos: "n." },
    { w: "methodology", zh: "研究方法論", pos: "n." },
    { w: "empirical", zh: "實證的;經驗的", pos: "adj." },
    { w: "correlation", zh: "相關性", pos: "n." },
    { w: "replicate", zh: "重製;複驗", pos: "v." },
    { w: "validity", zh: "效度;有效性", pos: "n." },
    { w: "criterion", zh: "標準(複 criteria)", pos: "n." },
    { w: "bias", zh: "偏誤;偏見", pos: "n." },
    { w: "significant", zh: "顯著的", pos: "adj." },
  ]},
  { theme: "自然科學", emoji: "🔬", list: [
    { w: "organism", zh: "生物體", pos: "n." },
    { w: "molecule", zh: "分子", pos: "n." },
    { w: "ecosystem", zh: "生態系", pos: "n." },
    { w: "adaptation", zh: "適應(作用)", pos: "n." },
    { w: "sediment", zh: "沉積物", pos: "n." },
    { w: "photosynthesis", zh: "光合作用", pos: "n." },
    { w: "glacier", zh: "冰川", pos: "n." },
    { w: "species", zh: "物種(單複同形)", pos: "n." },
    { w: "atmosphere", zh: "大氣層", pos: "n." },
    { w: "predator", zh: "掠食者", pos: "n." },
  ]},
  { theme: "社會科學", emoji: "🏛️", list: [
    { w: "urbanization", zh: "都市化", pos: "n." },
    { w: "demographic", zh: "人口統計的", pos: "adj." },
    { w: "migration", zh: "遷徙;移民", pos: "n." },
    { w: "hierarchy", zh: "階層;層級", pos: "n." },
    { w: "incentive", zh: "誘因;動機", pos: "n." },
    { w: "institution", zh: "制度;機構", pos: "n." },
    { w: "norm", zh: "規範;常態", pos: "n." },
    { w: "welfare", zh: "福利", pos: "n." },
    { w: "mobility", zh: "流動性", pos: "n." },
    { w: "census", zh: "人口普查", pos: "n." },
  ]},
  { theme: "人文藝術", emoji: "🎨", list: [
    { w: "aesthetic", zh: "美學的", pos: "adj." },
    { w: "narrative", zh: "敘事", pos: "n." },
    { w: "portray", zh: "描繪;刻畫", pos: "v." },
    { w: "symbolism", zh: "象徵手法", pos: "n." },
    { w: "manuscript", zh: "手稿", pos: "n." },
    { w: "sculpture", zh: "雕塑", pos: "n." },
    { w: "patron", zh: "贊助者", pos: "n." },
    { w: "genre", zh: "類型;體裁", pos: "n." },
    { w: "era", zh: "時代;年代", pos: "n." },
    { w: "compose", zh: "創作;組成", pos: "v." },
  ]},
  { theme: "校園生活", emoji: "🎒", list: [
    { w: "syllabus", zh: "課程大綱", pos: "n." },
    { w: "prerequisite", zh: "先修課;必要條件", pos: "n." },
    { w: "seminar", zh: "研討課", pos: "n." },
    { w: "tuition", zh: "學費", pos: "n." },
    { w: "dormitory", zh: "宿舍", pos: "n." },
    { w: "advisor", zh: "指導老師;顧問", pos: "n." },
    { w: "enroll", zh: "註冊;選課", pos: "v." },
    { w: "scholarship", zh: "獎學金", pos: "n." },
    { w: "faculty", zh: "全體教職員;學院", pos: "n." },
    { w: "assignment", zh: "作業;指派", pos: "n." },
  ]},
  { theme: "論證與轉折", emoji: "🧩", list: [
    { w: "nevertheless", zh: "儘管如此", pos: "adv." },
    { w: "furthermore", zh: "此外;而且", pos: "adv." },
    { w: "plausible", zh: "看似合理的", pos: "adj." },
    { w: "refute", zh: "駁斥;反駁", pos: "v." },
    { w: "advocate", zh: "主張;倡導", pos: "v." },
    { w: "undermine", zh: "削弱;動搖", pos: "v." },
    { w: "implication", zh: "含意;影響", pos: "n." },
    { w: "consequently", zh: "因此;結果", pos: "adv." },
    { w: "presume", zh: "推測;假定", pos: "v." },
    { w: "contrary", zh: "相反的(事物)", pos: "adj./n." },
  ]},
];

// ---------- Reading 學術閱讀(4 篇 × 4 題,含四大題型)----------
const TOEFL_READING = [
  { id: "rd1", field: "天文學", icon: "🌕", title: "The Origin of the Moon",
    text: "For most of the twentieth century, scientists debated three competing explanations for the origin of the Moon. The capture hypothesis proposed that the Moon formed elsewhere in the solar system and was later pulled into orbit by Earth's gravity. The fission hypothesis suggested that a rapidly spinning young Earth threw off a portion of its own mantle. The co-formation hypothesis held that Earth and the Moon condensed side by side from the same cloud of dust and gas.\n\nEach account, however, ran into serious difficulties. Capture requires an extremely narrow range of approach speeds, and it fails to explain why lunar rocks are chemically so similar to Earth's mantle. Co-formation, on the other hand, cannot account for the Moon's unusually small iron core.\n\nThe giant-impact hypothesis, which emerged in the 1970s, now enjoys the widest support. It holds that a Mars-sized body struck the young Earth at an oblique angle, vaporizing rock from the outer layers of both objects. Much of this debris settled into orbit and gradually coalesced into the Moon. Because the ejected material came mainly from the mantle rather than the core, the model neatly explains both the Moon's chemical resemblance to Earth and its iron deficiency.",
    questions: [
      { q: `<span class="tfl-qtype">主旨題</span> What is the main purpose of the passage?`,
        opts: ["To review competing explanations of the Moon's origin and show why one is favored",
          "To prove that the capture hypothesis is entirely impossible",
          "To describe how astronauts collected lunar rock samples",
          "To compare the Moon's surface with the surface of Mars"],
        note: "文章列出三種舊假說的困難,再說明巨大撞擊說為何最被接受 → 主旨是「比較各假說並指出勝出者」。" },
      { q: `<span class="tfl-qtype">細節題</span> According to the passage, why is the co-formation hypothesis problematic?`,
        opts: ["It cannot explain why the Moon's iron core is so small",
          "It requires a very narrow range of approach speeds",
          "It assumes the Moon formed far from the solar system",
          "It contradicts the chemical similarity of lunar and Earth rocks"],
        note: "文中明說 Co-formation cannot account for the Moon's unusually small iron core;narrow range of approach speeds 是 capture 的問題。" },
      { q: `<span class="tfl-qtype">詞彙題</span> The word "coalesced" in the passage is closest in meaning to`,
        opts: ["came together", "cooled down", "broke apart", "moved away"],
        note: "coalesce = 聚合、合併;碎片在軌道上逐漸「聚合」成月球。" },
      { q: `<span class="tfl-qtype">推論題</span> What can be inferred about the material ejected by the giant impact?`,
        opts: ["It contained relatively little iron because it came from the outer layers",
          "It came mostly from the cores of both bodies",
          "It escaped Earth's gravity completely",
          "It was chemically unlike anything on Earth"],
        note: "末句說碎片主要來自 mantle 而非 core,而核心才富含鐵 → 可推論噴出物含鐵量低。" },
    ]},

  { id: "rd2", field: "生物學", icon: "🌱", title: "Why Some Plants Eat Insects",
    text: "Carnivorous plants such as the Venus flytrap and the pitcher plant appear to reverse the usual order of nature: instead of being eaten by animals, they eat them. This unusual strategy is best understood as an adaptation to soil rather than to appetite. Nearly all carnivorous species grow in bogs, sandy barrens, or other habitats where nitrogen and phosphorus are scarce. Trapping insects allows these plants to obtain the nutrients that their roots cannot supply.\n\nCarnivory, however, is expensive. Traps are modified leaves, and a leaf shaped into a pitcher or a snapping hinge captures far less sunlight than a flat leaf of the same mass. A plant that invests heavily in traps therefore sacrifices photosynthetic capacity. Ecologists describe the resulting trade-off with a simple rule: carnivory pays only where light and water are abundant but soil nutrients are not.\n\nThis rule explains a puzzling pattern in the field. When bogs are drained or enriched with fertilizer, carnivorous plants are usually the first species to disappear. Once nutrients become freely available in the soil, ordinary plants with efficient flat leaves grow faster, and the costly traps become a disadvantage rather than an asset.",
    questions: [
      { q: `<span class="tfl-qtype">主旨題</span> The passage is mainly concerned with`,
        opts: ["the conditions under which insect-trapping is beneficial to plants",
          "the different shapes of traps found in carnivorous plants",
          "the digestive chemistry that carnivorous plants use",
          "the decline of insect populations in bogs"],
        note: "全篇圍繞「食蟲為何划算/何時不划算」的取捨條件,不是構造或化學。" },
      { q: `<span class="tfl-qtype">細節題</span> According to the passage, traps are costly to a plant because they`,
        opts: ["capture less sunlight than ordinary flat leaves",
          "require large amounts of nitrogen to build",
          "must be replaced after every insect caught",
          "attract predators that damage the plant"],
        note: "第二段:pitcher/hinge 形狀的葉子吸收陽光遠少於同質量的平葉 → 犧牲光合作用。" },
      { q: `<span class="tfl-qtype">詞彙題</span> The word "scarce" in the passage is closest in meaning to`,
        opts: ["in short supply", "poisonous", "unstable", "widespread"],
        note: "scarce = 稀少、不足;句意是氮磷「不足」的棲地。" },
      { q: `<span class="tfl-qtype">推論題</span> It can be inferred that adding fertilizer to a bog would`,
        opts: ["give non-carnivorous plants a competitive advantage",
          "cause carnivorous plants to grow larger traps",
          "reduce the number of insects available as prey",
          "make the soil too acidic for ordinary plants"],
        note: "末段:養分充足後,平葉的普通植物長得更快,陷阱反成負擔 → 普通植物取得競爭優勢。" },
    ]},

  { id: "rd3", field: "歷史", icon: "☕", title: "Coffeehouses and Public Debate",
    text: "When coffee reached London in the middle of the seventeenth century, it arrived with an institution attached: the coffeehouse. Within fifty years several thousand had opened in the city. For the price of a penny, any man could enter, take a seat at a common table, and read the newspapers kept on hand for customers. Contemporaries called these establishments \"penny universities,\" since an afternoon of conversation there cost less than a single lecture.\n\nHistorians argue that the coffeehouse mattered less for what was served than for how people sat. Taverns organized drinkers into private booths, and social rank governed who spoke to whom. The coffeehouse, by contrast, seated strangers together and encouraged them to argue. Merchants, physicians, and clerks exchanged news at the same table, and a claim was expected to survive questioning rather than rest on the speaker's status.\n\nThe consequences reached well beyond conversation. Marine insurance, stock trading, and scientific societies all took shape in particular coffeehouses whose regular customers shared an interest. Several newspapers began as sheets compiled from the talk of a single room. The coffeehouse, in short, supplied early modern cities with something they had lacked: a cheap, semi-public space in which information circulated faster than rank.",
    questions: [
      { q: `<span class="tfl-qtype">主旨題</span> What is the main idea of the passage?`,
        opts: ["Coffeehouses created a new kind of public space that changed how information circulated",
          "Coffee was cheaper and healthier than the drinks served in taverns",
          "London universities lost students to coffeehouses in the 1600s",
          "Newspapers were the most profitable business of the seventeenth century"],
        note: "全文重點是咖啡館作為「半公共空間」對資訊流通與制度形成的影響。" },
      { q: `<span class="tfl-qtype">細節題</span> According to the passage, how did coffeehouses differ from taverns?`,
        opts: ["They seated strangers of different ranks at shared tables",
          "They served food as well as drinks",
          "They admitted customers only by invitation",
          "They were open for fewer hours each day"],
        note: "第二段直接對比:酒館用包廂、依身分決定誰能與誰交談;咖啡館讓陌生人同桌辯論。" },
      { q: `<span class="tfl-qtype">詞彙題</span> The phrase "penny universities" suggests that coffeehouses were`,
        opts: ["places where one could learn a great deal very cheaply",
          "schools that charged tuition by the week",
          "libraries that lent books for a small fee",
          "colleges founded by wealthy merchants"],
        note: "後半句解釋:一下午的談話比一堂講座還便宜 → 極廉價的學習場所。" },
      { q: `<span class="tfl-qtype">推論題</span> The author mentions marine insurance and stock trading in order to`,
        opts: ["illustrate that institutions grew out of coffeehouse conversation",
          "argue that coffeehouses were mainly financial businesses",
          "explain why coffee became expensive in London",
          "contrast British and continental European trade"],
        note: "第三段用這些例子證明咖啡館的影響「遠超過談話本身」,即制度由此成形。" },
    ]},

  { id: "rd4", field: "認知心理學", icon: "🧠", title: "The Spacing Effect",
    text: "Suppose two students each spend six hours preparing for the same examination. The first studies for six hours the night before; the second studies for one hour on six separate days. More than a century of research indicates that the second student will remember substantially more, and the advantage grows as the delay before the test increases. Psychologists call this finding the spacing effect.\n\nThe leading explanation concerns the difficulty of retrieval. During a single long session, the material stays available in working memory, so each repetition is easy and adds little. When study is distributed, forgetting occurs between sessions, and the learner must reconstruct the information rather than simply recognize it. That effortful reconstruction is what strengthens the memory trace.\n\nThe practical difficulty is that spacing feels worse while it is happening. Massed practice produces rapid, visible gains within a session, whereas spaced practice is marked by hesitation and error. Students consistently rate the method that produces poorer long-term results as the more effective one. Researchers describe such conditions as desirable difficulties: obstacles that slow performance during learning but improve retention afterward.",
    questions: [
      { q: `<span class="tfl-qtype">主旨題</span> The passage mainly discusses`,
        opts: ["why spreading study over time improves long-term memory",
          "how much total time students should spend studying",
          "why examinations should be scheduled in advance",
          "the difference between working memory and long-term memory"],
        note: "全文說明分散練習(spacing effect)為何有效及其反直覺之處。" },
      { q: `<span class="tfl-qtype">細節題</span> According to the passage, why does a single long session add little to memory?`,
        opts: ["The material remains in working memory, so repetition requires no effort",
          "Students become too tired to concentrate",
          "The information is never encoded in the first place",
          "Long sessions cause interference between different topics"],
        note: "第二段:長時間單次學習時材料仍在工作記憶中,每次重複都太輕鬆,幫助有限。" },
      { q: `<span class="tfl-qtype">詞彙題</span> The word "retrieval" in the passage is closest in meaning to`,
        opts: ["bringing information back to mind", "storing information for later",
          "organizing information into groups", "removing unnecessary information"],
        note: "retrieval = 提取、回想已存的資訊,與 storage(儲存)相對。" },
      { q: `<span class="tfl-qtype">推論題</span> Why does the author call spacing a "desirable difficulty"?`,
        opts: ["It feels harder during study but produces better retention later",
          "It is difficult only for students who dislike examinations",
          "It requires more total study hours than massed practice",
          "It is desirable for teachers but difficult for students"],
        note: "末句定義:學習當下表現變慢,但之後的保留效果更好 → 「有益的困難」。" },
    ]},
];

// ---------- Listening 校園對話與學術講座(雙聲道)----------
const TOEFL_LISTENING = [
  { id: "cv1", kind: "校園對話", title: "選課與先修規定", icon: "🗓️",
    lines: [
      { sp: "W", en: "Excuse me, Professor Lin. I'd like to enroll in your seminar on urban sociology this fall, but the system keeps rejecting my registration." },
      { sp: "M", en: "That's probably the prerequisite. The seminar assumes you've finished Statistics for Social Research." },
      { sp: "W", en: "I took a statistics course last summer, but it was at my community college, so it may not appear on my transcript here." },
      { sp: "M", en: "Then the registrar simply can't see it. Bring me the syllabus from that course, and if the content matches, I can sign a waiver." },
      { sp: "W", en: "I still have the syllabus in my email. Should I also submit anything to the department office?" },
      { sp: "M", en: "Just the signed form. Do it before Friday, though — after that the seminar closes and I can't add anyone." },
    ],
    questions: [
      { q: "Why does the student go to see the professor?", opts: ["She cannot register for his seminar", "She wants to change her major", "She missed the first class meeting", "She needs a letter of recommendation"], note: "開場:系統一直拒絕她的選課。" },
      { q: "What does the professor say is causing the problem?", opts: ["The registrar has no record of her statistics course", "The seminar is already full", "She has not paid her tuition", "Her advisor has not approved her plan"], note: "教授說社區大學的課沒出現在成績單上,註冊組看不到。" },
      { q: "What should the student do before Friday?", opts: ["Submit the signed waiver form", "Retake the statistics course", "Email the registrar directly", "Attend an extra seminar session"], note: "教授:只要交簽好的表格,且必須在週五前完成。" },
    ]},

  { id: "cv2", kind: "校園對話", title: "圖書館館際互借", icon: "📚",
    lines: [
      { sp: "M", en: "Hi, I'm looking for a book for my art history paper, but the catalog says it's not in our library." },
      { sp: "W", en: "If we don't own it, you can request it through interlibrary loan. It usually takes about a week to arrive." },
      { sp: "M", en: "A week might be too late. My first draft is due next Wednesday." },
      { sp: "W", en: "In that case, check whether the chapter you need has been scanned. For articles and single chapters, delivery is electronic and often same-day." },
      { sp: "M", en: "I only need the chapter on nineteenth-century patrons, so that would be perfect." },
      { sp: "W", en: "Then fill out the electronic request form and enter the chapter title. You'll get a PDF link by email once it's processed." },
    ],
    questions: [
      { q: "What is the student's main problem?", opts: ["The library does not have the book he needs", "He has lost his library card", "The library is closing early", "He cannot find the catalog"], note: "第一句:目錄顯示館內沒有這本書。" },
      { q: "Why does the librarian suggest requesting only a chapter?", opts: ["Electronic chapter delivery is much faster", "Chapters are cheaper to request", "The full book is damaged", "Only chapters can be renewed"], note: "館員說單篇文章或章節可電子傳遞,常常當天就到。" },
      { q: "What will the student receive by email?", opts: ["A link to a PDF", "A printed copy of the book", "A due-date reminder", "A list of nearby libraries"], note: "最後一句:處理完會收到 PDF 連結。" },
    ]},

  { id: "lec1", kind: "學術講座", title: "生物學:蜜蜂的搖擺舞", icon: "🐝",
    lines: [
      { sp: "M", en: "Today I want to look at one of the most remarkable communication systems in the animal world: the waggle dance of the honeybee." },
      { sp: "M", en: "When a forager returns to the hive after finding a rich patch of flowers, she walks a figure-eight pattern on the vertical surface of the comb." },
      { sp: "M", en: "The straight run in the middle encodes direction. The angle of that run relative to vertical equals the angle of the food source relative to the sun." },
      { sp: "M", en: "Distance is encoded separately, in the duration of the waggling. Roughly speaking, one additional second corresponds to another kilometer of flight." },
      { sp: "M", en: "Now, what makes this genuinely symbolic is that the dance refers to something the other bees cannot see, smell, or touch at that moment." },
      { sp: "M", en: "Outside of human language, very few systems in nature can point to a place that is simply not there." },
    ],
    questions: [
      { q: "What is the lecture mainly about?", opts: ["How honeybees communicate the location of food", "How honeybees build the comb inside a hive", "Why honeybee populations are declining", "How bees distinguish different kinds of flowers"], note: "開場即點題:蜜蜂的搖擺舞這套溝通系統。" },
      { q: "According to the professor, what does the angle of the straight run indicate?", opts: ["The direction of the food relative to the sun", "The size of the flower patch", "The number of bees needed", "The time of day the food was found"], note: "直線段的角度相對垂直線 = 食物相對太陽的角度。" },
      { q: "Why does the professor call the dance symbolic?", opts: ["It refers to something the other bees cannot perceive at the time", "It is performed only by the oldest bees", "It varies from one hive to another", "It must be learned by watching adults"], note: "倒數第二句:舞蹈指涉的是其他蜜蜂當下看不到、聞不到、摸不到的東西。" },
    ]},

  { id: "lec2", kind: "學術講座", title: "藝術史:印象派為何走出畫室", icon: "🖼️",
    lines: [
      { sp: "W", en: "Last week we ended with the Salon and its rules. Today let's ask a simpler question: why did the Impressionists start painting outdoors?" },
      { sp: "W", en: "Part of the answer is technological. In eighteen forty-one, an American painter patented the collapsible metal paint tube." },
      { sp: "W", en: "Before that, artists ground pigments and stored them in pig bladders, which dried out quickly and were nearly impossible to carry." },
      { sp: "W", en: "The tube made paint portable, and portable paint made it practical to work in a field for an entire afternoon." },
      { sp: "W", en: "That changed what got painted. Light shifts within minutes outdoors, so artists worked quickly, in short broken strokes, and finished on the spot." },
      { sp: "W", en: "I'm not saying the tube caused Impressionism. But Renoir himself said that without paint in tubes, there would have been no Impressionism." },
    ],
    questions: [
      { q: "What is the main point of the lecture?", opts: ["A technological change made outdoor painting practical for the Impressionists", "The Salon rejected all Impressionist paintings", "Renoir invented a new kind of brush stroke", "Pig bladders produced better colors than metal tubes"], note: "全篇論證:可攜式顏料管讓戶外作畫成為可能。" },
      { q: "According to the professor, what was the problem with pig bladders?", opts: ["The paint dried out and they were hard to carry", "They were too expensive for most artists", "They could hold only dark colors", "They were banned by the Salon"], note: "第三句明說顏料乾得快且幾乎無法攜帶。" },
      { q: "Why does the professor mention Renoir at the end?", opts: ["To support the claim with a painter's own testimony", "To argue that Renoir invented the paint tube", "To show that Renoir disliked working outdoors", "To introduce the topic of the next lecture"], note: "教授先說「我不是說顏料管導致印象派」,再引 Renoir 的話佐證其重要性。" },
    ]},
];

// ---------- Speaking 獨立口說(Task 1 型:15 秒準備 + 45 秒作答)----------
// keys:內容關鍵詞群組(任一同義詞命中即得分);sample:示範回答(可播放音檔)
const TOEFL_SPEAKING = [
  { id: "sp1", type: "偏好題", icon: "👥",
    prompt: "Some students prefer to study alone, while others prefer to study in a group. Which do you prefer, and why? Include details and examples in your explanation.",
    zh: "有些學生偏好獨自讀書,有些偏好小組共讀。你偏好哪一種?請說明理由並舉例。",
    prep: 15, speak: 45,
    keys: [["prefer", "choose", "rather"], ["alone", "group", "myself", "others"], ["because", "since", "reason"], ["example", "instance", "time when"], ["focus", "concentrate", "distract", "explain", "discuss"]],
    tips: ["第一句就表態:I prefer studying alone / in a group.", "給兩個理由,每個理由後面接一個具體例子(上學期某堂課、某次考試)。", "用 First… Second… 或 The main reason… Another reason… 讓結構清楚。", "最後一句收尾:That's why I prefer…"],
    sample: "I prefer studying alone, mainly for two reasons. First, I concentrate much better in a quiet room. When I studied with friends last semester, we spent half the time chatting, and I finished only two chapters in three hours. Second, studying alone lets me control the pace. If a concept is difficult, I can slow down and reread it without worrying that others are waiting for me. I do join a group before big exams, but only to check answers. That's why, for daily studying, I prefer to work on my own." },

  { id: "sp2", type: "同意與否", icon: "⚖️",
    prompt: "Do you agree or disagree with the following statement? Universities should require every student to take at least one course in the arts. Use specific reasons and examples to support your answer.",
    zh: "你是否同意:大學應要求每位學生至少修一門藝術課程?請用具體理由與例子支持你的立場。",
    prep: 15, speak: 45,
    keys: [["agree", "disagree"], ["university", "students", "course", "class"], ["because", "since", "reason"], ["example", "instance"], ["creative", "creativity", "balance", "skill", "required", "elective"]],
    tips: ["立場先講清楚:I agree / I disagree with this statement.", "理由講兩個就好,寧可深入也不要淺淺帶過四個。", "舉自己或同學的真實經驗最有說服力。", "留 5 秒收尾,不要話說到一半被切斷。"],
    sample: "I agree that universities should require at least one arts course. To begin with, art classes train a different kind of thinking. In my design elective, I had to defend my choices out loud every week, and that made me a clearer speaker in my engineering classes too. In addition, a required course pushes students to try something they would never choose. My roommate signed up for photography only because he had to, and now he shoots for the campus newspaper. For these reasons, one arts course should be part of every degree." },

  { id: "sp3", type: "描述題", icon: "🏞️",
    prompt: "Describe a place in your hometown that you enjoy visiting. Explain why this place is important to you, using specific details in your response.",
    zh: "描述你家鄉一個你喜歡去的地方,並用具體細節說明它對你的意義。",
    prep: 15, speak: 45,
    keys: [["place", "park", "market", "library", "café", "temple", "river", "beach"], ["hometown", "city", "town", "near", "house", "home"], ["because", "since", "reason", "what makes", "important"], ["visit", "go", "spend", "walk", "sit", "stay"], ["quiet", "busy", "memory", "routine", "family", "friends", "relax", "stress", "think", "evening"]],
    tips: ["先一句話點出地點與它是什麼:There's a night market near my house…", "用五感細節(聲音、氣味、畫面)讓描述具體。", "把「為什麼重要」連到一段記憶或習慣,不要只說 I like it.", "45 秒約 100–120 字,講得完整比講得快重要。"],
    sample: "My favorite place is a riverside park about ten minutes from my house. It's nothing fancy — just a walking path, some old banyan trees, and a few basketball courts. I go there almost every evening after class. What makes it important to me is the routine. When I was preparing for university entrance exams, I walked there every night to clear my head, and I still do that whenever I feel stressed. The sound of the river and the noise from the courts somehow help me think. It's the one place in my city where I always slow down." },

  { id: "sp4", type: "取捨題", icon: "🔀",
    prompt: "Some people learn best by reading about a subject; others learn best by doing it. Which approach works better for you, and why? Give specific examples.",
    zh: "有人靠閱讀學得最好,有人靠實作學得最好。哪一種對你更有效?請舉具體例子。",
    prep: 15, speak: 45,
    keys: [["learn", "learning", "study"], ["reading", "doing", "practice", "hands-on"], ["because", "since", "reason"], ["example", "instance", "when I"], ["remember", "understand", "mistake", "skill"]],
    tips: ["直接選一邊,不要說 both——回答時間不夠支撐兩邊。", "用一個「失敗再成功」的例子最有力量。", "可以承認另一邊有用,再說明為何你的選擇更好(讓步句加分)。", "結尾重述立場一次。"],
    sample: "I definitely learn better by doing. Reading gives me the vocabulary, but it doesn't stay with me until I use it. For example, I read three chapters about database design last year and understood almost nothing. Then I built a small booking website for a class project, and within two weekends the same concepts finally made sense, because I had to fix my own mistakes. I still read before I start, since it saves me from obvious errors. But the real learning happens when I actually build something, so hands-on practice works better for me." },
];

// ---------- Writing 學術討論題(Academic Discussion Task)----------
const TOEFL_WRITING = [
  { id: "wr1", course: "Environmental Policy", icon: "🌍",
    professor: "Cities around the world are considering whether to make public transportation free for all riders. Supporters say it reduces traffic and pollution; critics say the money would be better spent improving service. If you were advising a city government, would you recommend making public transit free? Why or why not?",
    posts: [
      { who: "Marta", text: "I would make it free. Fares are a heavy burden on low-income commuters, and every car we take off the road improves air quality for everyone. Cities already subsidize roads and parking without asking drivers to cover the full cost." },
      { who: "Kenji", text: "I'm not convinced. In cities that removed fares, most new riders had been walking or cycling, not driving. If we want fewer cars, the money should go into faster, more frequent service — that's what actually persuades drivers to switch." },
    ],
    zh: "教授提問:是否建議市政府讓大眾運輸免費?兩位同學已提出正反意見,請寫出你的立場並加入新的理由或例子(至少 100 字)。",
    minWords: 100,
    keys: [["free", "fare", "fares"], ["transit", "transport", "bus", "subway", "train"], ["traffic", "pollution", "car", "cars", "emissions"], ["service", "frequency", "frequent", "invest", "funding", "budget"], ["example", "instance", "city", "cities"]],
    tips: ["先明確表態,再回應至少一位同學的論點(同意或反駁)。", "加入他們沒提到的角度才是高分關鍵——例如財源、公平性、實際城市案例。", "用 While Kenji is right that…, I still think… 這類讓步句展現論證層次。", "目標 100–140 字,寫完留 2 分鐘檢查主動詞與單複數。"],
    sample: "I side with Kenji, though for a slightly different reason than the one he gives. Free fares are politically attractive precisely because they are visible, while frequency improvements are not — and that is exactly why cities tend to fund the wrong one. Marta is right that fares burden low-income riders, but a targeted discount for those riders costs a fraction of universal free service and leaves money for operations. Tallinn made transit free in 2013 and saw car use fall by only a few percent, while cities that invested in frequency saw much larger shifts. If the goal is fewer cars rather than cheaper rides, the budget should buy buses and drivers, not free tickets." },

  { id: "wr2", course: "Educational Technology", icon: "💻",
    professor: "Many universities now record every lecture and post the video online. Some instructors report that attendance drops sharply when recordings are available. Should lecture recordings be made available to all students by default? Defend your position.",
    posts: [
      { who: "Priya", text: "Recordings should absolutely be the default. Students who work night shifts or care for family members shouldn't be penalized for missing a fixed time slot, and rewatching a difficult explanation is exactly how I learned statistics." },
      { who: "Tomás", text: "I worry about what we lose. Discussion only happens when people are in the room, and a recording turns a class into a broadcast. Attendance dropped by half in my chemistry course, and the questions afterwards were much shallower." },
    ],
    zh: "教授提問:大學是否應預設將所有課程錄影公開?兩位同學意見相左,請提出你的立場、回應他們的論點,並加入新的理由(至少 100 字)。",
    minWords: 100,
    keys: [["recording", "recordings", "record", "video"], ["attendance", "attend", "class", "lecture"], ["students", "learning", "learn"], ["discussion", "question", "questions", "interaction", "engage"], ["example", "instance", "because", "however"]],
    tips: ["立場可以是折衷方案(例如:錄影公開但討論課不錄),但必須說清楚界線。", "直接回應 Priya 或 Tomás 的具體說法,不要各講各的。", "用一個機制解釋現象:為什麼有錄影就沒人來?怎麼設計可以兩全?", "檢查時態一致(討論通則用現在式)。"],
    sample: "Both positions assume that lectures and discussions serve the same purpose, and I think that assumption is what causes the disagreement. Priya's argument applies to content delivery: if a professor spends fifty minutes explaining hypothesis testing, there is no pedagogical reason that explanation must be heard live, and recording it removes a real barrier for working students. Tomás's argument applies to interaction, which genuinely collapses when the room is half empty. The sensible policy therefore separates the two: record and post the lecture portion by default, but make seminars and problem sessions unrecorded and required. My own department did this last year, and attendance at problem sessions actually rose, because students arrived having already watched the explanation." },
];
