// ============================================================
//  📕 多益 13 大主題字彙庫(1/4):企業發展・辦公室・人事招募
//  欄位:w 單字 / p 詞性 / zh 中文 / d 英英釋義
//        syn 同義 / ant 反義 / ph 重點片語 / n 解析 / r 字根字首
// ============================================================

const TOEIC_VOCAB = [
  { id: "corp", no: 1, name: "企業發展", en: "Corporate Development", icon: "🏗️",
    map: { center: "企業發展", branches: [
      { label: "併購擴張", ws: ["acquire", "merger", "subsidiary", "expansion", "alliance"] },
      { label: "組織治理", ws: ["board", "executive", "shareholder", "stake", "corporation"] },
      { label: "策略規劃", ws: ["strategy", "initiative", "forecast", "diversify", "restructure"] },
      { label: "契約法務", ws: ["clause", "provision", "terminate", "breach", "comply"] },
      { label: "研發成果", ws: ["patent", "prototype", "feasibility", "milestone", "launch"] },
    ]},
    list: [
      { w: "acquire", p: "v.", zh: "收購;取得", d: "to buy a company, or to gain something",
        syn: ["obtain", "purchase", "take over"], ant: ["sell", "divest"],
        ph: [["acquire a stake in", "取得…的股份"], ["newly acquired skills", "新習得的技能"]],
        n: "商業併購用 acquire,買日用品用 buy。名詞是 acquisition,形容詞 acquired(後天取得的)。",
        r: "ac-(朝向) + quire(尋求) → 去追求而得到" },
      { w: "acquisition", p: "n.", zh: "收購案;取得", d: "the act of buying a company or gaining something",
        syn: ["takeover", "purchase"], ant: ["divestiture"],
        ph: [["a hostile acquisition", "敵意併購"], ["language acquisition", "語言習得"]],
        n: "多益常考「M&A = mergers and acquisitions 併購」。" },
      { w: "merger", p: "n.", zh: "合併", d: "the joining of two companies into one",
        syn: ["consolidation", "amalgamation"], ant: ["split", "spin-off"],
        ph: [["merger talks", "併購談判"], ["a merger between A and B", "A 與 B 的合併"]],
        n: "merger 是「兩家合成一家」,acquisition 是「一家買下另一家」,考題常拿來對比。",
        r: "merge(融合) + -er(名詞) → 融合的動作" },
      { w: "subsidiary", p: "n./adj.", zh: "子公司;附屬的", d: "a company controlled by a larger one",
        syn: ["affiliate", "branch"], ant: ["parent company"],
        ph: [["a wholly owned subsidiary", "全資子公司"], ["play a subsidiary role", "扮演次要角色"]],
        r: "sub-(在下) + sid(坐) + -iary → 坐在下位的" },
      { w: "headquarters", p: "n.", zh: "總部", d: "the main office of an organization",
        syn: ["head office", "main office"], ant: ["branch"],
        ph: [["relocate its headquarters", "遷移總部"], ["be headquartered in", "總部設於"]],
        n: "字尾永遠有 s,單複數同形:The headquarters is/are in Tokyo. 兩種都可接受。" },
      { w: "expansion", p: "n.", zh: "擴張", d: "the process of becoming larger",
        syn: ["growth", "enlargement"], ant: ["contraction", "downsizing"],
        ph: [["overseas expansion", "海外擴張"], ["expansion plan", "擴張計畫"]],
        r: "ex-(向外) + pand(展開) + -sion → 向外展開" },
      { w: "venture", p: "n./v.", zh: "(有風險的)事業;冒險投入", d: "a new business activity involving risk",
        syn: ["undertaking", "enterprise"],
        ph: [["a joint venture", "合資企業"], ["venture capital", "創業投資"]],
        n: "joint venture(合資)是多益高頻詞組;動詞 venture into 表示「跨足(新領域)」。" },
      { w: "stake", p: "n.", zh: "股份;利害關係", d: "a share in a business, or an interest in something",
        syn: ["share", "interest"],
        ph: [["hold a 40% stake", "持有四成股份"], ["at stake", "岌岌可危;成敗攸關"]],
        n: "at stake 是慣用語:Millions of dollars are at stake.(數百萬美元的成敗在此一舉)" },
      { w: "shareholder", p: "n.", zh: "股東", d: "a person who owns shares in a company",
        syn: ["stockholder", "investor"],
        ph: [["the annual shareholders' meeting", "年度股東大會"], ["shareholder value", "股東價值"]],
        r: "share(股份) + holder(持有者)" },
      { w: "stakeholder", p: "n.", zh: "利害關係人", d: "anyone affected by a company's decisions",
        n: "stakeholder(員工、客戶、社區都算)範圍比 shareholder(只有股東)大,易混淆考點。" },
      { w: "board", p: "n.", zh: "董事會", d: "the group of people who manage a company",
        ph: [["the board of directors", "董事會"], ["sit on the board", "擔任董事"], ["on board", "加入團隊;在機上"]],
        n: "board 也有「板子、伙食、登機」等義;on board 在旅遊情境是「在機上」,職場情境是「加入」。" },
      { w: "executive", p: "n./adj.", zh: "高階主管;執行的", d: "a senior manager in a company",
        syn: ["director", "officer"], ant: ["subordinate"],
        ph: [["a chief executive officer (CEO)", "執行長"], ["executive summary", "摘要;執行摘要"]],
        r: "ex-(出) + secut(跟隨) + -ive → 跟到底並執行的人" },
      { w: "corporation", p: "n.", zh: "股份有限公司", d: "a large company or group of companies",
        syn: ["firm", "enterprise"],
        ph: [["a multinational corporation", "跨國企業"]],
        r: "corpor(身體) + -ation → 由眾人組成的「法人身體」" },
      { w: "corporate", p: "adj.", zh: "公司的;企業的", d: "relating to a large company",
        ph: [["corporate culture", "企業文化"], ["corporate social responsibility", "企業社會責任"]],
        n: "corporate 是形容詞,corporation 是名詞;Part 5 常考詞性選擇。" },
      { w: "entity", p: "n.", zh: "實體;法人", d: "something that exists as a single, separate unit",
        syn: ["organization", "body"],
        ph: [["a separate legal entity", "獨立法人"]] },
      { w: "strategy", p: "n.", zh: "策略", d: "a plan for achieving a long-term goal",
        syn: ["plan", "approach"], ant: ["improvisation"],
        ph: [["a growth strategy", "成長策略"], ["strategic partnership", "策略聯盟"]],
        n: "形容詞是 strategic(重音在第二音節),副詞 strategically。" },
      { w: "initiative", p: "n.", zh: "新措施;主動性", d: "a new plan, or the ability to act without being told",
        syn: ["program", "scheme"],
        ph: [["launch an initiative", "推動新措施"], ["take the initiative", "主動出擊"]],
        n: "兩個意思差很多:a green initiative(環保計畫)vs. show initiative(展現主動)。" },
      { w: "restructure", p: "v.", zh: "重組;改組", d: "to organize a company in a new way",
        syn: ["reorganize", "overhaul"],
        ph: [["restructure the department", "重組部門"], ["debt restructuring", "債務重組"]],
        r: "re-(重新) + structure(結構)" },
      { w: "diversify", p: "v.", zh: "多角化;分散", d: "to start doing more different types of business",
        syn: ["expand into", "branch out"], ant: ["specialize", "concentrate"],
        ph: [["diversify into new markets", "跨足新市場"], ["a diversified portfolio", "多元投資組合"]],
        r: "divers(不同的) + -ify(使…化) → 使變得多樣" },
      { w: "forecast", p: "n./v.", zh: "預測", d: "a statement about what will happen in the future",
        syn: ["projection", "prediction"],
        ph: [["a sales forecast", "銷售預測"], ["as forecast", "如同預測的"]],
        n: "過去式可用 forecast 或 forecasted,商用英文多用 forecast。",
        r: "fore-(事前) + cast(投擲) → 事先拋出的判斷" },
      { w: "milestone", p: "n.", zh: "里程碑", d: "an important stage in a project",
        syn: ["landmark", "turning point"],
        ph: [["reach a milestone", "達到里程碑"], ["a major milestone", "重大里程碑"]] },
      { w: "feasibility", p: "n.", zh: "可行性", d: "how possible or practical something is",
        syn: ["viability", "practicality"],
        ph: [["a feasibility study", "可行性研究"]],
        n: "形容詞 feasible(可行的)= doable;不要和 possible(有可能的)混用。" },
      { w: "prototype", p: "n.", zh: "原型;試作品", d: "the first model of a new product",
        syn: ["model", "mock-up"],
        ph: [["build a prototype", "做出原型機"]],
        r: "proto-(最初) + type(型) → 最初的型" },
      { w: "patent", p: "n./v.", zh: "專利;取得專利", d: "the legal right to be the only maker of a product",
        ph: [["file for a patent", "申請專利"], ["a patent expires", "專利到期"]],
        n: "動詞 patent 唸 /ˈpætnt/(美);patent pending 表示「專利申請中」。" },
      { w: "launch", p: "v./n.", zh: "推出;發表", d: "to make a new product available for the first time",
        syn: ["release", "roll out", "introduce"], ant: ["discontinue", "withdraw"],
        ph: [["launch a new line", "推出新產品線"], ["a product launch", "產品發表會"]] },
      { w: "partnership", p: "n.", zh: "合夥;夥伴關係", d: "a business relationship between two parties",
        syn: ["alliance", "collaboration"],
        ph: [["enter into a partnership", "建立夥伴關係"], ["in partnership with", "與…合作"]] },
      { w: "alliance", p: "n.", zh: "聯盟", d: "an agreement between organizations to work together",
        syn: ["coalition", "partnership"], ant: ["rivalry"],
        ph: [["form an alliance", "結盟"], ["a strategic alliance", "策略聯盟"]] },
      { w: "competitor", p: "n.", zh: "競爭者", d: "a company selling similar products",
        syn: ["rival", "contender"],
        ph: [["outperform competitors", "表現優於同業"], ["a competitive edge", "競爭優勢"]],
        n: "competitive(有競爭力的)vs. competent(有能力的)是常見陷阱字。" },
      { w: "sector", p: "n.", zh: "產業;部門", d: "one part of a country's economy or business area",
        syn: ["industry", "field"],
        ph: [["the manufacturing sector", "製造業"], ["the public sector", "公部門"]] },
      { w: "negotiate", p: "v.", zh: "談判;協商", d: "to discuss in order to reach an agreement",
        syn: ["bargain", "hammer out"],
        ph: [["negotiate the terms", "協商條件"], ["a non-negotiable price", "不二價"]],
        r: "neg-(否定) + oti(閒暇) → 沒空閒地談事情" },
      { w: "clause", p: "n.", zh: "條款", d: "a particular part of a written legal agreement",
        syn: ["provision", "article"],
        ph: [["a confidentiality clause", "保密條款"], ["under clause 5", "依第五條"]] },
      { w: "provision", p: "n.", zh: "條款;供應", d: "a condition in an agreement; the act of supplying",
        ph: [["the provisions of the contract", "合約條款"], ["make provision for", "為…做準備"]],
        n: "多益兩義都考:法律條款,以及「提供」(the provision of services)。" },
      { w: "terminate", p: "v.", zh: "終止", d: "to end a contract or agreement officially",
        syn: ["end", "cancel", "call off"], ant: ["renew", "extend"],
        ph: [["terminate a contract", "終止合約"], ["with immediate effect", "立即生效"]],
        r: "termin(界線;終點) + -ate → 走到終點" },
      { w: "renew", p: "v.", zh: "續約;更新", d: "to make an agreement continue for a longer time",
        syn: ["extend", "prolong"], ant: ["terminate", "cancel"],
        ph: [["renew a lease", "續租"], ["automatically renewed", "自動續約"]],
        r: "re-(再) + new(新的) → 再變新" },
      { w: "breach", p: "n./v.", zh: "違約;破壞", d: "an act of breaking a rule or agreement",
        syn: ["violation", "infringement"], ant: ["compliance"],
        ph: [["a breach of contract", "違約"], ["a data breach", "資料外洩"]] },
      { w: "comply", p: "v.", zh: "遵守", d: "to obey a rule or law",
        syn: ["conform", "adhere"], ant: ["violate", "breach"],
        ph: [["comply with regulations", "遵守法規"], ["in compliance with", "依照…"]],
        n: "介係詞固定用 with:comply with(不是 comply to),Part 5 高頻考點。" },
      { w: "revenue", p: "n.", zh: "營收", d: "the money a company receives from its business",
        syn: ["income", "turnover"], ant: ["expenditure"],
        ph: [["generate revenue", "創造營收"], ["annual revenue", "年度營收"]],
        n: "revenue 是總收入,profit 是扣掉成本後的獲利,兩者常被拿來對比出題。" },
      { w: "profit", p: "n./v.", zh: "利潤;獲利", d: "money gained after costs are paid",
        syn: ["earnings", "gain"], ant: ["loss"],
        ph: [["a profit margin", "利潤率"], ["turn a profit", "轉虧為盈"]] },
      { w: "growth", p: "n.", zh: "成長", d: "an increase in size, value or amount",
        syn: ["increase", "expansion"], ant: ["decline", "contraction"],
        ph: [["steady growth", "穩定成長"], ["a growth rate of 5%", "百分之五的成長率"]] },
      { w: "invest", p: "v.", zh: "投資", d: "to put money into something to make more money",
        syn: ["fund", "put money into"], ant: ["withdraw", "divest"],
        ph: [["invest in equipment", "投資設備"], ["a return on investment (ROI)", "投資報酬率"]],
        r: "in-(進入) + vest(衣服) → 把錢「穿」到事業上" },
    ]},

  { id: "office", no: 2, name: "辦公室", en: "Offices", icon: "🏢",
    map: { center: "辦公室", branches: [
      { label: "會議", ws: ["agenda", "minutes", "chair", "adjourn", "conference"] },
      { label: "文件", ws: ["memo", "draft", "circulate", "attachment", "confidential"] },
      { label: "時程", ws: ["schedule", "deadline", "postpone", "reschedule", "overtime"] },
      { label: "人與空間", ws: ["colleague", "supervisor", "department", "premises", "facility"] },
      { label: "設備", ws: ["equipment", "supplies", "photocopier", "maintenance", "stationery"] },
    ]},
    list: [
      { w: "agenda", p: "n.", zh: "議程", d: "a list of items to be discussed at a meeting",
        syn: ["schedule", "program"],
        ph: [["on the agenda", "在議程上"], ["top of the agenda", "首要議題"]],
        n: "原為 agendum 的複數,現代英文當單數用:The agenda is long." },
      { w: "minutes", p: "n.", zh: "會議紀錄", d: "a written record of what was said at a meeting",
        ph: [["take the minutes", "做會議紀錄"], ["circulate the minutes", "分發會議紀錄"]],
        n: "永遠用複數;和「分鐘」同形,靠上下文判斷,是聽力常見陷阱。" },
      { w: "chair", p: "v./n.", zh: "主持;主席", d: "to lead a meeting; the person leading it",
        syn: ["preside over", "moderate"],
        ph: [["chair a meeting", "主持會議"], ["the chairperson", "主席"]] },
      { w: "adjourn", p: "v.", zh: "休會;延期", d: "to stop a meeting, intending to continue later",
        syn: ["suspend", "recess"], ant: ["convene", "resume"],
        ph: [["adjourn the meeting", "宣布休會"], ["adjourn until Friday", "延到週五"]] },
      { w: "convene", p: "v.", zh: "召開;集合", d: "to bring people together for a meeting",
        syn: ["assemble", "call together"], ant: ["adjourn", "disperse"],
        r: "con-(一起) + ven(來) → 一起前來" },
      { w: "conference", p: "n.", zh: "會議;研討會", d: "a large formal meeting",
        ph: [["a conference call", "電話會議"], ["hold a conference", "舉辦研討會"]],
        r: "con-(一起) + fer(帶來) → 把想法一起帶來" },
      { w: "attend", p: "v.", zh: "出席", d: "to be present at an event",
        syn: ["be present at", "take part in"], ant: ["miss", "skip"],
        ph: [["attend a seminar", "出席研討會"], ["attend to a matter", "處理事情"]],
        n: "attend 是及物動詞,不加 to:attend the meeting(✗ attend to the meeting 意思變成「處理」)。" },
      { w: "attendance", p: "n.", zh: "出席(率)", d: "the number of people present, or the act of attending",
        ph: [["in attendance", "出席在場"], ["poor attendance", "出席率低"]] },
      { w: "memo", p: "n.", zh: "備忘錄;內部通知", d: "a short written message within a company",
        syn: ["notice", "bulletin"],
        ph: [["circulate a memo", "發送內部通知"], ["as per the memo", "依照備忘錄"]],
        n: "memorandum 的簡稱,Part 7 常見文體,開頭固定有 To / From / Date / Subject。" },
      { w: "draft", p: "n./v.", zh: "草稿;起草", d: "an early version of a document",
        syn: ["outline", "rough copy"], ant: ["final version"],
        ph: [["a first draft", "初稿"], ["draft a proposal", "起草提案"]] },
      { w: "revise", p: "v.", zh: "修訂", d: "to change a document to improve it",
        syn: ["amend", "update", "modify"],
        ph: [["a revised edition", "修訂版"], ["revise the figures", "修正數字"]],
        r: "re-(再) + vis(看) → 再看一次" },
      { w: "circulate", p: "v.", zh: "傳閱;分發", d: "to send information to a group of people",
        syn: ["distribute", "pass around"],
        ph: [["circulate the agenda", "傳閱議程"]],
        r: "circul(圓圈) + -ate → 繞一圈傳給大家" },
      { w: "distribute", p: "v.", zh: "分發;配送", d: "to give things to several people",
        syn: ["hand out", "allocate"], ant: ["collect", "gather"],
        ph: [["distribute handouts", "分發講義"]] },
      { w: "attachment", p: "n.", zh: "附件", d: "a file sent with an email",
        syn: ["enclosure"],
        ph: [["see the attachment", "請見附件"], ["attached please find", "隨函附上"]],
        n: "email 用 attachment,紙本信件用 enclosure,兩字在 Part 7 都會出現。" },
      { w: "confidential", p: "adj.", zh: "機密的", d: "meant to be kept secret",
        syn: ["classified", "private"], ant: ["public", "open"],
        ph: [["strictly confidential", "極機密"], ["keep it confidential", "保密"]],
        r: "con-(完全) + fid(信任) + -ential → 只給信得過的人" },
      { w: "notify", p: "v.", zh: "通知", d: "to officially tell someone about something",
        syn: ["inform", "advise"],
        ph: [["notify sb. of sth.", "通知某人某事"], ["prior notification", "事先通知"]],
        n: "notify 後面接「人」:notify the staff of the change,介係詞用 of。" },
      { w: "remind", p: "v.", zh: "提醒", d: "to make someone remember something",
        ph: [["remind sb. to do", "提醒某人做…"], ["a friendly reminder", "溫馨提醒"]],
        n: "remind sb. to do(提醒去做)vs. remind sb. of sth.(讓人想起某事),用法不同。" },
      { w: "schedule", p: "n./v.", zh: "時程表;安排", d: "a plan of times for events",
        syn: ["timetable", "itinerary"],
        ph: [["ahead of schedule", "提前"], ["behind schedule", "落後進度"], ["as scheduled", "按原定計畫"]],
        n: "美式唸 /ˈskedʒuːl/,英式唸 /ˈʃedjuːl/,聽力兩種都可能出現。" },
      { w: "reschedule", p: "v.", zh: "改期", d: "to change the time of an event",
        syn: ["move", "postpone"],
        ph: [["reschedule for Monday", "改到週一"]],
        r: "re-(重新) + schedule" },
      { w: "postpone", p: "v.", zh: "延期", d: "to move an event to a later time",
        syn: ["put off", "delay", "defer"], ant: ["advance", "bring forward"],
        ph: [["postpone until further notice", "延期至另行通知"]],
        n: "postpone 後面接動名詞:postpone making a decision(✗ to make)。",
        r: "post-(之後) + pon(放置) → 放到後面" },
      { w: "deadline", p: "n.", zh: "截止期限", d: "the time by which something must be finished",
        syn: ["due date", "cutoff"],
        ph: [["meet the deadline", "趕上期限"], ["miss the deadline", "錯過期限"], ["a tight deadline", "很趕的期限"]] },
      { w: "overtime", p: "n./adv.", zh: "加班(費)", d: "extra hours worked beyond normal hours",
        ph: [["work overtime", "加班"], ["overtime pay", "加班費"]] },
      { w: "workload", p: "n.", zh: "工作量", d: "the amount of work a person has to do",
        ph: [["a heavy workload", "沉重的工作量"], ["ease the workload", "減輕工作量"]] },
      { w: "workflow", p: "n.", zh: "工作流程", d: "the order in which work moves through a process",
        syn: ["process", "procedure"] },
      { w: "procedure", p: "n.", zh: "程序;步驟", d: "the official way of doing something",
        syn: ["process", "protocol"],
        ph: [["standard operating procedure (SOP)", "標準作業程序"], ["follow the procedure", "依程序進行"]],
        r: "pro-(向前) + ced(走) + -ure → 一步步向前走的方式" },
      { w: "protocol", p: "n.", zh: "規範;禮節", d: "the accepted rules for behavior or procedure",
        syn: ["etiquette", "guidelines"],
        ph: [["safety protocol", "安全規範"]] },
      { w: "coordinate", p: "v.", zh: "協調", d: "to organize people or activities to work together",
        syn: ["organize", "arrange"],
        ph: [["coordinate with the team", "與團隊協調"], ["a project coordinator", "專案協調人"]],
        r: "co-(共同) + ordin(順序) → 把順序排在一起" },
      { w: "delegate", p: "v./n.", zh: "授權;代表", d: "to give work to someone else; a representative",
        syn: ["assign", "hand over"],
        ph: [["delegate tasks", "分派任務"], ["a delegate from Seoul", "首爾來的代表"]],
        n: "動詞唸 /ˈdelɪɡeɪt/,名詞唸 /ˈdelɪɡət/,是聽力的重音變化考點。" },
      { w: "prioritize", p: "v.", zh: "排定優先順序", d: "to decide which things are most important",
        ph: [["prioritize urgent tasks", "優先處理緊急事項"], ["top priority", "最高優先"]],
        r: "prior(在先的) + -ize(使…化)" },
      { w: "colleague", p: "n.", zh: "同事", d: "a person you work with",
        syn: ["coworker", "associate"],
        ph: [["a former colleague", "前同事"]],
        n: "拼字陷阱:col-league,不是 collegue;和 college(大學)只差一個字母。" },
      { w: "supervisor", p: "n.", zh: "主管", d: "a person who manages other workers",
        syn: ["manager", "superior"], ant: ["subordinate", "staff member"],
        ph: [["report to your supervisor", "向主管回報"]],
        r: "super-(在上) + vis(看) + -or → 在上面看著的人" },
      { w: "subordinate", p: "n./adj.", zh: "部屬;下級的", d: "a person of lower rank",
        ant: ["supervisor", "superior"],
        r: "sub-(在下) + ordin(順序) → 順序在下的" },
      { w: "department", p: "n.", zh: "部門", d: "a section of a company",
        syn: ["division", "unit"],
        ph: [["the accounting department", "會計部"], ["interdepartmental", "跨部門的"]] },
      { w: "premises", p: "n.", zh: "營業場所;建物", d: "the building and land a business uses",
        syn: ["site", "property"],
        ph: [["on the premises", "在本場所內"], ["vacate the premises", "撤離場所"]],
        n: "永遠複數;on the premises 是公告常用語,例:No smoking on the premises." },
      { w: "facility", p: "n.", zh: "設施", d: "a place or equipment provided for a purpose",
        syn: ["amenity", "installation"],
        ph: [["parking facilities", "停車設施"], ["a manufacturing facility", "生產基地"]] },
      { w: "equipment", p: "n.", zh: "設備", d: "the tools or machines needed for an activity",
        syn: ["apparatus", "gear"],
        ph: [["office equipment", "辦公設備"], ["a piece of equipment", "一件設備"]],
        n: "不可數名詞!沒有 equipments,要數用 a piece of equipment,Part 5 常考。" },
      { w: "supplies", p: "n.", zh: "用品;補給", d: "items needed for regular use",
        ph: [["office supplies", "辦公用品"], ["run out of supplies", "用品用完"]] },
      { w: "stationery", p: "n.", zh: "文具", d: "paper, pens and other writing materials",
        n: "stationery(文具,e = envelope)vs. stationary(靜止的,a = at rest),超經典拼字題。" },
      { w: "photocopier", p: "n.", zh: "影印機", d: "a machine that makes copies of documents",
        ph: [["the copier is jammed", "影印機卡紙了"], ["out of order", "故障中"]] },
      { w: "maintenance", p: "n.", zh: "維護;保養", d: "the work of keeping something in good condition",
        syn: ["upkeep", "servicing"],
        ph: [["routine maintenance", "例行保養"], ["under maintenance", "維修中"]],
        n: "動詞是 maintain,注意名詞拼字中間是 -ten-(maintenance),常拼錯。" },
      { w: "extension", p: "n.", zh: "分機;延長", d: "an inside phone number; making something longer",
        ph: [["dial extension 204", "撥分機 204"], ["an extension of the deadline", "延長期限"]],
        n: "辦公室情境多半是「分機」,聽力會唸 extension two-oh-four。" },
    ]},

  { id: "hr", no: 3, name: "人事與招募", en: "Personnel / Recruitment", icon: "👔",
    map: { center: "人事招募", branches: [
      { label: "應徵", ws: ["applicant", "resume", "qualification", "credential", "vacancy"] },
      { label: "甄選", ws: ["recruit", "screen", "shortlist", "interview", "hire"] },
      { label: "到職", ws: ["onboarding", "probation", "orientation", "trainee", "mentor"] },
      { label: "薪酬福利", ws: ["salary", "wage", "bonus", "allowance", "compensation"] },
      { label: "異動", ws: ["promotion", "transfer", "resign", "retire", "layoff"] },
    ]},
    list: [
      { w: "applicant", p: "n.", zh: "應徵者", d: "a person who formally asks for a job",
        syn: ["candidate", "job seeker"],
        ph: [["a qualified applicant", "符合資格的應徵者"], ["applicants must submit", "應徵者須繳交"]],
        r: "ap-(朝向) + plic(摺疊;貼上) + -ant(人) → 把申請書遞上的人" },
      { w: "candidate", p: "n.", zh: "候選人", d: "someone being considered for a job",
        syn: ["applicant", "nominee"],
        ph: [["the ideal candidate", "理想人選"], ["a strong candidate", "有力的人選"]],
        n: "applicant 是「投了履歷的人」,candidate 是「已進入考慮名單的人」,語意有先後。" },
      { w: "resume", p: "n.", zh: "履歷", d: "a short written record of your education and work",
        syn: ["CV", "curriculum vitae"],
        ph: [["submit your resume", "遞交履歷"], ["update your resume", "更新履歷"]],
        n: "名詞 résumé 唸 /ˈrezəmeɪ/,和動詞 resume(/rɪˈzuːm/ 恢復)同形不同音,聽力陷阱。" },
      { w: "qualification", p: "n.", zh: "資格;學經歷", d: "a skill or achievement that makes you suitable",
        syn: ["credential", "requirement"],
        ph: [["meet the qualifications", "符合資格"], ["a qualified technician", "合格技師"]] },
      { w: "credential", p: "n.", zh: "資歷;證件", d: "a document proving your ability or identity",
        syn: ["certificate", "qualification"],
        ph: [["verify credentials", "查核資歷"]] },
      { w: "vacancy", p: "n.", zh: "職缺;空房", d: "a job or room that is available",
        syn: ["opening", "position"], ant: ["full occupancy"],
        ph: [["fill a vacancy", "補上職缺"], ["No Vacancy", "客滿(飯店招牌)"]],
        n: "職場情境是「職缺」,旅遊情境是「空房」,兩大情境都會考。" },
      { w: "recruit", p: "v./n.", zh: "招募;新進人員", d: "to find new people to join a company",
        syn: ["hire", "take on"], ant: ["dismiss", "lay off"],
        ph: [["recruit staff", "招募員工"], ["a new recruit", "新人"]] },
      { w: "recruitment", p: "n.", zh: "招募", d: "the process of finding new employees",
        ph: [["a recruitment drive", "招募活動"], ["recruitment agency", "人力仲介"]] },
      { w: "screen", p: "v.", zh: "篩選", d: "to examine applications to select suitable people",
        syn: ["filter", "vet"],
        ph: [["screen applications", "篩選履歷"], ["a screening interview", "初步面試"]] },
      { w: "shortlist", p: "v./n.", zh: "列入決選名單", d: "to choose a small group from many applicants",
        ph: [["be shortlisted for", "入圍…"]] },
      { w: "interview", p: "n./v.", zh: "面試", d: "a formal meeting to assess a candidate",
        ph: [["a job interview", "工作面試"], ["the interviewer / the interviewee", "面試官/受試者"]],
        n: "-er 是主動方,-ee 是被動方(employer/employee、trainer/trainee),整組一起記。" },
      { w: "hire", p: "v.", zh: "僱用;租用", d: "to give someone a job; to rent (British)",
        syn: ["employ", "take on"], ant: ["fire", "dismiss"],
        ph: [["a new hire", "新進員工"], ["hire a car", "租車(英式)"]] },
      { w: "onboarding", p: "n.", zh: "新人到職流程", d: "the process of helping new employees settle in",
        syn: ["orientation", "induction"] },
      { w: "orientation", p: "n.", zh: "新人訓練;方向", d: "training given to new employees",
        ph: [["an orientation session", "新人說明會"]] },
      { w: "probation", p: "n.", zh: "試用期", d: "a trial period for a new employee",
        ph: [["a three-month probation period", "三個月試用期"], ["pass probation", "通過試用"]] },
      { w: "trainee", p: "n.", zh: "受訓者", d: "a person being trained for a job",
        syn: ["apprentice", "intern"], ant: ["trainer"] },
      { w: "intern", p: "n.", zh: "實習生", d: "a student working to gain experience",
        ph: [["a summer intern", "暑期實習生"], ["an internship program", "實習計畫"]] },
      { w: "mentor", p: "n./v.", zh: "導師;指導", d: "an experienced person who advises a newer one",
        syn: ["coach", "adviser"],
        ph: [["a mentoring program", "師徒制"]] },
      { w: "personnel", p: "n.", zh: "全體人員;人事", d: "the people who work for an organization",
        syn: ["staff", "workforce", "human resources"],
        ph: [["the personnel department", "人事部"], ["qualified personnel", "合格人員"]],
        n: "重音在最後:per-son-NEL;和 personal(個人的,重音在前)是聽力經典陷阱。" },
      { w: "workforce", p: "n.", zh: "勞動力;全體員工", d: "all the people who work in a company or country",
        ph: [["a skilled workforce", "熟練勞動力"], ["reduce the workforce", "縮編人力"]] },
      { w: "salary", p: "n.", zh: "薪水(月薪)", d: "fixed pay, usually monthly, for professional work",
        syn: ["pay", "compensation"],
        ph: [["a competitive salary", "有競爭力的薪資"], ["salary expectations", "期望待遇"]],
        n: "salary 按月/年計(白領),wage 按時/日計(時薪),多益兩字分得很清楚。" },
      { w: "wage", p: "n.", zh: "工資(時薪)", d: "money paid by the hour or day",
        ph: [["the minimum wage", "最低工資"], ["hourly wages", "時薪"]] },
      { w: "compensation", p: "n.", zh: "薪酬;賠償", d: "payment for work or for loss",
        syn: ["remuneration", "payment"],
        ph: [["a compensation package", "薪酬方案"], ["compensation for damages", "損害賠償"]],
        r: "com-(共同) + pens(秤重;支付) → 秤出對等的付出" },
      { w: "bonus", p: "n.", zh: "獎金", d: "extra money given as a reward",
        syn: ["incentive"],
        ph: [["a year-end bonus", "年終獎金"], ["a performance bonus", "績效獎金"]] },
      { w: "allowance", p: "n.", zh: "津貼", d: "money given regularly for a specific purpose",
        ph: [["a housing allowance", "住房津貼"], ["a travel allowance", "差旅津貼"]] },
      { w: "incentive", p: "n.", zh: "誘因;獎勵", d: "something that encourages people to work harder",
        syn: ["motivation", "reward"], ant: ["deterrent"],
        ph: [["offer incentives", "提供獎勵"], ["an incentive scheme", "獎勵制度"]] },
      { w: "benefit", p: "n./v.", zh: "福利;受益", d: "an advantage given by an employer",
        ph: [["employee benefits", "員工福利"], ["fringe benefits", "額外福利"], ["benefit from", "從…受益"]] },
      { w: "appraisal", p: "n.", zh: "考核;評估", d: "a formal judgment of someone's work",
        syn: ["evaluation", "review", "assessment"],
        ph: [["an annual performance appraisal", "年度績效考核"]] },
      { w: "evaluate", p: "v.", zh: "評估", d: "to judge the value or quality of something",
        syn: ["assess", "appraise"],
        r: "e-(向外) + valu(價值) + -ate → 把價值估算出來" },
      { w: "promotion", p: "n.", zh: "升遷;促銷", d: "a move to a more important job; advertising activity",
        ant: ["demotion"],
        ph: [["earn a promotion", "獲得升遷"], ["a sales promotion", "促銷活動"]],
        n: "職場義是升遷,行銷義是促銷;看到 promotion 一定要先看情境再判斷。" },
      { w: "transfer", p: "v./n.", zh: "調職;轉帳;轉乘", d: "to move to another place, job or account",
        ph: [["transfer to the Osaka branch", "調至大阪分公司"], ["a wire transfer", "電匯"]],
        n: "動詞重音在後(transFER),名詞在前(TRANSfer)。" },
      { w: "resign", p: "v.", zh: "辭職", d: "to officially leave a job",
        syn: ["quit", "step down"], ant: ["stay on"],
        ph: [["resign from the post", "辭去職務"], ["hand in your resignation", "遞辭呈"]],
        r: "re-(back) + sign(簽署) → 把職務簽回去" },
      { w: "retire", p: "v.", zh: "退休", d: "to stop working because of age",
        ph: [["retire at 65", "六十五歲退休"], ["a retirement party", "退休歡送會"]] },
      { w: "dismiss", p: "v.", zh: "解僱;駁回", d: "to remove someone from a job",
        syn: ["fire", "terminate", "let go"], ant: ["hire", "employ"],
        ph: [["be dismissed for misconduct", "因行為不當被解僱"]],
        r: "dis-(離開) + miss(送) → 送走" },
      { w: "layoff", p: "n.", zh: "裁員", d: "the ending of jobs because there is not enough work",
        syn: ["redundancy", "downsizing"],
        ph: [["announce layoffs", "宣布裁員"], ["be laid off", "被裁員"]],
        n: "layoff 是「因公司因素」裁員,dismissal 多半是「因個人表現/行為」解僱。" },
      { w: "severance", p: "n.", zh: "資遣費", d: "money paid to an employee who is dismissed",
        ph: [["a severance package", "資遣方案"]] },
      { w: "turnover", p: "n.", zh: "人員流動率;營業額", d: "the rate at which staff leave; total sales",
        ph: [["a high staff turnover", "員工流動率高"], ["annual turnover", "年營業額"]],
        n: "兩義都是多益高頻:人事情境是流動率,財務情境是營業額。" },
      { w: "morale", p: "n.", zh: "士氣", d: "the level of confidence and enthusiasm in a group",
        ph: [["boost morale", "提振士氣"], ["low morale", "士氣低落"]],
        n: "morale(士氣,重音在後)vs. moral(道德的,重音在前),拼字與發音都易混。" },
      { w: "employer", p: "n.", zh: "雇主", d: "a person or company that pays people to work",
        ant: ["employee"] },
      { w: "employee", p: "n.", zh: "員工", d: "a person who is paid to work for a company",
        syn: ["worker", "staff member"], ant: ["employer"],
        n: "重音在最後:em-ploy-EE;employer 重音在中間,聽力靠重音分辨。" },
      { w: "staff", p: "n.", zh: "全體員工", d: "all the people who work in an organization",
        n: "集合名詞,通常不加 s:The staff are helpful.(✗ staffs)Part 5 常考。" },
    ]},
];
