// ============================================================
//  📕 多益 13 大主題字彙庫(4/4):房屋地產・餐廳飲食・購物
//  另含 TOEIC_AFFIXES:字根字首字尾總表(圖解用)
// ============================================================

TOEIC_VOCAB.push(
  { id: "house", no: 11, name: "房屋與地產", en: "Housing & Property", icon: "🏠",
    map: { center: "房屋地產", branches: [
      { label: "租賃", ws: ["lease", "tenant", "landlord", "deposit", "utilities"] },
      { label: "買賣", ws: ["mortgage", "appraisal", "realtor", "closing", "title"] },
      { label: "空間", ws: ["square footage", "furnished", "vacant", "layout", "storage"] },
      { label: "裝修", ws: ["renovate", "remodel", "contractor", "plumbing", "insulation"] },
      { label: "遷移", ws: ["relocate", "premises", "occupancy", "sublet", "eviction"] },
    ]},
    list: [
      { w: "lease", p: "n./v.", zh: "租約;出租", d: "a legal agreement to rent property",
        syn: ["rental agreement"],
        ph: [["sign a lease", "簽租約"], ["the lease expires", "租約到期"], ["a five-year lease", "五年租約"]] },
      { w: "tenant", p: "n.", zh: "承租人;房客", d: "a person who rents a property",
        ant: ["landlord"],
        ph: [["a long-term tenant", "長期房客"], ["prospective tenants", "潛在租客"]],
        r: "ten(持有) + -ant(人) → 持有使用權的人" },
      { w: "landlord", p: "n.", zh: "房東", d: "a person who owns a property and rents it out",
        ant: ["tenant"],
        ph: [["notify the landlord", "通知房東"]] },
      { w: "utilities", p: "n.", zh: "水電瓦斯等費用", d: "services such as water, gas and electricity",
        ph: [["utilities included", "含水電"], ["pay the utilities", "支付水電費"]],
        n: "租屋廣告的關鍵字:utilities included/excluded 決定租金實際負擔。" },
      { w: "appraisal", p: "n.", zh: "不動產估價", d: "an official judgment of a property's value",
        syn: ["valuation"],
        ph: [["a property appraisal", "不動產估價"]] },
      { w: "realtor", p: "n.", zh: "房仲", d: "a person who sells property for others",
        syn: ["real estate agent"],
        ph: [["contact a realtor", "聯絡房仲"]] },
      { w: "closing", p: "n.", zh: "成交(過戶)", d: "the final stage of a property sale",
        ph: [["closing costs", "過戶費用"], ["the closing date", "成交日"]] },
      { w: "title", p: "n.", zh: "所有權(狀)", d: "the legal right to own property",
        ph: [["transfer the title", "移轉所有權"], ["a title search", "產權查核"]] },
      { w: "square footage", p: "n.", zh: "坪數;面積", d: "the size of a space measured in square feet",
        ph: [["the total square footage", "總面積"]] },
      { w: "furnished", p: "adj.", zh: "附家具的", d: "supplied with furniture",
        ant: ["unfurnished"],
        ph: [["a fully furnished apartment", "全家具公寓"]] },
      { w: "vacant", p: "adj.", zh: "空置的", d: "empty and available",
        syn: ["unoccupied", "available"], ant: ["occupied"],
        ph: [["a vacant unit", "空屋"], ["vacant since March", "自三月起空置"]] },
      { w: "layout", p: "n.", zh: "格局;配置", d: "the way rooms or objects are arranged",
        ph: [["an open layout", "開放式格局"], ["the office layout", "辦公室配置"]] },
      { w: "storage", p: "n.", zh: "儲藏(空間)", d: "space for keeping things",
        ph: [["ample storage", "充足收納空間"], ["put in storage", "存放起來"]] },
      { w: "renovate", p: "v.", zh: "翻新", d: "to repair and improve a building",
        syn: ["refurbish", "remodel"],
        ph: [["newly renovated", "全新翻修"], ["renovation work", "翻修工程"]],
        r: "re-(再) + nov(新) + -ate → 使再變新" },
      { w: "remodel", p: "v.", zh: "改建", d: "to change the structure or appearance of a building",
        ph: [["remodel the kitchen", "改建廚房"]] },
      { w: "contractor", p: "n.", zh: "承包商", d: "a person or company hired to do building work",
        ph: [["hire a contractor", "聘請承包商"], ["a general contractor", "統包商"]] },
      { w: "plumbing", p: "n.", zh: "水管配管", d: "the system of pipes in a building",
        ph: [["a plumbing problem", "水管問題"], ["call a plumber", "叫水電工"]],
        n: "b 不發音:/ˈplʌmɪŋ/。" },
      { w: "insulation", p: "n.", zh: "隔熱;絕緣", d: "material used to keep heat or noise out",
        ph: [["poor insulation", "隔熱不佳"], ["sound insulation", "隔音"]] },
      { w: "relocate", p: "v.", zh: "搬遷", d: "to move to a new place",
        syn: ["move", "transfer"],
        ph: [["relocate the office", "遷移辦公室"], ["a relocation allowance", "搬遷津貼"]],
        r: "re-(再) + locate(定位) → 換個位置" },
      { w: "premises", p: "n.", zh: "營業場所", d: "the buildings and land used by a business",
        ph: [["inspect the premises", "查看場所"], ["off the premises", "在場所外"]] },
      { w: "occupancy", p: "n.", zh: "使用;入住", d: "the act of living or working in a place",
        ph: [["ready for occupancy", "可立即入住"], ["occupancy permit", "使用執照"]] },
      { w: "sublet", p: "v.", zh: "轉租", d: "to rent a property you are renting to someone else",
        ph: [["sublet the apartment", "轉租公寓"], ["subletting is prohibited", "禁止轉租"]],
        r: "sub-(在下) + let(出租) → 二房東式出租" },
      { w: "eviction", p: "n.", zh: "驅逐;強制搬遷", d: "the act of forcing a tenant to leave",
        ph: [["an eviction notice", "搬遷通知"]] },
      { w: "amenities", p: "n.", zh: "生活機能設施", d: "useful features of a building or area",
        ph: [["on-site amenities", "館內設施"], ["nearby amenities", "周邊機能"]] },
      { w: "commercial property", p: "n.", zh: "商用不動產", d: "buildings used for business",
        ant: ["residential property"],
        ph: [["invest in commercial property", "投資商用不動產"]] },
      { w: "residential", p: "adj.", zh: "住宅的", d: "consisting of homes rather than businesses",
        ph: [["a residential area", "住宅區"], ["residential units", "住宅戶數"]] },
      { w: "zoning", p: "n.", zh: "土地分區使用", d: "rules about how land may be used",
        ph: [["zoning regulations", "土地使用分區法規"]] },
      { w: "property manager", p: "n.", zh: "物業經理", d: "a person who runs a building for its owner",
        ph: [["contact the property manager", "聯絡物業經理"]] },
      { w: "maintenance fee", p: "n.", zh: "管理費", d: "regular payment for building upkeep",
        ph: [["a monthly maintenance fee", "月管理費"]] },
      { w: "inspection", p: "n.", zh: "查驗;驗屋", d: "an official examination of a property",
        ph: [["a home inspection", "驗屋"], ["pass inspection", "通過查驗"]] },
      { w: "spacious", p: "adj.", zh: "寬敞的", d: "large and with plenty of room",
        syn: ["roomy"], ant: ["cramped"],
        ph: [["a spacious lobby", "寬敞的大廳"]] },
      { w: "cramped", p: "adj.", zh: "狹窄擁擠的", d: "too small and uncomfortable",
        ant: ["spacious"] },
      { w: "adjacent", p: "adj.", zh: "鄰接的", d: "next to something",
        syn: ["neighboring", "adjoining"],
        ph: [["adjacent to the station", "緊鄰車站"]],
        n: "介係詞用 to:adjacent to(不是 adjacent from)。",
        r: "ad-(靠近) + jac(躺) → 躺在旁邊" },
      { w: "accessible", p: "adj.", zh: "可到達的;無障礙的", d: "easy to reach or enter",
        ant: ["inaccessible"],
        ph: [["wheelchair accessible", "無障礙可通行"], ["easily accessible by bus", "搭公車很方便"]] },
      { w: "furnishings", p: "n.", zh: "家具陳設", d: "furniture and decorations in a room",
        ph: [["office furnishings", "辦公家具"]] },
      { w: "square meter", p: "n.", zh: "平方公尺", d: "a unit of area",
        ph: [["120 square meters", "一百二十平方公尺"]] },
      { w: "down payment", p: "n.", zh: "頭期款", d: "the first payment when buying property",
        ph: [["a 20% down payment", "兩成頭期款"]] },
      { w: "leasehold", p: "n.", zh: "租賃權", d: "the right to use property for a fixed period",
        ant: ["freehold"] },
      { w: "utility bill", p: "n.", zh: "水電帳單", d: "a bill for gas, water or electricity",
        ph: [["settle the utility bills", "繳清水電帳單"]] },
      { w: "move-in date", p: "n.", zh: "遷入日", d: "the day a tenant starts living in a property",
        ph: [["confirm the move-in date", "確認遷入日"]] },
    ]},

  { id: "dining", no: 12, name: "餐廳與飲食", en: "Dining Out", icon: "🍽️",
    map: { center: "餐廳飲食", branches: [
      { label: "訂位", ws: ["reserve", "party", "deposit", "walk-in", "seating"] },
      { label: "點餐", ws: ["appetizer", "entrée", "beverage", "special", "order"] },
      { label: "服務", ws: ["server", "chef", "cater", "refill", "tip"] },
      { label: "結帳", ws: ["bill", "gratuity", "split", "receipt", "voucher"] },
      { label: "問題", ws: ["complaint", "undercooked", "allergy", "substitute", "comp"] },
    ]},
    list: [
      { w: "reserve", p: "v.", zh: "預訂", d: "to arrange for a table to be kept for you",
        syn: ["book"],
        ph: [["reserve a table for four", "訂四人桌"], ["reserved seating", "保留席"]] },
      { w: "party", p: "n.", zh: "一行人;宴會", d: "a group of people eating together",
        ph: [["a party of six", "六位一行"], ["the whole party", "全體同行者"]],
        n: "餐廳情境的 party 是「一行人」,不是「派對」——聽力常誤解。" },
      { w: "walk-in", p: "n./adj.", zh: "未預約(客)", d: "a customer without a reservation",
        ant: ["reservation"],
        ph: [["we accept walk-ins", "接受未預約客人"]] },
      { w: "seating", p: "n.", zh: "座位安排", d: "the arrangement of seats",
        ph: [["outdoor seating", "戶外座位"], ["seating capacity", "座位數"]] },
      { w: "appetizer", p: "n.", zh: "開胃菜", d: "a small dish served before the main course",
        syn: ["starter"],
        ph: [["order an appetizer", "點開胃菜"]] },
      { w: "entrée", p: "n.", zh: "主菜", d: "the main dish of a meal (American)",
        syn: ["main course"],
        n: "美式的 entrée 是「主菜」,法式反而是「前菜」,多益採美式用法。" },
      { w: "beverage", p: "n.", zh: "飲料", d: "any drink",
        syn: ["drink"],
        ph: [["complimentary beverages", "免費飲料"], ["a beverage menu", "飲料單"]] },
      { w: "special", p: "n.", zh: "特餐;今日推薦", d: "a dish offered for a limited time",
        ph: [["today's special", "今日特餐"], ["the lunch special", "午間套餐"]] },
      { w: "server", p: "n.", zh: "服務生", d: "a person who brings food in a restaurant",
        syn: ["waiter", "waitress"],
        ph: [["ask your server", "詢問服務生"]] },
      { w: "chef", p: "n.", zh: "主廚", d: "a professional cook",
        ph: [["the head chef", "主廚"], ["chef's recommendation", "主廚推薦"]] },
      { w: "cater", p: "v.", zh: "外燴;迎合", d: "to provide food for an event; to satisfy a need",
        ph: [["cater an event", "承辦餐飲"], ["cater to customers", "迎合顧客需求"], ["a catering company", "外燴公司"]],
        n: "cater for(英)/ cater to(美)= 迎合;cater an event = 承辦餐飲。" },
      { w: "refill", p: "n./v.", zh: "續杯;再裝滿", d: "another serving of the same drink",
        ph: [["free refills", "免費續杯"], ["would you like a refill?", "要續杯嗎?"]] },
      { w: "tip", p: "n./v.", zh: "小費", d: "extra money given for good service",
        syn: ["gratuity"],
        ph: [["leave a tip", "留小費"], ["a 15% tip", "一成五小費"]] },
      { w: "gratuity", p: "n.", zh: "服務費;小費", d: "money added for service, often automatically",
        ph: [["an 18% gratuity is included", "已含一成八服務費"]],
        n: "gratuity 較正式,常出現在帳單上;tip 是口語。" },
      { w: "bill", p: "n.", zh: "帳單", d: "a list showing what you must pay",
        syn: ["check (US)"],
        ph: [["ask for the bill", "請結帳"], ["split the bill", "分開付帳"]],
        n: "英式用 bill,美式餐廳多用 check;兩種在多益聽力都出現。" },
      { w: "split", p: "v.", zh: "分開(付帳)", d: "to divide something between people",
        ph: [["split the check", "分開結帳"], ["split evenly", "平均分攤"]] },
      { w: "complaint", p: "n.", zh: "抱怨;客訴", d: "a statement that you are unhappy about something",
        ph: [["file a complaint", "提出客訴"], ["address a complaint", "處理客訴"]] },
      { w: "undercooked", p: "adj.", zh: "沒煮熟的", d: "not cooked enough",
        ant: ["overcooked"],
        ph: [["the steak is undercooked", "牛排不夠熟"]] },
      { w: "substitute", p: "n./v.", zh: "替換;代用品", d: "to use one thing instead of another",
        ph: [["substitute salad for fries", "把薯條換成沙拉"], ["a substitute ingredient", "替代食材"]],
        n: "substitute A for B = 用 A 取代 B,介係詞方向是考點。",
        r: "sub-(在下;替代) + stitut(放置) → 放上去頂替" },
      { w: "comp", p: "v.", zh: "免費招待", d: "to give something free as an apology or courtesy",
        ph: [["comp the dessert", "甜點免費招待"]] },
      { w: "cuisine", p: "n.", zh: "料理;菜系", d: "a style of cooking",
        ph: [["Italian cuisine", "義式料理"], ["local cuisine", "在地料理"]],
        n: "唸 /kwɪˈziːn/,重音在後,是聽力難字。" },
      { w: "menu", p: "n.", zh: "菜單", d: "a list of dishes available",
        ph: [["a set menu", "套餐菜單"], ["a seasonal menu", "季節菜單"]] },
      { w: "vegetarian", p: "n./adj.", zh: "素食(者)", d: "a person who does not eat meat",
        ph: [["vegetarian options", "素食選擇"]] },
      { w: "dietary", p: "adj.", zh: "飲食的", d: "relating to the food a person eats",
        ph: [["dietary restrictions", "飲食限制"], ["dietary requirements", "飲食需求"]] },
      { w: "condiment", p: "n.", zh: "調味料", d: "a sauce or seasoning added to food",
        ph: [["condiments are on the table", "調味料在桌上"]] },
      { w: "ingredient", p: "n.", zh: "食材;成分", d: "one of the foods used to make a dish",
        ph: [["fresh ingredients", "新鮮食材"], ["a key ingredient", "關鍵材料"]] },
      { w: "portion", p: "n.", zh: "份量", d: "the amount of food served to one person",
        syn: ["serving", "helping"],
        ph: [["generous portions", "份量十足"], ["portion size", "份量大小"]] },
      { w: "banquet", p: "n.", zh: "宴會", d: "a formal meal for many people",
        ph: [["a banquet hall", "宴會廳"], ["host a banquet", "舉辦宴會"]] },
      { w: "reception", p: "n.", zh: "招待會", d: "a formal party to welcome people",
        ph: [["a welcome reception", "歡迎酒會"]] },
      { w: "buffet", p: "n.", zh: "自助餐", d: "a meal where guests serve themselves",
        ph: [["a buffet breakfast", "自助早餐"]],
        n: "唸 /bəˈfeɪ/,t 不發音。" },
      { w: "takeout", p: "n.", zh: "外帶", d: "food bought to eat somewhere else",
        syn: ["takeaway (UK)"],
        ph: [["order takeout", "叫外帶"], ["for here or to go?", "內用還是外帶?"]] },
      { w: "beverage service", p: "n.", zh: "飲品服務", d: "the provision of drinks",
        ph: [["in-flight beverage service", "機上飲料服務"]] },
      { w: "reserve a private room", p: "v.", zh: "訂包廂", d: "to book a separate dining room",
        ph: [["reserve a private dining room", "預訂包廂"]] },
      { w: "seasonal", p: "adj.", zh: "當季的", d: "available only at a certain time of year",
        ph: [["seasonal produce", "當季農產"]] },
      { w: "delicacy", p: "n.", zh: "珍饈;佳餚", d: "a rare or expensive food",
        ph: [["a local delicacy", "在地名產"]] },
      { w: "hospitality", p: "n.", zh: "款待;餐旅業", d: "friendly treatment of guests; the hotel and food industry",
        ph: [["the hospitality industry", "餐旅業"], ["thank you for your hospitality", "感謝款待"]],
        r: "hospit(客人) + -ality → 待客之道" },
      { w: "establishment", p: "n.", zh: "店家;機構", d: "a business such as a restaurant or hotel",
        ph: [["a dining establishment", "餐飲業者"]] },
      { w: "patron", p: "n.", zh: "常客;贊助者", d: "a regular customer of a restaurant or shop",
        syn: ["customer", "regular"],
        ph: [["valued patrons", "貴賓顧客"]] },
      { w: "beverage tab", p: "n.", zh: "酒水帳", d: "the record of drinks to be paid for",
        ph: [["open a tab", "先記帳最後結清"]] },
      { w: "courteous", p: "adj.", zh: "有禮的", d: "polite and respectful",
        syn: ["polite", "attentive"], ant: ["rude"],
        ph: [["courteous service", "有禮的服務"]] },
    ]},

  { id: "shop", no: 13, name: "購物", en: "Shopping", icon: "🛍️",
    map: { center: "購物", branches: [
      { label: "促銷", ws: ["clearance", "markdown", "coupon", "loyalty", "rebate"] },
      { label: "結帳", ws: ["cashier", "checkout", "receipt", "installment", "surcharge"] },
      { label: "退換", ws: ["refund", "exchange", "return policy", "defective", "warranty"] },
      { label: "商品", ws: ["merchandise", "apparel", "in stock", "assortment", "brand"] },
      { label: "通路", ws: ["retail", "outlet", "e-commerce", "delivery", "membership"] },
    ]},
    list: [
      { w: "retail", p: "n./adj.", zh: "零售", d: "the selling of goods to the public",
        ant: ["wholesale"],
        ph: [["a retail outlet", "零售據點"], ["the retail price", "零售價"]] },
      { w: "merchandise", p: "n.", zh: "商品", d: "goods that are bought and sold",
        syn: ["goods", "products"],
        ph: [["display merchandise", "陳列商品"], ["defective merchandise", "瑕疵商品"]],
        n: "不可數名詞,不加 s;動詞用法是「行銷推廣」。" },
      { w: "apparel", p: "n.", zh: "服飾", d: "clothing",
        syn: ["clothing", "garments"],
        ph: [["the apparel department", "服飾部"]] },
      { w: "assortment", p: "n.", zh: "各式各樣;品項組合", d: "a mixture of different types of the same thing",
        syn: ["selection", "variety"],
        ph: [["a wide assortment", "品項豐富"]] },
      { w: "in stock", p: "adj.", zh: "有現貨", d: "available to buy immediately",
        ant: ["out of stock"],
        ph: [["is it in stock?", "有現貨嗎?"], ["out of stock until Friday", "週五前缺貨"]] },
      { w: "clearance", p: "n.", zh: "出清", d: "a sale to get rid of old stock",
        ph: [["a clearance sale", "出清特賣"], ["on clearance", "出清中"]] },
      { w: "markdown", p: "n.", zh: "降價", d: "a reduction in price",
        syn: ["price cut", "discount"], ant: ["markup"],
        ph: [["further markdowns", "再降價"]],
        n: "markup 是「加價」(成本到售價的加成),markdown 是「降價」,常一起考。" },
      { w: "coupon", p: "n.", zh: "優惠券", d: "a printed piece of paper giving a discount",
        syn: ["voucher"],
        ph: [["redeem a coupon", "使用優惠券"], ["a coupon code", "折扣碼"]] },
      { w: "rebate", p: "n.", zh: "現金回饋;折扣退款", d: "money paid back after a purchase",
        ph: [["a mail-in rebate", "郵寄退款"], ["offer a rebate", "提供回饋"]],
        r: "re-(回) + bate(減少) → 事後退回一部分" },
      { w: "loyalty program", p: "n.", zh: "會員忠誠方案", d: "a scheme rewarding regular customers",
        ph: [["join the loyalty program", "加入會員方案"], ["earn points", "累積點數"]] },
      { w: "membership", p: "n.", zh: "會員資格", d: "the state of belonging to a group",
        ph: [["a membership fee", "會員費"], ["renew your membership", "續辦會員"]] },
      { w: "cashier", p: "n.", zh: "收銀員", d: "a person who takes payment in a shop",
        ph: [["pay the cashier", "向收銀員付款"]] },
      { w: "checkout", p: "n.", zh: "結帳櫃檯", d: "the place where you pay in a shop",
        ph: [["the express checkout", "快速結帳台"], ["self-checkout", "自助結帳"]] },
      { w: "refund", p: "n./v.", zh: "退款", d: "money given back for returned goods",
        ph: [["request a refund", "要求退款"], ["a full refund", "全額退款"], ["non-refundable", "不可退款"]] },
      { w: "exchange", p: "n./v.", zh: "換貨;交換", d: "to give something back and get another",
        ph: [["exchange it for a larger size", "換大一號"], ["in exchange for", "以…交換"]] },
      { w: "return policy", p: "n.", zh: "退貨政策", d: "the rules about returning goods",
        ph: [["a 30-day return policy", "三十天退貨政策"]] },
      { w: "proof of purchase", p: "n.", zh: "購買證明", d: "something showing you bought an item",
        ph: [["present proof of purchase", "出示購買證明"]] },
      { w: "sales associate", p: "n.", zh: "門市人員", d: "a shop employee who helps customers",
        ph: [["ask a sales associate", "詢問門市人員"]] },
      { w: "restocking fee", p: "n.", zh: "退貨處理費", d: "a charge for returning an opened product",
        ph: [["a 15% restocking fee applies", "酌收一成五退貨處理費"]] },
      { w: "installment plan", p: "n.", zh: "分期方案", d: "an arrangement to pay over time",
        ph: [["an interest-free installment plan", "免息分期"]] },
      { w: "display", p: "n./v.", zh: "陳列;展示", d: "an arrangement of goods for customers to see",
        ph: [["a window display", "櫥窗陳列"], ["on display", "展示中"]] },
      { w: "outlet", p: "n.", zh: "暢貨中心;通路", d: "a shop selling goods at reduced prices",
        ph: [["an outlet mall", "暢貨中心"], ["a retail outlet", "銷售據點"]] },
      { w: "e-commerce", p: "n.", zh: "電子商務", d: "buying and selling online",
        ph: [["an e-commerce platform", "電商平台"]] },
      { w: "browse", p: "v.", zh: "隨意看看;瀏覽", d: "to look at goods without intending to buy",
        ph: [["just browsing, thanks", "只是看看,謝謝"], ["browse the catalog", "瀏覽型錄"]] },
      { w: "aisle", p: "n.", zh: "商品走道", d: "a passage between shelves in a shop",
        ph: [["in aisle 7", "在七號走道"]] },
      { w: "stock up", p: "v.", zh: "囤貨", d: "to buy a large amount of something",
        ph: [["stock up on supplies", "囤積用品"]] },
      { w: "bargain", p: "n./v.", zh: "便宜貨;議價", d: "something bought cheaply; to negotiate a price",
        syn: ["deal", "steal"],
        ph: [["a real bargain", "超划算"], ["bargain hunting", "撿便宜"]] },
      { w: "promotion", p: "n.", zh: "促銷", d: "activities to increase sales",
        ph: [["a promotional offer", "促銷優惠"], ["run a promotion", "舉辦促銷"]] },
      { w: "advertisement", p: "n.", zh: "廣告", d: "a public notice promoting a product",
        syn: ["ad", "commercial"],
        ph: [["place an advertisement", "刊登廣告"], ["as advertised", "如廣告所述"]] },
      { w: "brand", p: "n.", zh: "品牌", d: "a product name made by a particular company",
        ph: [["a leading brand", "領導品牌"], ["brand loyalty", "品牌忠誠度"]] },
      { w: "customer service", p: "n.", zh: "客服", d: "help given to people who buy products",
        ph: [["contact customer service", "聯絡客服"]] },
      { w: "complimentary gift", p: "n.", zh: "贈品", d: "a free present given with a purchase",
        ph: [["receive a complimentary gift", "獲贈禮品"]] },
      { w: "fitting room", p: "n.", zh: "試衣間", d: "a room where customers try on clothes",
        ph: [["a limit of six items in the fitting room", "試衣間一次限六件"]] },
      { w: "expiration date", p: "n.", zh: "有效期限", d: "the date after which something should not be used",
        ph: [["check the expiration date", "檢查有效期限"]] },
      { w: "gift certificate", p: "n.", zh: "禮券", d: "a card exchangeable for goods",
        syn: ["gift card"],
        ph: [["a $50 gift certificate", "五十元禮券"]] },
      { w: "shipping fee", p: "n.", zh: "運費", d: "the cost of sending goods to a customer",
        ph: [["free shipping on orders over $50", "滿五十元免運"]] },
      { w: "in-store", p: "adj.", zh: "店內的", d: "happening inside a shop",
        ph: [["in-store pickup", "門市取貨"], ["in-store credit", "店內購物金"]] },
      { w: "backorder", p: "n.", zh: "缺貨待補", d: "an order waiting for stock to arrive",
        ph: [["the item is on backorder", "商品缺貨待補"]] },
      { w: "markup", p: "n.", zh: "加價;利潤加成", d: "the amount added to the cost to set the price",
        ant: ["markdown"] },
      { w: "purchase history", p: "n.", zh: "購買紀錄", d: "a record of what a customer has bought",
        ph: [["check your purchase history", "查看購買紀錄"]] },
    ]},
);

// ============================================================
//  🧬 字根字首字尾總表(圖解用)
// ============================================================
const TOEIC_AFFIXES = [
  { type: "字首", color: "#5356E4", items: [
    { a: "re-", m: "再;回", ex: ["renew 續約", "reimburse 報銷", "restock 補貨", "relocate 搬遷"] },
    { a: "pre-", m: "事前", ex: ["prerequisite 先修條件", "precaution 預防措施", "prescription 處方"] },
    { a: "pro-", m: "向前;為了", ex: ["procurement 採購", "promotion 升遷", "prototype 原型"] },
    { a: "sub-", m: "在下;次要", ex: ["subsidiary 子公司", "subordinate 部屬", "sublet 轉租"] },
    { a: "super- / sur-", m: "在上;超過", ex: ["supervisor 主管", "surplus 盈餘", "surcharge 附加費"] },
    { a: "ex- / e-", m: "向外", ex: ["expenditure 支出", "expedite 加急", "evacuate 疏散"] },
    { a: "in- / im-", m: "進入;不", ex: ["install 安裝", "implement 導入", "invalid 無效的"] },
    { a: "trans-", m: "跨越", ex: ["transaction 交易", "transfer 調職", "transit 運輸"] },
    { a: "com- / con-", m: "一起", ex: ["compensation 薪酬", "convene 召開", "conference 會議"] },
    { a: "de-", m: "向下;去除", ex: ["deduction 扣除", "deficit 赤字", "defective 瑕疵的"] },
    { a: "inter-", m: "之間", ex: ["interface 介面", "intermission 中場休息", "interdepartmental 跨部門"] },
    { a: "mal-", m: "壞的", ex: ["malfunction 故障"] },
  ]},
  { type: "字根", color: "#FF8A3C", items: [
    { a: "spect / spec", m: "看", ex: ["inspect 檢驗", "specification 規格", "prospective 潛在的"] },
    { a: "duc / duct", m: "引導", ex: ["deduction 扣除", "conductor 導體", "productivity 生產力"] },
    { a: "fer", m: "帶來", ex: ["conference 會議", "transfer 轉移", "referral 轉診"] },
    { a: "scrib / script", m: "寫", ex: ["prescription 處方", "subscription 訂閱", "describe 描述"] },
    { a: "ven / vent", m: "來", ex: ["convene 召開", "venue 場地", "inventory 庫存"] },
    { a: "cred / fid", m: "相信", ex: ["credential 資歷", "confidential 機密的", "credit 信用"] },
    { a: "ced / cess", m: "走", ex: ["procedure 程序", "process 流程", "access 存取"] },
    { a: "pos / pon", m: "放置", ex: ["postpone 延期", "deposit 訂金", "component 元件"] },
    { a: "vac", m: "空的", ex: ["vacancy 職缺;空房", "vacant 空置的", "evacuate 疏散"] },
    { a: "term", m: "界線;結束", ex: ["terminate 終止", "terminal 航廈", "term 條件"] },
    { a: "loc", m: "位置", ex: ["allocate 撥款", "relocate 搬遷", "local 當地的"] },
    { a: "quir / quisit", m: "尋求", ex: ["acquire 收購", "requisition 請購", "inquiry 詢問"] },
  ]},
  { type: "字尾", color: "#12A5D8", items: [
    { a: "-er / -or", m: "動作的執行者", ex: ["employer 雇主", "supervisor 主管", "vendor 供應商"] },
    { a: "-ee", m: "動作的接受者", ex: ["employee 員工", "trainee 受訓者", "attendee 與會者"] },
    { a: "-ment", m: "名詞:結果或狀態", ex: ["shipment 貨運", "equipment 設備", "agreement 協議"] },
    { a: "-tion / -sion", m: "名詞:動作或過程", ex: ["expansion 擴張", "acquisition 收購", "compensation 薪酬"] },
    { a: "-ity / -ty", m: "名詞:性質", ex: ["capacity 容量", "liability 負債", "feasibility 可行性"] },
    { a: "-ance / -ence", m: "名詞:狀態", ex: ["maintenance 維護", "compliance 合規", "attendance 出席"] },
    { a: "-able / -ible", m: "形容詞:可以…的", ex: ["negotiable 可議的", "compatible 相容的", "durable 耐用的"] },
    { a: "-ive", m: "形容詞:有…性質的", ex: ["executive 執行的", "defective 瑕疵的", "protective 防護的"] },
    { a: "-ize / -ify", m: "動詞:使…化", ex: ["prioritize 排優先", "standardize 標準化", "verify 驗證"] },
    { a: "-ous", m: "形容詞:充滿…的", ex: ["spacious 寬敞的", "hazardous 危險的", "courteous 有禮的"] },
  ]},
];
