// ============================================================
//  📕 多益 13 大主題字彙庫(3/4):製造業・旅遊・娛樂藝文・健康保健
// ============================================================

TOEIC_VOCAB.push(
  { id: "manu", no: 7, name: "製造業", en: "Manufacturing", icon: "🏭",
    map: { center: "製造業", branches: [
      { label: "產線", ws: ["assembly", "conveyor", "shift", "output", "capacity"] },
      { label: "品質", ws: ["inspect", "defect", "tolerance", "certify", "recall"] },
      { label: "廠務", ws: ["plant", "facility", "machinery", "overhaul", "shutdown"] },
      { label: "安全", ws: ["hazard", "protective", "compliance", "evacuate", "precaution"] },
      { label: "效率", ws: ["streamline", "productivity", "waste", "yield", "throughput"] },
    ]},
    list: [
      { w: "assembly", p: "n.", zh: "組裝;集會", d: "the process of putting parts together",
        ph: [["an assembly line", "生產線"], ["assembly instructions", "組裝說明"]],
        r: "as-(朝向) + sembl(一起) → 把零件聚在一起" },
      { w: "conveyor", p: "n.", zh: "輸送帶", d: "a moving belt that carries objects",
        ph: [["a conveyor belt", "輸送帶"]] },
      { w: "shift", p: "n./v.", zh: "輪班;轉換", d: "a period of work; to move or change",
        ph: [["the night shift", "夜班"], ["work in shifts", "輪班工作"], ["a shift in demand", "需求轉變"]] },
      { w: "output", p: "n.", zh: "產量;輸出", d: "the amount produced",
        syn: ["production", "yield"], ant: ["input"],
        ph: [["increase output", "提高產量"], ["daily output", "日產量"]] },
      { w: "throughput", p: "n.", zh: "產能吞吐量", d: "the amount of material processed in a period",
        ph: [["improve throughput", "提升吞吐量"]] },
      { w: "productivity", p: "n.", zh: "生產力", d: "the rate at which goods are produced",
        ph: [["boost productivity", "提升生產力"], ["a productivity gain", "生產力提升"]] },
      { w: "streamline", p: "v.", zh: "簡化流程", d: "to make a process simpler and more efficient",
        syn: ["simplify", "optimize"],
        ph: [["streamline operations", "精簡營運流程"]],
        n: "字面是「讓水流順暢的線條」,引申為去掉多餘步驟。" },
      { w: "inspect", p: "v.", zh: "檢查", d: "to look at something carefully to check quality",
        syn: ["examine", "check"],
        ph: [["inspect the goods", "驗貨"], ["a quality inspection", "品質檢驗"]],
        r: "in-(進入) + spect(看) → 看進去" },
      { w: "inspector", p: "n.", zh: "檢驗員", d: "a person whose job is to check quality or safety",
        ph: [["a safety inspector", "安全檢查員"]] },
      { w: "defect", p: "n.", zh: "瑕疵", d: "a fault that makes something imperfect",
        syn: ["flaw", "fault"],
        ph: [["a manufacturing defect", "製造瑕疵"], ["a defect rate", "不良率"]],
        r: "de-(缺) + fect(做) → 沒做好的地方" },
      { w: "tolerance", p: "n.", zh: "公差;容忍度", d: "the allowed amount of variation in size",
        ph: [["within tolerance", "在公差範圍內"], ["zero tolerance", "零容忍"]] },
      { w: "certify", p: "v.", zh: "認證", d: "to state officially that something meets a standard",
        ph: [["ISO certified", "通過 ISO 認證"], ["a certificate of origin", "產地證明"]],
        r: "cert(確定) + -ify → 使確定無疑" },
      { w: "recall", p: "v./n.", zh: "召回;回想", d: "to ask customers to return a faulty product",
        ph: [["issue a product recall", "發布產品召回"], ["recall defective units", "召回瑕疵品"]],
        n: "產品情境是「召回」,一般語境是「回想」;多益出題偏產品召回。" },
      { w: "plant", p: "n.", zh: "工廠;廠房", d: "a factory or industrial building",
        syn: ["factory", "mill"],
        ph: [["a manufacturing plant", "製造廠"], ["plant manager", "廠長"]] },
      { w: "machinery", p: "n.", zh: "機械(總稱)", d: "machines considered as a group",
        n: "不可數名詞,不加 s;要數就說 a piece of machinery。" },
      { w: "overhaul", p: "n./v.", zh: "大修;全面檢修", d: "a thorough repair or examination",
        syn: ["revamp", "refurbish"],
        ph: [["overhaul the equipment", "全面檢修設備"]] },
      { w: "shutdown", p: "n.", zh: "停工;關機", d: "the closing of a factory or system",
        ph: [["a scheduled shutdown", "預定停工"], ["an emergency shutdown", "緊急停機"]] },
      { w: "hazard", p: "n.", zh: "危害;危險", d: "something that may cause harm",
        syn: ["risk", "danger"],
        ph: [["a fire hazard", "火災隱患"], ["hazardous materials", "危險物品"]] },
      { w: "protective", p: "adj.", zh: "防護的", d: "designed to keep someone safe",
        ph: [["protective gear", "防護裝備"], ["protective eyewear", "護目鏡"]] },
      { w: "precaution", p: "n.", zh: "預防措施", d: "an action taken to prevent harm",
        ph: [["take precautions", "採取預防措施"], ["as a precaution", "以防萬一"]],
        r: "pre-(事前) + caution(小心) → 事前的小心" },
      { w: "evacuate", p: "v.", zh: "疏散", d: "to move people away from a dangerous place",
        ph: [["evacuate the building", "疏散建築物"], ["an evacuation drill", "疏散演習"]],
        r: "e-(向外) + vacu(空的) → 使變空" },
      { w: "compliance", p: "n.", zh: "合規;遵守", d: "the act of obeying rules or standards",
        ant: ["violation"],
        ph: [["in compliance with safety rules", "符合安全規定"], ["a compliance officer", "法遵人員"]] },
      { w: "regulation", p: "n.", zh: "法規", d: "an official rule",
        syn: ["rule", "directive"],
        ph: [["safety regulations", "安全法規"], ["comply with regulations", "遵守法規"]] },
      { w: "raw material", p: "n.", zh: "原物料", d: "the basic material from which goods are made",
        ph: [["rising raw material costs", "原物料成本上升"]] },
      { w: "component part", p: "n.", zh: "零組件", d: "a piece used to build a finished product",
        ph: [["source component parts", "採購零組件"]] },
      { w: "batch", p: "n.", zh: "批次", d: "a quantity produced at one time",
        ph: [["a batch number", "批號"], ["scrap the whole batch", "整批報廢"]] },
      { w: "scrap", p: "v./n.", zh: "報廢;廢料", d: "to throw away as useless; waste material",
        syn: ["discard", "junk"],
        ph: [["scrap metal", "廢金屬"], ["scrap the plan", "取消計畫"]] },
      { w: "waste", p: "n./v.", zh: "廢棄物;浪費", d: "unwanted material; to use badly",
        ph: [["reduce waste", "減少浪費"], ["waste disposal", "廢棄物處理"]] },
      { w: "warehouse worker", p: "n.", zh: "倉儲人員", d: "a person who works in a storage building",
        ph: [["hire warehouse workers", "招募倉儲人員"]] },
      { w: "operate", p: "v.", zh: "操作;營運", d: "to control a machine; to run a business",
        ph: [["operate machinery", "操作機械"], ["operating hours", "營運時間"], ["operating costs", "營運成本"]] },
      { w: "install a line", p: "n.", zh: "架設產線", d: "to set up a production line",
        ph: [["install a new production line", "架設新產線"]] },
      { w: "supervise", p: "v.", zh: "監督", d: "to watch and direct work",
        syn: ["oversee", "monitor"],
        r: "super-(在上) + vis(看)" },
      { w: "monitor", p: "v./n.", zh: "監測;螢幕", d: "to watch and check progress over time",
        syn: ["track", "observe"],
        ph: [["monitor performance", "監測效能"], ["closely monitored", "嚴密監控"]] },
      { w: "calibrate", p: "v.", zh: "校準", d: "to adjust an instrument so it measures accurately",
        ph: [["calibrate the sensors", "校準感測器"]] },
      { w: "durable goods", p: "n.", zh: "耐久財", d: "products meant to last a long time",
        ant: ["consumables"] },
      { w: "capacity utilization", p: "n.", zh: "產能利用率", d: "how much of the possible output is used",
        ph: [["running at 80% capacity", "產能利用率八成"]] },
      { w: "efficiency gain", p: "n.", zh: "效率提升", d: "an improvement in how well resources are used",
        ph: [["deliver efficiency gains", "帶來效率提升"]] },
      { w: "downtime cost", p: "n.", zh: "停機損失", d: "money lost while equipment is not running",
        ph: [["reduce downtime costs", "降低停機損失"]] },
      { w: "prototype", p: "n.", zh: "原型機", d: "the first version of a product used for testing",
        ph: [["test the prototype", "測試原型機"]] },
      { w: "standardize", p: "v.", zh: "標準化", d: "to make things the same as an agreed standard",
        ph: [["standardize procedures", "把程序標準化"]],
        r: "standard + -ize(使…化)" },
    ]},

  { id: "travel", no: 8, name: "旅遊", en: "Travel", icon: "✈️",
    map: { center: "旅遊", branches: [
      { label: "訂位", ws: ["reservation", "itinerary", "confirmation", "voucher", "fare"] },
      { label: "機場", ws: ["boarding", "departure", "layover", "terminal", "baggage"] },
      { label: "住宿", ws: ["accommodation", "check-in", "vacancy", "amenity", "suite"] },
      { label: "交通", ws: ["shuttle", "commute", "rental", "fare", "transit"] },
      { label: "狀況", ws: ["delay", "cancel", "overbook", "reissue", "compensation"] },
    ]},
    list: [
      { w: "reservation", p: "n.", zh: "訂位;預訂", d: "an arrangement to keep a seat or room for someone",
        syn: ["booking"],
        ph: [["make a reservation", "訂位"], ["under the name of", "以…的名字訂的"]],
        n: "美式常用 reservation,英式常用 booking,兩者聽力都會出現。" },
      { w: "itinerary", p: "n.", zh: "行程表", d: "a detailed plan of a journey",
        syn: ["schedule", "travel plan"],
        ph: [["a detailed itinerary", "詳細行程"], ["revise the itinerary", "修改行程"]],
        n: "唸 /aɪˈtɪnəreri/,重音在第二音節,是聽力難字。" },
      { w: "confirmation", p: "n.", zh: "確認(信/碼)", d: "a message proving a booking is complete",
        ph: [["a confirmation email", "確認信"], ["your confirmation number", "訂位代號"]] },
      { w: "voucher", p: "n.", zh: "抵用券;憑證", d: "a ticket that can be exchanged for goods or services",
        syn: ["coupon", "certificate"],
        ph: [["a meal voucher", "餐券"], ["redeem a voucher", "兌換抵用券"]] },
      { w: "fare", p: "n.", zh: "車資;票價", d: "the money paid to travel",
        ph: [["a one-way fare", "單程票價"], ["fare increase", "票價調漲"]],
        n: "fare 是「交通票價」,fee 是「服務費」,fine 是「罰款」——三字常被放在同一題。" },
      { w: "boarding", p: "n.", zh: "登機(上車)", d: "the act of getting on a plane, ship or train",
        ph: [["a boarding pass", "登機證"], ["boarding begins at gate 12", "十二號登機門開始登機"]] },
      { w: "departure", p: "n.", zh: "出發;離開", d: "the act of leaving a place",
        ant: ["arrival"],
        ph: [["the departure lounge", "候機室"], ["departure time", "出發時間"]] },
      { w: "layover", p: "n.", zh: "轉機停留", d: "a short stop between two flights",
        syn: ["stopover", "connection"],
        ph: [["a two-hour layover", "兩小時轉機停留"]] },
      { w: "terminal", p: "n.", zh: "航廈;總站", d: "a building where journeys begin and end",
        ph: [["Terminal 2", "第二航廈"], ["a bus terminal", "巴士總站"]] },
      { w: "baggage", p: "n.", zh: "行李", d: "the bags you take when traveling",
        syn: ["luggage"],
        ph: [["baggage claim", "行李提領處"], ["checked baggage", "託運行李"], ["carry-on baggage", "隨身行李"]],
        n: "不可數!不能說 baggages;要數用 two pieces of baggage。" },
      { w: "accommodation", p: "n.", zh: "住宿", d: "a place to stay",
        syn: ["lodging"],
        ph: [["arrange accommodation", "安排住宿"], ["overnight accommodation", "過夜住宿"]],
        n: "拼字陷阱:兩個 c、兩個 m(ac-com-mo-da-tion)。" },
      { w: "check-in", p: "n.", zh: "報到;入住", d: "the process of registering at a hotel or airport",
        ant: ["check-out"],
        ph: [["check-in opens at 3 p.m.", "下午三點開放入住"], ["online check-in", "線上報到"]] },
      { w: "vacancy", p: "n.", zh: "空房", d: "a room that is available",
        ph: [["No vacancies", "客滿"], ["do you have any vacancies?", "還有空房嗎?"]] },
      { w: "amenity", p: "n.", zh: "設施;便利設備", d: "a useful feature of a place",
        ph: [["hotel amenities", "飯店設施"], ["in-room amenities", "客房備品"]] },
      { w: "suite", p: "n.", zh: "套房", d: "a set of connected rooms in a hotel",
        ph: [["a deluxe suite", "豪華套房"]],
        n: "唸 /swiːt/,和 sweet 同音,是聽力同音字陷阱。" },
      { w: "shuttle", p: "n./v.", zh: "接駁車", d: "a vehicle traveling regularly between two places",
        ph: [["an airport shuttle", "機場接駁車"], ["a complimentary shuttle", "免費接駁"]] },
      { w: "complimentary", p: "adj.", zh: "免費招待的", d: "given free of charge",
        syn: ["free", "on the house"],
        ph: [["a complimentary breakfast", "免費早餐"], ["complimentary Wi-Fi", "免費無線網路"]],
        n: "complimentary(免費的)vs. complementary(互補的),差一個字母意思全變,經典考點。" },
      { w: "rental", p: "n./adj.", zh: "租賃", d: "the act of renting; something rented",
        ph: [["a car rental agency", "租車公司"], ["rental fee", "租金"]] },
      { w: "transit", p: "n.", zh: "運輸;過境", d: "the movement of people or goods",
        ph: [["public transit", "大眾運輸"], ["in transit", "運送途中"], ["a transit visa", "過境簽證"]] },
      { w: "delay", p: "n./v.", zh: "延誤", d: "a situation where something happens later than planned",
        syn: ["holdup", "postponement"],
        ph: [["a two-hour delay", "延誤兩小時"], ["delayed due to weather", "因天候延誤"]] },
      { w: "cancel", p: "v.", zh: "取消", d: "to decide that something will not happen",
        syn: ["call off", "scrap"], ant: ["confirm", "reinstate"],
        ph: [["cancel a reservation", "取消訂位"], ["a cancellation fee", "取消手續費"]],
        n: "名詞是 cancellation(兩個 l),動詞美式 canceled、英式 cancelled。" },
      { w: "overbook", p: "v.", zh: "超賣;超額訂位", d: "to sell more seats or rooms than are available",
        ph: [["the flight was overbooked", "班機超賣"]] },
      { w: "reissue", p: "v.", zh: "重新開立", d: "to issue a ticket or document again",
        ph: [["reissue the ticket", "重開機票"]] },
      { w: "compensation", p: "n.", zh: "賠償", d: "money given to make up for a loss",
        ph: [["claim compensation", "申請賠償"], ["compensation for the delay", "延誤賠償"]] },
      { w: "destination", p: "n.", zh: "目的地", d: "the place someone is traveling to",
        ph: [["a popular destination", "熱門景點"], ["final destination", "最終目的地"]],
        r: "de-(完全) + stin(站定) → 最終停下的地方" },
      { w: "excursion", p: "n.", zh: "遠足;短程旅遊", d: "a short trip for pleasure",
        syn: ["outing", "day trip"],
        ph: [["a guided excursion", "導覽行程"]] },
      { w: "customs", p: "n.", zh: "海關", d: "the place where officials check goods entering a country",
        ph: [["go through customs", "通關"], ["customs declaration", "海關申報"]],
        n: "永遠複數;custom(單數)是「習俗」,意思完全不同。" },
      { w: "passport control", p: "n.", zh: "證照查驗", d: "the place where passports are checked",
        ph: [["proceed to passport control", "前往證照查驗"]] },
      { w: "aisle", p: "n.", zh: "走道", d: "a passage between rows of seats",
        ant: ["window seat"],
        ph: [["an aisle seat", "走道座位"]],
        n: "s 不發音,唸 /aɪl/,和 I'll 同音,是聽力陷阱。" },
      { w: "depart", p: "v.", zh: "出發", d: "to leave, especially to start a journey",
        ant: ["arrive"],
        ph: [["depart from Gate 5", "由五號門出發"]] },
      { w: "connecting flight", p: "n.", zh: "轉接班機", d: "a second flight taken to reach a destination",
        ph: [["miss a connecting flight", "錯過轉機"]] },
      { w: "expire", p: "v.", zh: "到期", d: "to come to an end; to be no longer valid",
        ph: [["the passport expires in June", "護照六月到期"], ["an expiration date", "有效期限"]],
        r: "ex-(出) + spir(呼吸) → 呼出最後一口氣" },
      { w: "valid", p: "adj.", zh: "有效的", d: "legally or officially acceptable",
        ant: ["invalid", "expired"],
        ph: [["a valid ID", "有效證件"], ["valid until December", "有效期至十二月"]] },
      { w: "lodge", p: "v./n.", zh: "投宿;提出(申訴)", d: "to stay somewhere; to make an official complaint",
        ph: [["lodge a complaint", "提出申訴"]] },
      { w: "concierge", p: "n.", zh: "飯店禮賓人員", d: "a hotel employee who helps guests with arrangements",
        ph: [["ask the concierge", "詢問禮賓人員"]] },
      { w: "occupancy", p: "n.", zh: "住房率;使用", d: "the proportion of rooms being used",
        ph: [["a high occupancy rate", "高住房率"], ["maximum occupancy", "最大容納人數"]] },
      { w: "round-trip", p: "adj.", zh: "來回的", d: "going to a place and back again",
        ant: ["one-way"],
        ph: [["a round-trip ticket", "來回機票"]],
        n: "美式 round-trip,英式 return ticket;single = one-way(單程)。" },
      { w: "upgrade a seat", p: "v.", zh: "升等座位", d: "to move to a better class of seat",
        ph: [["upgrade to business class", "升等商務艙"]] },
      { w: "luggage", p: "n.", zh: "行李", d: "bags and cases used when traveling",
        n: "同 baggage,不可數;lost luggage(行李遺失)是常見情境。" },
      { w: "detour", p: "n.", zh: "繞道", d: "a longer route taken to avoid a problem",
        ph: [["take a detour", "繞道而行"]],
        r: "de-(離開) + tour(轉) → 轉離原路" },
    ]},

  { id: "ent", no: 9, name: "娛樂與藝文", en: "Entertainment & Media", icon: "🎭",
    map: { center: "娛樂藝文", branches: [
      { label: "表演", ws: ["performance", "venue", "rehearsal", "audience", "premiere"] },
      { label: "展覽", ws: ["exhibition", "gallery", "curator", "admission", "collection"] },
      { label: "票務", ws: ["box office", "sold out", "matinee", "subscription", "refund"] },
      { label: "媒體", ws: ["broadcast", "coverage", "review", "critic", "publication"] },
      { label: "評價", ws: ["acclaim", "feature", "renowned", "debut", "sequel"] },
    ]},
    list: [
      { w: "performance", p: "n.", zh: "演出;表現", d: "an act of entertaining an audience; how well someone does",
        ph: [["a live performance", "現場演出"], ["performance review", "績效考核"]],
        n: "藝文情境是「演出」,人事情境是「績效」,同字跨情境。" },
      { w: "venue", p: "n.", zh: "場地", d: "the place where an event happens",
        syn: ["location", "site"],
        ph: [["change the venue", "更換場地"], ["a concert venue", "演唱會場地"]] },
      { w: "rehearsal", p: "n.", zh: "排練", d: "a practice session before a performance",
        ph: [["a dress rehearsal", "彩排"], ["attend rehearsals", "參加排練"]] },
      { w: "audience", p: "n.", zh: "觀眾", d: "the people watching or listening to a performance",
        syn: ["spectators", "viewers"],
        ph: [["a packed audience", "滿場觀眾"], ["audience participation", "觀眾互動"]] },
      { w: "premiere", p: "n./v.", zh: "首映;首演", d: "the first public performance of a film or play",
        syn: ["debut", "opening night"],
        ph: [["the world premiere", "全球首映"]] },
      { w: "debut", p: "n./v.", zh: "初次登場", d: "a first appearance in public",
        ph: [["make one's debut", "初次亮相"], ["a debut album", "首張專輯"]],
        n: "唸 /deɪˈbjuː/,t 不發音,是法文外來字。" },
      { w: "exhibition", p: "n.", zh: "展覽", d: "a public show of art or products",
        syn: ["exhibit", "display", "show"],
        ph: [["hold an exhibition", "舉辦展覽"], ["the exhibition runs through May", "展至五月"]] },
      { w: "gallery", p: "n.", zh: "藝廊", d: "a place where art is shown or sold",
        ph: [["an art gallery", "美術館"], ["a gallery opening", "開幕酒會"]] },
      { w: "curator", p: "n.", zh: "策展人", d: "a person who organizes an exhibition",
        ph: [["the museum curator", "博物館策展人"]],
        r: "cur(照料) + -ator(人) → 照料收藏品的人" },
      { w: "collection", p: "n.", zh: "收藏;系列", d: "a group of objects or works kept together",
        ph: [["a private collection", "私人收藏"], ["the spring collection", "春季系列"]] },
      { w: "admission", p: "n.", zh: "入場(費);承認", d: "the cost or right to enter",
        syn: ["entry", "entrance fee"],
        ph: [["free admission", "免費入場"], ["admission is $12", "入場費十二元"]] },
      { w: "box office", p: "n.", zh: "售票處;票房", d: "the place where tickets are sold; ticket sales",
        ph: [["at the box office", "在售票處"], ["a box office hit", "票房大賣的作品"]] },
      { w: "sold out", p: "adj.", zh: "售罄", d: "with no tickets left",
        ph: [["the show is sold out", "演出票已售完"]] },
      { w: "matinee", p: "n.", zh: "日場演出", d: "an afternoon performance",
        ant: ["evening show"],
        ph: [["a Saturday matinee", "週六日場"]] },
      { w: "subscription", p: "n.", zh: "訂閱;套票", d: "an arrangement to receive something regularly",
        ph: [["a season subscription", "全季套票"], ["renew a subscription", "續訂"]],
        r: "sub-(在下) + scrib(寫) → 在下面簽名同意" },
      { w: "broadcast", p: "v./n.", zh: "播送;節目", d: "to send out a program on television or radio",
        syn: ["air", "transmit"],
        ph: [["broadcast live", "現場直播"], ["a news broadcast", "新聞播報"]] },
      { w: "coverage", p: "n.", zh: "報導;涵蓋範圍", d: "the reporting of news; the extent included",
        ph: [["media coverage", "媒體報導"], ["insurance coverage", "保險給付範圍"]],
        n: "媒體情境是「報導」,保險情境是「給付範圍」,兩義都考。" },
      { w: "review", p: "n./v.", zh: "評論;審查", d: "a written opinion about a work; to examine again",
        ph: [["rave reviews", "好評如潮"], ["a peer review", "同儕審查"]] },
      { w: "critic", p: "n.", zh: "評論家", d: "a person who judges books, films or art",
        ph: [["a film critic", "影評人"], ["critics praised it", "評論家給予好評"]],
        n: "critic(評論家,人)、critical(批判的/關鍵的)、criticism(批評),整組一起背。" },
      { w: "acclaim", p: "n./v.", zh: "讚譽", d: "public praise",
        syn: ["praise", "applause"], ant: ["criticism"],
        ph: [["critical acclaim", "評論界好評"], ["widely acclaimed", "廣受讚譽"]] },
      { w: "renowned", p: "adj.", zh: "著名的", d: "famous and admired",
        syn: ["celebrated", "prominent"], ant: ["obscure", "unknown"],
        ph: [["a renowned pianist", "知名鋼琴家"], ["renowned for its design", "以設計聞名"]] },
      { w: "feature", p: "v./n.", zh: "以…為主角;特色", d: "to include as an important part",
        ph: [["the film features", "本片由…主演"], ["a feature article", "專題報導"]] },
      { w: "sequel", p: "n.", zh: "續集", d: "a film or book that continues an earlier story",
        ant: ["prequel"],
        r: "sequ(跟隨) + -el → 接著來的" },
      { w: "publication", p: "n.", zh: "出版(品)", d: "a book or magazine; the act of publishing",
        ph: [["a monthly publication", "月刊"], ["the publication date", "出版日期"]] },
      { w: "issue", p: "n./v.", zh: "期號;發行;議題", d: "one edition of a magazine; to give out officially",
        ph: [["the latest issue", "最新一期"], ["issue a statement", "發表聲明"]],
        n: "多益三義都常考:期刊的「期」、正式「發布」、討論的「議題」。" },
      { w: "screening", p: "n.", zh: "放映;篩檢", d: "a showing of a film; a medical or job check",
        ph: [["a private screening", "私人放映會"], ["health screening", "健康篩檢"]] },
      { w: "auditorium", p: "n.", zh: "禮堂;觀眾席", d: "a large room where an audience sits",
        ph: [["the main auditorium", "大禮堂"]] },
      { w: "intermission", p: "n.", zh: "中場休息", d: "a short break during a performance",
        syn: ["interval", "break"],
        ph: [["a fifteen-minute intermission", "十五分鐘中場休息"]],
        r: "inter-(之間) + miss(送) → 送到中間的空檔" },
      { w: "usher", p: "n./v.", zh: "引座員;引導", d: "a person who shows people to their seats",
        ph: [["an usher will show you to your seat", "引座員會帶您入座"]] },
      { w: "lineup", p: "n.", zh: "節目陣容", d: "the list of performers at an event",
        ph: [["the festival lineup", "音樂節陣容"]] },
      { w: "exhibit", p: "n./v.", zh: "展品;展出", d: "an object shown publicly; to display",
        ph: [["a special exhibit", "特展"], ["exhibit at the fair", "在展會參展"]] },
      { w: "retrospective", p: "n.", zh: "回顧展", d: "an exhibition of an artist's work over many years",
        r: "retro-(向後) + spect(看) → 回頭看" },
      { w: "sponsor", p: "n./v.", zh: "贊助商;贊助", d: "a company that pays to support an event",
        ph: [["the official sponsor", "官方贊助商"], ["sponsored by", "由…贊助"]] },
      { w: "attendee", p: "n.", zh: "與會者", d: "a person who attends an event",
        ph: [["registered attendees", "已報名的與會者"]],
        n: "-ee 結尾表示「動作的接受方」:attendee、employee、interviewee。" },
      { w: "showcase", p: "v./n.", zh: "展現;櫥窗", d: "to present something in an attractive way",
        ph: [["showcase local talent", "展現在地人才"]] },
      { w: "release", p: "v./n.", zh: "發行;釋出", d: "to make a product available to the public",
        syn: ["launch", "issue"],
        ph: [["a new release", "新發行作品"], ["release the album", "發行專輯"]] },
      { w: "commemorate", p: "v.", zh: "紀念", d: "to remember an important event with a ceremony",
        ph: [["commemorate the anniversary", "紀念週年"]],
        r: "com-(共同) + memor(記憶) → 共同記得" },
      { w: "anniversary", p: "n.", zh: "週年紀念", d: "the date on which an event happened in a previous year",
        ph: [["the 50th anniversary", "五十週年"]],
        r: "anni(年) + vers(轉) → 一年轉一圈" },
      { w: "raffle", p: "n.", zh: "抽獎", d: "a competition where people buy numbered tickets",
        ph: [["a raffle prize", "抽獎獎品"]] },
      { w: "refreshments", p: "n.", zh: "茶點", d: "light food and drinks served at an event",
        ph: [["refreshments will be served", "將提供茶點"]] },
    ]},

  { id: "health", no: 10, name: "健康保健", en: "Health Care", icon: "🏥",
    map: { center: "健康保健", branches: [
      { label: "就醫", ws: ["appointment", "physician", "clinic", "referral", "consultation"] },
      { label: "診療", ws: ["diagnose", "symptom", "prescription", "dosage", "treatment"] },
      { label: "檢查", ws: ["checkup", "screening", "specimen", "physical", "monitor"] },
      { label: "保險", ws: ["coverage", "premium", "deductible", "claim", "reimburse"] },
      { label: "職場健康", ws: ["wellness", "sick leave", "ergonomic", "immunization", "recovery"] },
    ]},
    list: [
      { w: "physician", p: "n.", zh: "內科醫師", d: "a medical doctor",
        syn: ["doctor", "practitioner"],
        ph: [["a family physician", "家庭醫師"], ["consult a physician", "諮詢醫師"]] },
      { w: "clinic", p: "n.", zh: "診所", d: "a place where people receive medical treatment",
        ph: [["a walk-in clinic", "免預約診所"], ["clinic hours", "門診時間"]] },
      { w: "referral", p: "n.", zh: "轉診(單)", d: "the act of sending a patient to a specialist",
        ph: [["a referral to a specialist", "轉診至專科醫師"], ["require a referral", "需要轉診單"]] },
      { w: "consultation", p: "n.", zh: "諮詢;會診", d: "a meeting with a professional for advice",
        ph: [["a free consultation", "免費諮詢"], ["in consultation with", "與…商議後"]] },
      { w: "diagnose", p: "v.", zh: "診斷", d: "to identify an illness",
        ph: [["be diagnosed with", "被診斷出患有…"], ["an early diagnosis", "早期診斷"]],
        n: "名詞 diagnosis(複數 diagnoses),動詞 diagnose,Part 5 常考詞性。" },
      { w: "symptom", p: "n.", zh: "症狀", d: "a sign that you have an illness",
        ph: [["flu-like symptoms", "類流感症狀"], ["symptoms persist", "症狀持續"]] },
      { w: "prescription", p: "n.", zh: "處方(箋)", d: "a doctor's written order for medicine",
        ph: [["fill a prescription", "領取處方藥"], ["a prescription refill", "續領處方"]],
        n: "fill a prescription 是「去藥局拿藥」,不是「填表格」——閱讀常誤解。",
        r: "pre-(事前) + scrib(寫) → 事先寫下的指示" },
      { w: "dosage", p: "n.", zh: "劑量", d: "the amount of medicine to take",
        ph: [["the recommended dosage", "建議劑量"], ["exceed the dosage", "超過劑量"]] },
      { w: "treatment", p: "n.", zh: "治療", d: "medical care given to a patient",
        syn: ["therapy", "care"],
        ph: [["undergo treatment", "接受治療"], ["a course of treatment", "一個療程"]] },
      { w: "checkup", p: "n.", zh: "健康檢查", d: "a general medical examination",
        syn: ["physical examination"],
        ph: [["an annual checkup", "年度健檢"], ["schedule a checkup", "安排健檢"]] },
      { w: "screening", p: "n.", zh: "篩檢", d: "testing people for early signs of disease",
        ph: [["a cancer screening", "癌症篩檢"]] },
      { w: "specimen", p: "n.", zh: "檢體;樣本", d: "a small amount taken for testing",
        syn: ["sample"],
        ph: [["a blood specimen", "血液檢體"]] },
      { w: "physical", p: "n./adj.", zh: "體檢;身體的", d: "a medical examination; relating to the body",
        ph: [["an annual physical", "年度體檢"], ["physical therapy", "物理治療"]] },
      { w: "coverage", p: "n.", zh: "保險給付範圍", d: "what an insurance policy pays for",
        ph: [["dental coverage", "牙科給付"], ["full coverage", "全額給付"]] },
      { w: "premium", p: "n./adj.", zh: "保費;高級的", d: "the amount paid for insurance; of high quality",
        ph: [["monthly premiums", "月繳保費"], ["a premium service", "高級服務"]],
        n: "保險情境是「保費」,商品情境是「高級的」,兩義都是多益常客。" },
      { w: "deductible", p: "n.", zh: "自付額", d: "the amount you pay before insurance covers the rest",
        ph: [["a $500 deductible", "五百元自付額"]] },
      { w: "claim", p: "n./v.", zh: "理賠申請", d: "a request for payment from an insurance company",
        ph: [["file an insurance claim", "申請理賠"], ["process a claim", "受理理賠"]] },
      { w: "reimburse", p: "v.", zh: "核退;償付", d: "to pay back money that has been spent",
        ph: [["reimburse medical costs", "核退醫療費用"]] },
      { w: "policy", p: "n.", zh: "保單;政策", d: "an insurance contract; a plan of action",
        ph: [["an insurance policy", "保單"], ["company policy", "公司政策"]],
        n: "「保單」和「政策」兩義都高頻,靠情境判斷。" },
      { w: "wellness", p: "n.", zh: "健康促進", d: "the state of being in good health",
        ph: [["a corporate wellness program", "企業健康促進計畫"]] },
      { w: "sick leave", p: "n.", zh: "病假", d: "time off work because of illness",
        ph: [["take sick leave", "請病假"], ["paid sick leave", "有薪病假"]] },
      { w: "ergonomic", p: "adj.", zh: "人體工學的", d: "designed to be comfortable and reduce injury",
        ph: [["an ergonomic chair", "人體工學椅"]],
        r: "ergo(工作) + nom(法則) → 工作方式的法則" },
      { w: "immunization", p: "n.", zh: "疫苗接種", d: "the process of protecting against disease",
        syn: ["vaccination"],
        ph: [["an immunization record", "接種紀錄"]] },
      { w: "recovery", p: "n.", zh: "康復;回升", d: "the process of getting better",
        ph: [["a full recovery", "完全康復"], ["economic recovery", "經濟復甦"]] },
      { w: "chronic", p: "adj.", zh: "慢性的", d: "continuing for a long time",
        ant: ["acute"],
        ph: [["a chronic condition", "慢性病"], ["chronic pain", "慢性疼痛"]],
        n: "chronic(慢性、長期)vs. acute(急性、劇烈),醫療閱讀常對比。",
        r: "chron(時間) + -ic → 與時間拉長有關" },
      { w: "acute", p: "adj.", zh: "急性的;劇烈的", d: "severe and beginning suddenly",
        ant: ["chronic", "mild"],
        ph: [["acute pain", "劇痛"], ["an acute shortage", "嚴重短缺"]] },
      { w: "practitioner", p: "n.", zh: "執業者;醫師", d: "a person qualified to practice medicine or law",
        ph: [["a general practitioner (GP)", "家醫科醫師"]] },
      { w: "pharmacy", p: "n.", zh: "藥局", d: "a shop where medicines are sold",
        syn: ["drugstore"],
        ph: [["pick it up at the pharmacy", "到藥局領取"]] },
      { w: "pharmacist", p: "n.", zh: "藥師", d: "a person trained to prepare medicines",
        ph: [["ask the pharmacist", "詢問藥師"]] },
      { w: "medication", p: "n.", zh: "藥物", d: "medicine used to treat an illness",
        ph: [["take medication", "服藥"], ["be on medication", "正在服藥"]] },
      { w: "side effect", p: "n.", zh: "副作用", d: "an unwanted effect of a medicine",
        ph: [["mild side effects", "輕微副作用"]] },
      { w: "allergy", p: "n.", zh: "過敏", d: "a bad reaction to a substance",
        ph: [["an allergy to nuts", "堅果過敏"], ["allergic reaction", "過敏反應"]] },
      { w: "nutrition", p: "n.", zh: "營養", d: "the food needed to stay healthy",
        ph: [["nutrition label", "營養標示"], ["nutritional value", "營養價值"]] },
      { w: "hygiene", p: "n.", zh: "衛生", d: "keeping things clean to prevent illness",
        ph: [["food hygiene", "食品衛生"], ["personal hygiene", "個人衛生"]] },
      { w: "sanitize", p: "v.", zh: "消毒", d: "to clean something to remove germs",
        syn: ["disinfect", "sterilize"],
        ph: [["sanitize surfaces", "消毒表面"]] },
      { w: "quarantine", p: "n./v.", zh: "隔離檢疫", d: "a period of separation to prevent spreading disease",
        ph: [["placed under quarantine", "被隔離"]],
        r: "quaranta(四十) → 源自船隻須停泊四十天" },
      { w: "outbreak", p: "n.", zh: "疫情爆發", d: "the sudden start of a disease in an area",
        ph: [["a flu outbreak", "流感爆發"]] },
      { w: "ward", p: "n.", zh: "病房", d: "a large room in a hospital with beds for patients",
        ph: [["the maternity ward", "產科病房"]] },
      { w: "admit", p: "v.", zh: "收治住院;承認", d: "to take someone into a hospital; to accept as true",
        ph: [["be admitted to hospital", "住院"]] },
      { w: "discharge", p: "v./n.", zh: "出院;解僱", d: "to allow a patient to leave hospital",
        ant: ["admit"],
        ph: [["be discharged from hospital", "出院"], ["discharge instructions", "出院須知"]] },
    ]},
);
