// ============================================================
//  📕 多益 13 大主題字彙庫(2/4):財務預算・採購・技術領域
// ============================================================

TOEIC_VOCAB.push(
  { id: "fin", no: 4, name: "財務預算", en: "Finance & Budgeting", icon: "💰",
    map: { center: "財務預算", branches: [
      { label: "預算", ws: ["budget", "allocate", "expenditure", "overhead", "surplus"] },
      { label: "報表", ws: ["statement", "balance", "asset", "liability", "audit"] },
      { label: "銀行", ws: ["deposit", "withdraw", "interest", "mortgage", "installment"] },
      { label: "帳務", ws: ["invoice", "reimburse", "transaction", "settle", "outstanding"] },
      { label: "稅務投資", ws: ["taxable", "deduction", "dividend", "portfolio", "yield"] },
    ]},
    list: [
      { w: "budget", p: "n./v.", zh: "預算;編列預算", d: "a plan of how much money will be spent",
        ph: [["stay within budget", "不超出預算"], ["over budget", "超出預算"], ["a tight budget", "拮据的預算"]],
        n: "形容詞用法也常考:a budget hotel = 平價旅館(不是「預算旅館」)。" },
      { w: "allocate", p: "v.", zh: "撥款;分配", d: "to give money or resources for a purpose",
        syn: ["assign", "earmark", "distribute"],
        ph: [["allocate funds to", "撥款給…"], ["budget allocation", "預算分配"]],
        r: "al-(朝向) + loc(位置) + -ate → 放到指定位置" },
      { w: "expenditure", p: "n.", zh: "支出", d: "the total amount of money spent",
        syn: ["spending", "outlay"], ant: ["income", "revenue"],
        ph: [["capital expenditure", "資本支出"], ["cut expenditure", "削減支出"]] },
      { w: "expense", p: "n.", zh: "費用;開銷", d: "money spent on something specific",
        ph: [["travel expenses", "差旅費"], ["an expense report", "費用報銷單"], ["at the company's expense", "由公司負擔"]] },
      { w: "overhead", p: "n.", zh: "營運間接成本", d: "regular costs of running a business",
        ph: [["reduce overhead costs", "降低營運成本"]],
        n: "指房租、水電等「不直接產生產品」的固定支出。" },
      { w: "fiscal", p: "adj.", zh: "財政的;會計的", d: "relating to government or business money",
        syn: ["financial", "monetary"],
        ph: [["the fiscal year", "會計年度"], ["fiscal policy", "財政政策"]] },
      { w: "quarterly", p: "adj./adv.", zh: "每季的", d: "happening four times a year",
        ph: [["quarterly earnings", "季度盈餘"], ["report quarterly", "按季回報"]] },
      { w: "audit", p: "n./v.", zh: "審計;查帳", d: "an official examination of financial records",
        ph: [["an internal audit", "內部稽核"], ["audit the accounts", "查核帳目"]],
        r: "audi(聽) + -t → 早期查帳靠「聽」帳目宣讀" },
      { w: "statement", p: "n.", zh: "對帳單;聲明", d: "a printed record of money in an account",
        ph: [["a bank statement", "銀行對帳單"], ["a financial statement", "財務報表"]] },
      { w: "balance", p: "n./v.", zh: "餘額;結算", d: "the amount of money left in an account",
        ph: [["the outstanding balance", "未付餘額"], ["balance the books", "結清帳目"]] },
      { w: "asset", p: "n.", zh: "資產", d: "something valuable that a company owns",
        ant: ["liability"],
        ph: [["fixed assets", "固定資產"], ["an asset to the team", "團隊的寶貴人才"]],
        n: "asset 也可形容人:She is a real asset to our department.(她是部門的一大助力)" },
      { w: "liability", p: "n.", zh: "負債;責任", d: "money owed; legal responsibility",
        ant: ["asset"],
        ph: [["limited liability", "有限責任"], ["assets and liabilities", "資產與負債"]] },
      { w: "equity", p: "n.", zh: "股權;權益", d: "the value of shares in a company",
        ph: [["private equity", "私募股權"], ["shareholders' equity", "股東權益"]] },
      { w: "deficit", p: "n.", zh: "赤字;不足額", d: "the amount by which money spent exceeds money received",
        ant: ["surplus"],
        ph: [["a trade deficit", "貿易逆差"], ["run a deficit", "出現赤字"]],
        r: "de-(缺少) + fic(做) → 沒做足的部分" },
      { w: "surplus", p: "n./adj.", zh: "盈餘;剩餘的", d: "an amount more than what is needed",
        ant: ["deficit", "shortage"],
        ph: [["a budget surplus", "預算盈餘"], ["surplus stock", "剩餘庫存"]],
        r: "sur-(超過) + plus(多) → 多出來的" },
      { w: "invoice", p: "n./v.", zh: "發票;請款單", d: "a document listing goods sold and the money owed",
        syn: ["bill"],
        ph: [["issue an invoice", "開立請款單"], ["settle the invoice", "支付款項"]],
        n: "invoice 是「請你付錢的單」,receipt 是「已付款的收據」,順序不同。" },
      { w: "receipt", p: "n.", zh: "收據", d: "a paper showing that payment has been made",
        ph: [["keep the receipt", "保留收據"], ["upon receipt of", "一收到…就"]],
        n: "p 不發音,唸 /rɪˈsiːt/;upon receipt of your order 是商務書信常見句型。" },
      { w: "reimburse", p: "v.", zh: "報銷;償還", d: "to pay money back to someone",
        syn: ["refund", "repay"],
        ph: [["reimburse travel costs", "報銷差旅費"], ["submit for reimbursement", "提出報銷申請"]],
        r: "re-(回) + im-(進入) + burse(錢包) → 把錢放回你的錢包" },
      { w: "transaction", p: "n.", zh: "交易", d: "an act of buying or selling",
        syn: ["deal", "trade"],
        ph: [["a cash transaction", "現金交易"], ["transaction fee", "手續費"]],
        r: "trans-(跨越) + act(做) → 兩方之間來回的動作" },
      { w: "settle", p: "v.", zh: "結清;解決", d: "to pay money that is owed; to end a dispute",
        ph: [["settle the bill", "結帳"], ["settle a dispute", "解決爭議"]] },
      { w: "outstanding", p: "adj.", zh: "未付的;傑出的", d: "not yet paid; extremely good",
        ph: [["an outstanding balance", "未清餘額"], ["outstanding performance", "傑出表現"]],
        n: "財務情境是「未付」,人事情境是「傑出」——同字反差極大,是閱讀陷阱。" },
      { w: "deposit", p: "n./v.", zh: "訂金;存款;存入", d: "money paid in advance or put into an account",
        ant: ["withdraw"],
        ph: [["a security deposit", "押金"], ["deposit a check", "存入支票"]] },
      { w: "withdraw", p: "v.", zh: "提款;撤回", d: "to take money out; to remove something",
        ant: ["deposit", "submit"],
        ph: [["withdraw cash", "提領現金"], ["withdraw an application", "撤回申請"]],
        r: "with-(離開) + draw(拉) → 拉出來" },
      { w: "installment", p: "n.", zh: "分期付款", d: "one of several payments made over time",
        ph: [["pay in installments", "分期付款"], ["monthly installments", "月付"]] },
      { w: "mortgage", p: "n.", zh: "房貸", d: "a loan to buy property",
        ph: [["apply for a mortgage", "申請房貸"], ["a mortgage rate", "房貸利率"]],
        n: "t 不發音:/ˈmɔːrɡɪdʒ/。字面源自「死的抵押」(mort = 死)。",
        r: "mort(死) + gage(抵押) → 還清即「解除」的抵押" },
      { w: "interest", p: "n.", zh: "利息;興趣", d: "money charged for borrowing; a feeling of wanting to know",
        ph: [["an interest rate", "利率"], ["interest-free", "免息"]] },
      { w: "dividend", p: "n.", zh: "股利", d: "part of a company's profit paid to shareholders",
        ph: [["pay a dividend", "發放股利"]],
        r: "divid(分開) + -end → 要被分掉的東西" },
      { w: "portfolio", p: "n.", zh: "投資組合;作品集", d: "a set of investments, or a collection of work",
        ph: [["an investment portfolio", "投資組合"], ["a design portfolio", "設計作品集"]] },
      { w: "yield", p: "n./v.", zh: "收益;產生", d: "the profit produced; to produce a result",
        syn: ["return", "produce"],
        ph: [["a high yield", "高收益"], ["yield results", "產生成果"]] },
      { w: "taxable", p: "adj.", zh: "應課稅的", d: "on which tax must be paid",
        ph: [["taxable income", "應稅所得"], ["tax-exempt", "免稅的"]] },
      { w: "deduction", p: "n.", zh: "扣除額;推論", d: "an amount taken away; a conclusion",
        ph: [["a tax deduction", "稅額扣除"], ["payroll deductions", "薪資扣款"]],
        r: "de-(向下) + duct(引導) → 引導下來、減掉" },
      { w: "payroll", p: "n.", zh: "薪資名冊;薪資支出", d: "the list of employees and the money paid to them",
        ph: [["on the payroll", "在職;支薪名單上"], ["process payroll", "處理薪資"]] },
      { w: "accounting", p: "n.", zh: "會計", d: "the work of keeping financial records",
        ph: [["the accounting department", "會計部"], ["accounting standards", "會計準則"]] },
      { w: "estimate", p: "n./v.", zh: "估價單;估計", d: "a judgment of cost or value",
        syn: ["quote", "approximation"],
        ph: [["a rough estimate", "粗估"], ["a written estimate", "書面估價"]],
        n: "動詞唸 /ˈestɪmeɪt/,名詞唸 /ˈestɪmət/,是重音以外的母音弱化考點。" },
      { w: "expense report", p: "n.", zh: "報帳單", d: "a form listing costs to be repaid",
        ph: [["file an expense report", "提交報帳單"]] },
      { w: "cash flow", p: "n.", zh: "現金流", d: "the movement of money into and out of a business",
        ph: [["positive cash flow", "正向現金流"], ["cash flow problems", "現金週轉問題"]] },
      { w: "currency", p: "n.", zh: "貨幣", d: "the money used in a particular country",
        ph: [["foreign currency", "外幣"], ["the exchange rate", "匯率"]] },
      { w: "subsidize", p: "v.", zh: "補助", d: "to pay part of the cost of something",
        ph: [["subsidized housing", "補助住宅"], ["a government subsidy", "政府補助款"]],
        r: "sub-(在下) + sid(坐) → 在下面撐住" },
      { w: "cost-effective", p: "adj.", zh: "符合成本效益的", d: "giving good value for the money spent",
        syn: ["economical"], ant: ["wasteful"],
        ph: [["a cost-effective solution", "划算的方案"]] },
      { w: "approve", p: "v.", zh: "核准", d: "to officially agree to something",
        syn: ["authorize", "sign off on"], ant: ["reject", "deny"],
        ph: [["approve the budget", "核准預算"], ["subject to approval", "須經核准"]],
        n: "approve(核准)vs. approve of(贊同某事),多一個 of 意思就變了。" },
    ]},

  { id: "purch", no: 5, name: "採購", en: "Purchasing", icon: "📦",
    map: { center: "採購", branches: [
      { label: "詢價", ws: ["quotation", "bid", "tender", "specification", "catalog"] },
      { label: "下單", ws: ["procurement", "requisition", "purchase order", "bulk", "vendor"] },
      { label: "出貨", ws: ["shipment", "freight", "logistics", "carrier", "consignment"] },
      { label: "倉儲", ws: ["inventory", "warehouse", "restock", "backorder", "surplus"] },
      { label: "問題處理", ws: ["defective", "shortage", "expedite", "claim", "compensate"] },
    ]},
    list: [
      { w: "procurement", p: "n.", zh: "採購(作業)", d: "the process of obtaining supplies for a business",
        syn: ["purchasing", "sourcing"],
        ph: [["the procurement department", "採購部"], ["procurement policy", "採購政策"]],
        r: "pro-(為了) + cur(照料) → 為公司張羅所需" },
      { w: "vendor", p: "n.", zh: "供應商;攤販", d: "a person or company that sells goods",
        syn: ["supplier", "seller"], ant: ["buyer", "purchaser"],
        ph: [["an approved vendor", "合格供應商"], ["a street vendor", "路邊攤販"]] },
      { w: "quotation", p: "n.", zh: "報價單", d: "a statement of the price for a job or goods",
        syn: ["quote", "estimate"],
        ph: [["request a quotation", "索取報價"], ["a written quote", "書面報價"]] },
      { w: "bid", p: "n./v.", zh: "投標;出價", d: "an offer to do work or buy something at a stated price",
        ph: [["submit a bid", "投標"], ["the winning bid", "得標"], ["bid for a contract", "競標合約"]] },
      { w: "tender", p: "n./v.", zh: "招標;投標", d: "a formal offer to supply goods at a fixed price",
        ph: [["invite tenders", "公開招標"], ["put the work out to tender", "把工程發包招標"]] },
      { w: "specification", p: "n.", zh: "規格", d: "a detailed description of how something should be made",
        ph: [["technical specifications", "技術規格"], ["meet the specs", "符合規格"]],
        n: "口語常縮寫成 specs;built to specification = 依規格製造。" },
      { w: "catalog", p: "n.", zh: "型錄", d: "a book or list showing goods for sale",
        ph: [["a product catalog", "產品型錄"], ["request a catalog", "索取型錄"]] },
      { w: "requisition", p: "n./v.", zh: "請購(單)", d: "an official request for supplies",
        ph: [["a purchase requisition", "請購單"], ["submit a requisition", "提出請購"]] },
      { w: "purchase order", p: "n.", zh: "採購單(PO)", d: "an official document ordering goods",
        ph: [["issue a purchase order", "開立採購單"], ["the PO number", "採購單號"]] },
      { w: "bulk", p: "n./adj.", zh: "大量;散裝", d: "a large quantity",
        ph: [["buy in bulk", "大量採購"], ["a bulk discount", "大量訂購折扣"]] },
      { w: "shipment", p: "n.", zh: "貨物;裝運", d: "goods sent together, or the act of sending them",
        syn: ["consignment", "delivery"],
        ph: [["track a shipment", "追蹤貨物"], ["the shipment arrived damaged", "貨物送達時已受損"]] },
      { w: "freight", p: "n.", zh: "貨運;運費", d: "goods transported in large quantities, or the cost",
        ph: [["freight charges", "運費"], ["air freight", "空運"]],
        n: "唸 /freɪt/(像 eight);freight elevator 是「貨梯」,Part 7 常見。" },
      { w: "logistics", p: "n.", zh: "物流", d: "the organization of moving goods and supplies",
        ph: [["a logistics provider", "物流業者"], ["the logistics of the move", "搬遷的統籌作業"]] },
      { w: "carrier", p: "n.", zh: "貨運業者;航空公司", d: "a company that transports goods or people",
        ph: [["a common carrier", "公共運輸業者"], ["a low-cost carrier", "廉價航空"]] },
      { w: "consignment", p: "n.", zh: "託運貨物;寄售", d: "a batch of goods sent to someone",
        ph: [["on consignment", "寄售"]] },
      { w: "inventory", p: "n.", zh: "庫存;盤點", d: "the goods a business has in stock",
        syn: ["stock"],
        ph: [["take inventory", "盤點庫存"], ["inventory levels", "庫存水位"]] },
      { w: "warehouse", p: "n.", zh: "倉庫", d: "a large building for storing goods",
        syn: ["depot", "storage facility"],
        ph: [["a distribution warehouse", "配送倉庫"]] },
      { w: "restock", p: "v.", zh: "補貨", d: "to fill up supplies again",
        syn: ["replenish"],
        r: "re-(再) + stock(存貨)" },
      { w: "replenish", p: "v.", zh: "補充", d: "to fill something up again",
        syn: ["restock", "refill"],
        ph: [["replenish supplies", "補充用品"]] },
      { w: "backorder", p: "n.", zh: "缺貨待補訂單", d: "an order that cannot be filled until stock arrives",
        ph: [["on backorder", "缺貨待補中"]] },
      { w: "shortage", p: "n.", zh: "短缺", d: "a situation where there is not enough of something",
        syn: ["deficiency", "lack"], ant: ["surplus", "abundance"],
        ph: [["a staff shortage", "人手不足"], ["a chip shortage", "晶片短缺"]] },
      { w: "defective", p: "adj.", zh: "有瑕疵的", d: "not working correctly; faulty",
        syn: ["faulty", "flawed"], ant: ["flawless", "intact"],
        ph: [["a defective unit", "瑕疵品"], ["return defective goods", "退回瑕疵品"]] },
      { w: "expedite", p: "v.", zh: "加速處理", d: "to make a process happen more quickly",
        syn: ["speed up", "accelerate"], ant: ["delay", "hold up"],
        ph: [["expedite the shipment", "加急出貨"], ["expedited delivery", "急件配送"]],
        r: "ex-(出) + ped(腳) → 把腳從束縛中放出來 → 加快" },
      { w: "lead time", p: "n.", zh: "前置時間;交貨期", d: "the time between ordering and receiving goods",
        ph: [["a two-week lead time", "兩週交期"]] },
      { w: "supplier", p: "n.", zh: "供應商", d: "a company that provides goods to another",
        syn: ["vendor", "provider"],
        ph: [["a reliable supplier", "可靠的供應商"], ["switch suppliers", "更換供應商"]] },
      { w: "distributor", p: "n.", zh: "經銷商", d: "a company that supplies goods to shops",
        ph: [["an authorized distributor", "授權經銷商"]] },
      { w: "wholesale", p: "n./adj.", zh: "批發", d: "selling goods in large amounts at lower prices",
        ant: ["retail"],
        ph: [["wholesale price", "批發價"], ["a wholesale distributor", "批發商"]] },
      { w: "terms", p: "n.", zh: "條件;條款", d: "the conditions of an agreement",
        ph: [["payment terms", "付款條件"], ["terms and conditions", "條款與細則"], ["net 30 terms", "三十天付款期"]] },
      { w: "warranty", p: "n.", zh: "保固", d: "a written promise to repair or replace a product",
        syn: ["guarantee"],
        ph: [["under warranty", "保固期內"], ["a two-year warranty", "兩年保固"]],
        n: "warranty 是「書面保固」,guarantee 較口語且可當動詞,兩字常互換但考題偏好 warranty。" },
      { w: "claim", p: "n./v.", zh: "索賠;主張", d: "a demand for money; to say something is true",
        ph: [["file a claim", "提出索賠"], ["an insurance claim", "保險理賠"]] },
      { w: "compensate", p: "v.", zh: "賠償;補償", d: "to pay someone for loss or damage",
        syn: ["reimburse", "make up for"],
        ph: [["compensate for the delay", "補償延誤"]] },
      { w: "negotiable", p: "adj.", zh: "可議的", d: "able to be discussed and changed",
        ant: ["fixed", "non-negotiable"],
        ph: [["the price is negotiable", "價格可議"]] },
      { w: "invoice number", p: "n.", zh: "發票號碼", d: "the reference number of an invoice",
        ph: [["quote the invoice number", "註明發票號碼"]] },
      { w: "purchase", p: "v./n.", zh: "購買", d: "to buy something, especially for a business",
        syn: ["buy", "acquire"], ant: ["sell"],
        ph: [["proof of purchase", "購買證明"], ["a major purchase", "大額採購"]],
        n: "purchase 比 buy 正式,商務文件幾乎都用 purchase。" },
      { w: "surcharge", p: "n.", zh: "附加費", d: "an extra amount added to the usual price",
        ph: [["a fuel surcharge", "燃油附加費"]],
        r: "sur-(在上) + charge(收費) → 額外加收" },
      { w: "obsolete", p: "adj.", zh: "已淘汰的", d: "no longer used or produced",
        syn: ["outdated", "discontinued"], ant: ["current", "up-to-date"],
        ph: [["an obsolete model", "停產機型"]] },
      { w: "durable", p: "adj.", zh: "耐用的", d: "lasting a long time without breaking",
        syn: ["long-lasting", "sturdy"], ant: ["fragile"],
        ph: [["durable goods", "耐久財"]],
        r: "dur(持續) + -able → 能持續的" },
      { w: "damaged", p: "adj.", zh: "受損的", d: "harmed or broken",
        ph: [["damaged in transit", "運送中受損"], ["report damaged items", "回報受損品項"]] },
      { w: "confirm", p: "v.", zh: "確認", d: "to state that something is definitely true",
        syn: ["verify", "acknowledge"],
        ph: [["confirm receipt of", "確認收到…"], ["a confirmation number", "確認號碼"]] },
      { w: "discount", p: "n./v.", zh: "折扣;打折", d: "a reduction in the usual price",
        syn: ["markdown", "reduction"],
        ph: [["a 20% discount", "八折"], ["at a discount", "以折扣價"]],
        n: "中文的「八折」= 20% off / a 20% discount,考題常用數字陷阱。" },
    ]},

  { id: "tech", no: 6, name: "技術領域", en: "Technical Areas", icon: "🔧",
    map: { center: "技術領域", branches: [
      { label: "系統", ws: ["install", "upgrade", "configure", "compatible", "interface"] },
      { label: "故障", ws: ["malfunction", "glitch", "crash", "troubleshoot", "diagnose"] },
      { label: "資料", ws: ["backup", "database", "encrypt", "retrieve", "server"] },
      { label: "研發", ws: ["engineer", "innovation", "component", "circuit", "automate"] },
      { label: "維運", ws: ["maintenance", "downtime", "capacity", "network", "technician"] },
    ]},
    list: [
      { w: "install", p: "v.", zh: "安裝", d: "to put equipment or software in place ready to use",
        ant: ["uninstall", "remove"],
        ph: [["install an update", "安裝更新"], ["the installation is complete", "安裝完成"]],
        r: "in-(進入) + stall(位置) → 放進定位" },
      { w: "upgrade", p: "v./n.", zh: "升級", d: "to improve equipment to a newer version",
        ant: ["downgrade"],
        ph: [["upgrade the system", "升級系統"], ["a free upgrade", "免費升級"]] },
      { w: "configure", p: "v.", zh: "設定;配置", d: "to set up equipment or software for a purpose",
        syn: ["set up", "customize"],
        ph: [["configure the settings", "設定選項"], ["the default configuration", "預設配置"]] },
      { w: "compatible", p: "adj.", zh: "相容的", d: "able to work together with something else",
        ant: ["incompatible"],
        ph: [["compatible with Windows", "相容於 Windows"], ["backward compatible", "向下相容"]],
        n: "介係詞固定 with:compatible with(不是 compatible to)。",
        r: "com-(一起) + pat(承受) + -ible → 能一起共處的" },
      { w: "interface", p: "n./v.", zh: "介面;連接", d: "the way a user interacts with a system",
        ph: [["a user interface", "使用者介面"], ["interface with the database", "與資料庫連接"]],
        r: "inter-(之間) + face(面) → 兩者之間的接觸面" },
      { w: "malfunction", p: "n./v.", zh: "故障", d: "a failure to work correctly",
        syn: ["breakdown", "fault"],
        ph: [["a mechanical malfunction", "機械故障"]],
        r: "mal-(壞的) + function(運作) → 運作不良" },
      { w: "glitch", p: "n.", zh: "小故障", d: "a small, temporary problem",
        syn: ["bug", "hiccup"],
        ph: [["a software glitch", "軟體小問題"], ["a technical glitch", "技術性小狀況"]],
        n: "glitch 是「小而暫時」的問題,malfunction 較嚴重,聽力常用來判斷嚴重程度。" },
      { w: "crash", p: "v./n.", zh: "當機;碰撞", d: "to stop working suddenly",
        ph: [["the system crashed", "系統當機"], ["a server crash", "伺服器當機"]] },
      { w: "troubleshoot", p: "v.", zh: "排除故障", d: "to find and solve problems in a system",
        syn: ["debug", "diagnose"],
        ph: [["a troubleshooting guide", "疑難排解指南"]] },
      { w: "bandwidth", p: "n.", zh: "頻寬;處理餘裕", d: "the amount of data a connection can carry",
        ph: [["limited bandwidth", "頻寬有限"], ["I don't have the bandwidth", "我沒有餘力(職場口語)"]],
        n: "技術義是頻寬,職場口語引申為「時間與心力的餘裕」,兩義都會出現。" },
      { w: "backup", p: "n.", zh: "備份;後援", d: "a copy of data kept in case of loss",
        ph: [["run a backup", "執行備份"], ["a backup generator", "備用發電機"]] },
      { w: "retrieve", p: "v.", zh: "取回;檢索", d: "to get information back from a system",
        syn: ["recover", "access"],
        ph: [["retrieve the file", "取回檔案"], ["data retrieval", "資料檢索"]],
        r: "re-(再) + trouve(找到) → 再找回來" },
      { w: "database", p: "n.", zh: "資料庫", d: "an organized collection of information",
        ph: [["update the database", "更新資料庫"], ["a customer database", "客戶資料庫"]] },
      { w: "encrypt", p: "v.", zh: "加密", d: "to protect data by putting it into code",
        ant: ["decrypt"],
        ph: [["encrypted files", "加密檔案"], ["end-to-end encryption", "端對端加密"]],
        r: "en-(使進入) + crypt(隱藏) → 讓資訊藏起來" },
      { w: "server", p: "n.", zh: "伺服器", d: "a computer that provides data to other computers",
        ph: [["the server is down", "伺服器停擺"], ["a cloud server", "雲端伺服器"]] },
      { w: "network", p: "n./v.", zh: "網路;建立人脈", d: "a system of connected computers or people",
        ph: [["a network outage", "網路中斷"], ["networking event", "交流活動"]] },
      { w: "outage", p: "n.", zh: "停電;斷線", d: "a period when a service is not available",
        syn: ["blackout", "disruption"],
        ph: [["a power outage", "停電"], ["a scheduled outage", "預定停機"]] },
      { w: "downtime", p: "n.", zh: "停機時間", d: "time when a system is not working",
        ant: ["uptime"],
        ph: [["minimize downtime", "把停機時間降到最低"]] },
      { w: "capacity", p: "n.", zh: "容量;產能;身分", d: "the amount something can hold or produce",
        ph: [["storage capacity", "儲存容量"], ["at full capacity", "滿載"], ["in his capacity as", "以他…的身分"]],
        n: "三個意思都考:容量、產能、身分(in one's capacity as manager)。" },
      { w: "component", p: "n.", zh: "零件;組件", d: "one of the parts that make up a machine",
        syn: ["part", "element"],
        ph: [["electronic components", "電子零件"], ["a key component", "關鍵元件"]] },
      { w: "circuit", p: "n.", zh: "電路", d: "a complete path that electricity flows around",
        ph: [["a short circuit", "短路"], ["a circuit board", "電路板"]],
        r: "circu(圓) + it(走) → 電流繞一圈" },
      { w: "engineer", p: "n./v.", zh: "工程師;設計建造", d: "a person who designs machines or systems",
        ph: [["a field engineer", "現場工程師"], ["engineer a solution", "設計出解方"]] },
      { w: "technician", p: "n.", zh: "技師", d: "a person skilled at operating or repairing equipment",
        ph: [["a service technician", "維修技師"], ["a lab technician", "實驗室技術員"]] },
      { w: "automate", p: "v.", zh: "自動化", d: "to make a process operate by machines",
        ph: [["an automated system", "自動化系統"], ["automate routine tasks", "把例行工作自動化"]],
        r: "auto-(自己) + mat(思考;運作) → 自己運作" },
      { w: "innovation", p: "n.", zh: "創新", d: "a new idea, method or product",
        syn: ["breakthrough", "advance"],
        ph: [["technological innovation", "技術創新"], ["an innovative design", "創新設計"]],
        r: "in-(進入) + nov(新的) → 帶進新東西" },
      { w: "prototype testing", p: "n.", zh: "原型測試", d: "trying out an early model of a product",
        ph: [["undergo prototype testing", "進行原型測試"]] },
      { w: "implement", p: "v.", zh: "實施;導入", d: "to start using a plan or system",
        syn: ["carry out", "put into practice"],
        ph: [["implement a new system", "導入新系統"], ["the implementation phase", "導入階段"]],
        r: "im-(進入) + ple(填滿) → 把計畫填實" },
      { w: "integrate", p: "v.", zh: "整合", d: "to combine things so they work together",
        ant: ["separate", "isolate"],
        ph: [["integrate two systems", "整合兩套系統"], ["seamless integration", "無縫整合"]],
        r: "integr(完整) + -ate → 使成為完整一體" },
      { w: "specification sheet", p: "n.", zh: "規格表", d: "a document listing technical details",
        ph: [["refer to the spec sheet", "參閱規格表"]] },
      { w: "resolution", p: "n.", zh: "解析度;解決", d: "the clarity of an image; the solving of a problem",
        ph: [["high resolution", "高解析度"], ["the resolution of the issue", "問題的解決"]] },
      { w: "remote", p: "adj.", zh: "遠端的;偏遠的", d: "operating from a distance",
        ph: [["remote access", "遠端存取"], ["work remotely", "遠端工作"]] },
      { w: "restore", p: "v.", zh: "還原;恢復", d: "to bring something back to its earlier state",
        syn: ["recover", "reinstate"],
        ph: [["restore from backup", "從備份還原"], ["restore service", "恢復服務"]],
        r: "re-(回) + stor(建立) → 重新建立起來" },
      { w: "override", p: "v.", zh: "覆寫;強制取消", d: "to use your authority to change a setting or decision",
        ph: [["override the default", "覆寫預設值"], ["a manual override", "手動強制控制"]] },
      { w: "prompt", p: "n./v./adj.", zh: "提示;促使;迅速的", d: "a message asking for input; quick",
        ph: [["follow the on-screen prompts", "依畫面提示操作"], ["a prompt reply", "迅速回覆"]],
        n: "三種詞性都考;prompt payment(即時付款)在財務情境也很常見。" },
      { w: "utility", p: "n.", zh: "公用事業;工具程式", d: "a service such as electricity; a small program",
        ph: [["utility bills", "水電帳單"], ["a disk utility", "磁碟工具"]] },
      { w: "device", p: "n.", zh: "裝置", d: "a machine made for a particular purpose",
        syn: ["gadget", "appliance"],
        ph: [["a mobile device", "行動裝置"], ["pair the device", "配對裝置"]] },
      { w: "wireless", p: "adj.", zh: "無線的", d: "working without connecting wires",
        ph: [["a wireless connection", "無線連線"], ["wireless headset", "無線耳機"]] },
      { w: "activate", p: "v.", zh: "啟用", d: "to make something start working",
        ant: ["deactivate", "disable"],
        ph: [["activate your account", "啟用帳號"]] },
      { w: "verify", p: "v.", zh: "驗證;查核", d: "to check that something is true or accurate",
        syn: ["confirm", "validate"],
        ph: [["verify your identity", "驗證身分"], ["a verification code", "驗證碼"]],
        r: "ver(真實) + -ify(使…) → 確認為真" },
      { w: "efficiency", p: "n.", zh: "效率", d: "working well without wasting time or resources",
        ant: ["waste", "inefficiency"],
        ph: [["improve efficiency", "提升效率"], ["energy efficiency", "能源效率"]],
        n: "efficient(有效率,把事做快)vs. effective(有效果,把事做對),Part 5 高頻對比。" },
    ]},
);
