// ============================================================
//  💼 多益 TOEIC 專區 - 題庫資料
//  單字六大主題 / Part 2 應答 / Part 5 句子填空 / Part 3・4 聽力 / Part 7 閱讀
//  選項規則:opts 與 r 的第 0 個永遠是正解,畫面顯示時再洗牌
// ============================================================

// ---------- 高頻單字(6 主題 × 10 字)----------
const TOEIC_WORDS = [
  { theme: "辦公室", emoji: "🏢", list: [
    { w: "appointment", zh: "預約;約定", pos: "n." },
    { w: "schedule", zh: "時程表;安排", pos: "n./v." },
    { w: "deadline", zh: "截止期限", pos: "n." },
    { w: "document", zh: "文件", pos: "n." },
    { w: "colleague", zh: "同事", pos: "n." },
    { w: "supervisor", zh: "主管", pos: "n." },
    { w: "department", zh: "部門", pos: "n." },
    { w: "equipment", zh: "設備(不可數)", pos: "n." },
    { w: "supplies", zh: "辦公用品", pos: "n." },
    { w: "memo", zh: "備忘錄", pos: "n." },
  ]},
  { theme: "人事", emoji: "🧑‍💼", list: [
    { w: "applicant", zh: "應徵者", pos: "n." },
    { w: "resume", zh: "履歷", pos: "n." },
    { w: "qualification", zh: "資格;條件", pos: "n." },
    { w: "promotion", zh: "升遷;促銷", pos: "n." },
    { w: "salary", zh: "薪水", pos: "n." },
    { w: "recruit", zh: "招募", pos: "v." },
    { w: "retire", zh: "退休", pos: "v." },
    { w: "employee", zh: "員工", pos: "n." },
    { w: "employer", zh: "雇主", pos: "n." },
    { w: "staff", zh: "全體職員", pos: "n." },
  ]},
  { theme: "會議", emoji: "📋", list: [
    { w: "agenda", zh: "議程", pos: "n." },
    { w: "attend", zh: "出席", pos: "v." },
    { w: "postpone", zh: "延期", pos: "v." },
    { w: "conference", zh: "會議;研討會", pos: "n." },
    { w: "presentation", zh: "簡報", pos: "n." },
    { w: "participant", zh: "與會者", pos: "n." },
    { w: "propose", zh: "提議", pos: "v." },
    { w: "approve", zh: "核准", pos: "v." },
    { w: "negotiate", zh: "談判;協商", pos: "v." },
    { w: "announce", zh: "宣布", pos: "v." },
  ]},
  { theme: "財務", emoji: "💰", list: [
    { w: "budget", zh: "預算", pos: "n." },
    { w: "invoice", zh: "請款單;發票", pos: "n." },
    { w: "expense", zh: "費用;支出", pos: "n." },
    { w: "revenue", zh: "營收", pos: "n." },
    { w: "profit", zh: "利潤", pos: "n." },
    { w: "refund", zh: "退款", pos: "n./v." },
    { w: "receipt", zh: "收據", pos: "n." },
    { w: "transaction", zh: "交易", pos: "n." },
    { w: "account", zh: "帳戶;客戶", pos: "n." },
    { w: "estimate", zh: "估價;估計", pos: "n./v." },
  ]},
  { theme: "商務行銷", emoji: "📦", list: [
    { w: "advertisement", zh: "廣告", pos: "n." },
    { w: "customer", zh: "顧客", pos: "n." },
    { w: "contract", zh: "合約", pos: "n." },
    { w: "launch", zh: "推出;上市", pos: "v./n." },
    { w: "brochure", zh: "宣傳手冊", pos: "n." },
    { w: "warranty", zh: "保固", pos: "n." },
    { w: "shipment", zh: "出貨;貨運", pos: "n." },
    { w: "order", zh: "訂單;訂購", pos: "n./v." },
    { w: "discount", zh: "折扣", pos: "n." },
    { w: "supplier", zh: "供應商", pos: "n." },
  ]},
  { theme: "出差旅遊", emoji: "✈️", list: [
    { w: "reservation", zh: "預訂", pos: "n." },
    { w: "itinerary", zh: "行程表", pos: "n." },
    { w: "departure", zh: "出發;離境", pos: "n." },
    { w: "destination", zh: "目的地", pos: "n." },
    { w: "luggage", zh: "行李(不可數)", pos: "n." },
    { w: "boarding", zh: "登機", pos: "n." },
    { w: "delay", zh: "延誤", pos: "n./v." },
    { w: "confirm", zh: "確認", pos: "v." },
    { w: "accommodation", zh: "住宿", pos: "n." },
    { w: "fare", zh: "車資;票價", pos: "n." },
  ]},
];

// ---------- Part 2 應答問題(聽問題選回應;r[0] 為正解)----------
const TOEIC_PART2 = [
  { q: "When is the marketing report due?",
    r: ["By the end of this week.", "In the meeting room.", "Yes, I read it."],
    note: "When 問時間 → 回答期限。地點與 Yes/No 都答非所問。" },
  { q: "Who's in charge of the new project?",
    r: ["Ms. Chen from the sales team.", "It starts next Monday.", "On the second floor."],
    note: "Who 問人 → 回答人名;時間與地點是陷阱。" },
  { q: "Would you like to join us for lunch?",
    r: ["Sure, I'd love to.", "It was delicious.", "At the Italian restaurant."],
    note: "邀請句 → 接受或婉拒。過去式評價與地點都不對。" },
  { q: "Where can I find the meeting agenda?",
    r: ["It's on the shared drive.", "At three o'clock.", "Mr. Park will attend."],
    note: "Where 問地點 → 回答位置。" },
  { q: "How do I get to the conference center?",
    r: ["Take the shuttle bus from the lobby.", "About two hours.", "It was a great conference."],
    note: "How 問方法 → 回答交通方式;About two hours 回答的是 How long。" },
  { q: "Why was the flight delayed?",
    r: ["Because of the heavy snow.", "At Gate 12.", "For three days."],
    note: "Why 問原因 → Because of...。" },
  { q: "Have you finished the sales report?",
    r: ["Almost, I just need one more chart.", "He's a sales manager.", "Twice a month."],
    note: "Have you...? 可用 Almost / Not yet 這類間接回答。" },
  { q: "Could you make ten copies of this document?",
    r: ["Certainly, I'll do it right away.", "The copier is brand new.", "It's ten pages long."],
    note: "請求句 → 答應或拒絕;描述影印機或頁數都不是回應請求。" },
  { q: "When does the store open on weekends?",
    r: ["At ten in the morning.", "Near the train station.", "Yes, on Saturday."],
    note: "When 問時間;疑問詞問句不能用 Yes/No 回答。" },
  { q: "Who approved the travel budget?",
    r: ["The finance director did.", "Around five thousand dollars.", "To attend a trade show."],
    note: "Who → 人。金額回答 How much、目的回答 Why。" },
  { q: "Where should I send the invoice?",
    r: ["To the accounting department.", "By Friday afternoon.", "It costs fifty dollars."],
    note: "Where → 地點或收件部門。" },
  { q: "How often do you back up the files?",
    r: ["Every night, automatically.", "On the main server.", "About two gigabytes."],
    note: "How often 問頻率 → Every night。" },
  { q: "Would you mind turning down the air conditioning?",
    r: ["Not at all.", "Yes, the weather is nice.", "The window is open."],
    note: "Would you mind...? 願意幫忙要說 Not at all(不介意)。" },
  { q: "What time does the workshop start?",
    r: ["At nine thirty sharp.", "In Room 204.", "It lasts two hours."],
    note: "What time → 時刻;It lasts two hours 回答的是 How long。" },
  { q: "Why don't we take a short break?",
    r: ["Good idea, let's meet back in ten minutes.", "Because it's broken.", "I took it yesterday."],
    note: "Why don't we...? 是提議,不是問原因!回答要表態。" },
  { q: "Has the shipment arrived yet?",
    r: ["Yes, it came this morning.", "By express mail.", "About twenty boxes."],
    note: "Yes/No 問句 → 先回答有或沒有。" },
];

// ---------- Part 5 句子填空(opts[0] 為正解)----------
const TOEIC_PART5 = [
  { s: "All staff must submit their timesheets ___ Friday afternoon.",
    opts: ["by", "until", "since", "at"], note: "by + 時間 = 期限之前完成;until 表「持續到」。" },
  { s: "The new printer works much more ___ than the old one.",
    opts: ["efficiently", "efficient", "efficiency", "efficiencies"], note: "修飾動詞 works → 副詞 efficiently。" },
  { s: "Ms. Torres will be out of the office ___ she returns from the trade show.",
    opts: ["until", "by", "during", "despite"], note: "「持續到她回來為止」→ until + 子句。" },
  { s: "Please review the ___ contract before signing it.",
    opts: ["attached", "attaching", "attachment", "attach"], note: "被附上的合約 → 過去分詞當形容詞 attached。" },
  { s: "___ the heavy rain, the outdoor event was moved indoors.",
    opts: ["Because of", "Because", "Although", "So"], note: "後面接名詞片語 → Because of;Because 接子句。" },
  { s: "Employees who wish to attend the workshop should register ___ advance.",
    opts: ["in", "on", "at", "by"], note: "in advance 固定搭配 = 事先。" },
  { s: "The manager asked Kevin to handle the client's complaint ___.",
    opts: ["himself", "him", "his", "he"], note: "反身代名詞 himself 強調「親自」。" },
  { s: "Our sales have increased ___ 15 percent since the new campaign began.",
    opts: ["by", "in", "to", "with"], note: "increase by + 幅度(增加了 15%);increase to 是增加「到」。" },
  { s: "___ of the two proposals was approved by the board.",
    opts: ["Neither", "None", "Both", "Every"], note: "兩者皆非 → Neither(動詞 was 單數);Both 要接 were。" },
  { s: "The training session has been ___ until next Thursday.",
    opts: ["postponed", "postpone", "postponing", "postpones"], note: "has been + 過去分詞(被動完成)→ postponed。" },
  { s: "Applicants must have at least three years of ___ experience.",
    opts: ["relevant", "relevance", "relevantly", "relevancies"], note: "修飾名詞 experience → 形容詞 relevant。" },
  { s: "___ you have any questions, please contact the HR department.",
    opts: ["Should", "Unless", "Despite", "During"], note: "Should you... = If you should...(倒裝條件句)。" },
  { s: "The company offers a full refund ___ customers return items within 30 days.",
    opts: ["provided that", "in spite of", "according to", "instead of"], note: "provided that = 只要(條件)。" },
  { s: "Mr. Sato is responsible ___ coordinating the annual conference.",
    opts: ["for", "of", "to", "with"], note: "be responsible for + V-ing 固定搭配。" },
  { s: "The quarterly report must be reviewed ___ before it is published.",
    opts: ["carefully", "careful", "care", "caring"], note: "修飾動詞 reviewed → 副詞 carefully。" },
  { s: "___ arriving at the hotel, guests should present a valid ID.",
    opts: ["Upon", "While", "Since", "Until"], note: "Upon + V-ing = 一…就…(Upon arriving 一抵達)。" },
  { s: "The two companies reached an ___ after months of negotiation.",
    opts: ["agreement", "agree", "agreeable", "agreeably"], note: "冠詞 an 後面 → 名詞 agreement。" },
  { s: "Neither the manager nor the assistants ___ available yesterday afternoon.",
    opts: ["were", "was", "is", "am"], note: "neither A nor B 動詞就近一致 → assistants(複數)→ were。" },
  { s: "The seminar was so ___ that many attendees requested a follow-up session.",
    opts: ["informative", "information", "inform", "informed"], note: "so + 形容詞 + that;研討會「有收穫的」→ informative。" },
  { s: "Please make sure all equipment ___ turned off before leaving.",
    opts: ["is", "are", "be", "were"], note: "equipment 不可數名詞 → 單數動詞 is。" },
  { s: "___ who need parking permits should apply at the front desk.",
    opts: ["Those", "They", "This", "Them"], note: "Those who... = 凡是…的人。" },
  { s: "The hotel is conveniently ___ near the international airport.",
    opts: ["located", "locating", "location", "locates"], note: "be located = 位於(被動);conveniently 修飾它。" },
  { s: "Ms. Alvarez requested that the invoice ___ sent by the end of the day.",
    opts: ["be", "is", "was", "been"], note: "request/suggest that + 主詞 + 原形動詞(假設語氣)→ be sent。" },
  { s: "The store will exchange the item ___ you have the original receipt.",
    opts: ["as long as", "even so", "rather than", "as well as"], note: "as long as = 只要(條件)。" },
];

// ---------- Part 3・4 聽力(sp: M=男聲 / W=女聲;每組 3 題)----------
const TOEIC_LC = [
  { id: "c1", part: "Part 3", title: "改約會議時間", icon: "📞",
    lines: [
      { sp: "W", en: "Hi Mark, this is Lisa from the sales department. Are we still meeting at two o'clock today?" },
      { sp: "M", en: "Actually, I was about to call you. My earlier appointment is running late, so could we push our meeting to three thirty?" },
      { sp: "W", en: "Three thirty works for me. Should we still meet in the small conference room?" },
      { sp: "M", en: "Yes, I've already booked it. I'll bring the updated sales figures with me." },
      { sp: "W", en: "Perfect. I'll print the client list before then." },
      { sp: "M", en: "Great. Sorry again for the change, and see you this afternoon." },
    ],
    questions: [
      { q: "Why is the man changing the meeting time?", opts: ["His earlier appointment is running late", "He is out of town", "The conference room is unavailable", "He lost the sales figures"], note: "男士說 My earlier appointment is running late。" },
      { q: "What time will the speakers meet?", opts: ["At 3:30", "At 2:00", "At 3:00", "At 4:30"], note: "push our meeting to three thirty。" },
      { q: "What will the woman do before the meeting?", opts: ["Print the client list", "Book a room", "Update the sales figures", "Call a client"], note: "女士說 I'll print the client list before then。" },
    ]},
  { id: "c2", part: "Part 3", title: "印表機故障", icon: "🖨️",
    lines: [
      { sp: "M", en: "Excuse me, Anna. The printer on the fourth floor isn't working again. It keeps showing a paper jam error." },
      { sp: "W", en: "I checked it this morning, and there's no paper stuck inside. It might be a software problem." },
      { sp: "M", en: "Should I call the IT help desk, or will you report it?" },
      { sp: "W", en: "I'll send them a request now. In the meantime, you can use the printer near the elevator on the third floor." },
      { sp: "M", en: "Thanks. I need to print twenty copies of the training handout before noon." },
      { sp: "W", en: "Then I'd go now. That printer gets busy around lunchtime." },
    ],
    questions: [
      { q: "What problem are the speakers discussing?", opts: ["A printer is not working", "A meeting was canceled", "An elevator is out of service", "A file was deleted"], note: "開頭:The printer isn't working again。" },
      { q: "What does the woman offer to do?", opts: ["Report the problem to the IT help desk", "Fix the printer herself", "Print the handouts", "Move the printer"], note: "I'll send them a request now。" },
      { q: "What does the man need to do before noon?", opts: ["Print copies of a training handout", "Attend a training session", "Meet a client", "Have lunch with Anna"], note: "print twenty copies of the training handout before noon。" },
    ]},
  { id: "t1", part: "Part 4", title: "機場廣播", icon: "🛫",
    lines: [
      { sp: "M", en: "Attention passengers on Flight 274 to Chicago. Due to strong winds, this flight has been delayed by approximately one hour." },
      { sp: "M", en: "The new boarding time is 4:15 P.M., and boarding will now take place at Gate 22 instead of Gate 18." },
      { sp: "M", en: "If you have a connecting flight, please speak with a gate agent, who can help you rebook." },
      { sp: "M", en: "We apologize for the delay and thank you for your patience." },
    ],
    questions: [
      { q: "Why has the flight been delayed?", opts: ["Because of strong winds", "Because of heavy snow", "Because of a mechanical problem", "Because of a late crew"], note: "Due to strong winds。" },
      { q: "Where will boarding now take place?", opts: ["At Gate 22", "At Gate 18", "At Gate 12", "At Gate 4"], note: "at Gate 22 instead of Gate 18(instead of 是陷阱)。" },
      { q: "Who should passengers with connecting flights talk to?", opts: ["A gate agent", "The pilot", "A flight attendant", "The ticket office"], note: "please speak with a gate agent。" },
    ]},
  { id: "t2", part: "Part 4", title: "診所語音留言", icon: "📱",
    lines: [
      { sp: "W", en: "Hello, this message is for Mr. Chen. This is Emily from Riverside Dental Clinic." },
      { sp: "W", en: "I'm calling to confirm your appointment on Thursday, May ninth, at 10 A.M." },
      { sp: "W", en: "Please arrive ten minutes early to update your patient forms." },
      { sp: "W", en: "If you need to change your appointment, please call us at least 24 hours in advance. Otherwise, we look forward to seeing you Thursday. Thank you!" },
    ],
    questions: [
      { q: "Why is the woman calling?", opts: ["To confirm an appointment", "To cancel an appointment", "To ask for payment", "To announce a new clinic"], note: "I'm calling to confirm your appointment。" },
      { q: "What is Mr. Chen asked to do?", opts: ["Arrive ten minutes early", "Bring his insurance card", "Call back immediately", "Fill out forms online"], note: "Please arrive ten minutes early。" },
      { q: "What should Mr. Chen do if he needs to reschedule?", opts: ["Call at least 24 hours in advance", "Send an email", "Visit the clinic", "Wait for another call"], note: "call us at least 24 hours in advance。" },
    ]},
];

// ---------- Part 7 閱讀測驗 ----------
const TOEIC_PART7 = [
  { id: "r1", type: "電子郵件", icon: "📧", title: "Building Maintenance",
    text: "From: Daniel Reed, Facilities Office\nTo: All Staff\nSubject: Elevator Maintenance\n\nPlease be advised that the elevator in the main lobby will be out of service for repairs from Monday, March 3 through Wednesday, March 5. During this period, please use the stairs or the freight elevator at the rear of the building. We apologize for any inconvenience and appreciate your patience. If you have questions, contact the facilities office at extension 234.",
    questions: [
      { q: "Why was the email sent?", opts: ["To inform staff about elevator repairs", "To announce a new building", "To schedule a staff meeting", "To introduce a new employee"], note: "主旨與首句:電梯將停用維修。" },
      { q: "What should employees do during the repairs?", opts: ["Use the stairs or the freight elevator", "Work from home", "Call extension 234 every day", "Move to another office"], note: "please use the stairs or the freight elevator。" },
    ]},
  { id: "r2", type: "廣告", icon: "📣", title: "GreenFit Fitness Center",
    text: "Join GreenFit Fitness Center this month and pay no registration fee! Our newly renovated facility offers over 40 group classes each week, a heated indoor pool, and personal training sessions. Members who sign up for a one-year plan will also receive two free guest passes. Visit our front desk or website to schedule a free tour. Offer ends April 30.",
    questions: [
      { q: "What is being offered to new members this month?", opts: ["No registration fee", "A free swimsuit", "Free personal training for a year", "A discount on group classes"], note: "首句:pay no registration fee。" },
      { q: "What will members who choose a one-year plan receive?", opts: ["Two free guest passes", "A heated pool", "40 group classes", "A free tour"], note: "one-year plan → two free guest passes。" },
    ]},
  { id: "r3", type: "公告", icon: "📌", title: "Harbor Books - New Hours",
    text: "Attention Customers: Beginning next week, Harbor Books will extend its opening hours. The store will be open from 9 A.M. to 10 P.M. on weekdays and from 10 A.M. to 8 P.M. on weekends. In addition, our cafe on the second floor will now serve a full breakfast menu until 11 A.M. We look forward to serving you longer!",
    questions: [
      { q: "What is the notice mainly about?", opts: ["Longer store hours", "A new store location", "A book signing event", "Higher cafe prices"], note: "will extend its opening hours。" },
      { q: "What will the cafe offer?", opts: ["A full breakfast menu until 11 A.M.", "Free coffee on weekends", "A dinner menu", "24-hour service"], note: "serve a full breakfast menu until 11 A.M.。" },
    ]},
  { id: "r4", type: "備忘錄", icon: "📄", title: "New Expense Policy",
    text: "To: All Department Heads\nFrom: Accounting Department\n\nEffective June 1, all business expenses over $100 must be approved by a supervisor before purchase. Receipts must be submitted within seven days using the new online system. Paper forms will no longer be accepted after June 30. A short training video about the system is available on the company intranet.",
    questions: [
      { q: "What must employees do before purchasing items over $100?", opts: ["Get a supervisor's approval", "Submit a paper form", "Watch a training video", "Contact the accounting department"], note: "must be approved by a supervisor before purchase。" },
      { q: "What will happen after June 30?", opts: ["Paper forms will no longer be accepted", "The online system will close", "Expenses will not be refunded", "A new supervisor will be hired"], note: "Paper forms will no longer be accepted after June 30。" },
    ]},
];
