// 英語冒險王 - 看影片學英文 AI 口說(參考 VoiceTube)
// 每支影片精選 4~6 句經典名句:看影片 → 逐句聽 TTS → 🎙️ 口說挑戰(AI 評分)
// yt = YouTube 影片 ID(已驗證存在),句子為演說中廣為引用的名句(附出處)
const VIDEO_BANK = [
  {
    yt: "l-gQLqv9f4o", level: "junior", cefr: "A2", tags: ["勵志", "生活"],
    title: "A Pep Talk from Kid President",
    zh: "小總統的打氣演說", by: "SoulPancake",
    sentences: [
      { en: "This is your time.", zh: "這是屬於你的時刻。" },
      { en: "You were made to be awesome.", zh: "你生來就注定很了不起。" },
      { en: "What will you create that will make the world awesome?", zh: "你會創造什麼,讓這個世界變得更棒?" },
      { en: "It's everybody's duty to give the world a reason to dance.", zh: "給世界一個跳舞的理由,是每個人的責任。" },
      { en: "Be somebody who makes everybody feel like a somebody.", zh: "當一個讓每個人都覺得自己重要的人。" },
    ],
  },
  {
    yt: "gkjW9PZBRfk", level: "senior", cefr: "B1", tags: ["社會", "演講"],
    title: "Emma Watson: HeForShe Speech",
    zh: "艾瑪華森聯合國演說", by: "United Nations",
    sentences: [
      { en: "If not me, who? If not now, when?", zh: "如果不是我,那會是誰?如果不是現在,要等到何時?" },
      { en: "Both men and women should feel free to be sensitive.", zh: "無論男女,都應該能自在地展現感性。" },
      { en: "Both men and women should feel free to be strong.", zh: "無論男女,都應該能自在地展現堅強。" },
      { en: "Feminism by definition is the belief that men and women should have equal rights and opportunities.", zh: "女性主義的定義,是相信男性與女性應享有平等的權利與機會。" },
      { en: "It is time that we all perceive gender on a spectrum, not as two opposing sets of ideals.", zh: "是時候把性別視為一道光譜,而不是兩組對立的理想了。" },
    ],
  },
  {
    yt: "pxBQLFLei70", level: "senior", cefr: "B1", tags: ["勵志", "演講"],
    title: "Admiral McRaven: Make Your Bed",
    zh: "麥克雷文上將:先整理好你的床", by: "Texas Exes",
    sentences: [
      { en: "If you want to change the world, start off by making your bed.", zh: "如果你想改變世界,先從整理好你的床開始。" },
      { en: "If you can't do the little things right, you will never do the big things right.", zh: "如果你連小事都做不好,就永遠做不好大事。" },
      { en: "If you make your bed every morning, you will have accomplished the first task of the day.", zh: "如果你每天早上整理床鋪,你就完成了一天的第一項任務。" },
      { en: "It will give you a small sense of pride, and it will encourage you to do another task, and another, and another.", zh: "它會給你小小的成就感,鼓勵你完成下一件、再下一件任務。" },
      { en: "If you want to change the world, don't ever, ever ring the bell.", zh: "如果你想改變世界,永遠、永遠不要搖鈴放棄。" },
    ],
  },
  {
    yt: "UF8uR6Z6KLc", level: "college", cefr: "B2", tags: ["職場", "勵志"],
    title: "Steve Jobs: Stanford Commencement",
    zh: "賈伯斯史丹佛畢業演說", by: "Stanford",
    sentences: [
      { en: "Stay hungry. Stay foolish.", zh: "求知若飢,虛心若愚。" },
      { en: "Your time is limited, so don't waste it living someone else's life.", zh: "你的時間有限,別浪費在過別人的人生。" },
      { en: "The only way to do great work is to love what you do.", zh: "成就偉大工作的唯一方法,就是熱愛你所做的事。" },
      { en: "You can't connect the dots looking forward; you can only connect them looking backwards.", zh: "你無法預先把點連起來,只有回顧時才能看出它們的關聯。" },
      { en: "Have the courage to follow your heart and intuition.", zh: "要有勇氣跟隨你的內心與直覺。" },
      { en: "If you haven't found it yet, keep looking. Don't settle.", zh: "如果還沒找到,就繼續找,不要將就。" },
    ],
  },
  {
    yt: "qp0HIF3SfI4", level: "college", cefr: "B2", tags: ["職場", "TED"],
    title: "Simon Sinek: Start With Why",
    zh: "賽門西奈克:先問為什麼", by: "TED",
    sentences: [
      { en: "People don't buy what you do; they buy why you do it.", zh: "人們買的不是你做什麼,而是你為什麼而做。" },
      { en: "The goal is to do business with people who believe what you believe.", zh: "目標是與相信你所相信的人做生意。" },
      { en: "Martin Luther King gave the 'I have a dream' speech, not the 'I have a plan' speech.", zh: "金恩博士發表的是「我有一個夢」,而不是「我有一個計畫」。" },
      { en: "There are leaders and there are those who lead.", zh: "有掛名的領導者,也有真正引領人心的人。" },
    ],
  },
  {
    yt: "Ks-_Mh1QhMc", level: "master", cefr: "C1", tags: ["心理", "TED"],
    title: "Amy Cuddy: Your Body Language",
    zh: "艾美柯蒂:肢體語言塑造你", by: "TED",
    sentences: [
      { en: "Your body language may shape who you are.", zh: "你的肢體語言可能塑造你是誰。" },
      { en: "Our bodies change our minds, and our minds change our behavior, and our behavior changes our outcomes.", zh: "身體改變心智,心智改變行為,行為改變結果。" },
      { en: "Don't fake it till you make it. Fake it till you become it.", zh: "不只是裝到你成功,而是裝到你真正成為那樣的人。" },
      { en: "Tiny tweaks can lead to big changes.", zh: "微小的調整能帶來巨大的改變。" },
    ],
  },
  {
    yt: "iG9CE55wbtY", level: "phd", cefr: "C2", tags: ["教育", "TED"],
    title: "Ken Robinson: Do Schools Kill Creativity?",
    zh: "肯羅賓森:學校扼殺創意嗎?", by: "TED",
    sentences: [
      { en: "If you're not prepared to be wrong, you'll never come up with anything original.", zh: "如果你不準備好犯錯,就永遠想不出任何原創的東西。" },
      { en: "Creativity is as important in education as literacy, and we should treat it with the same status.", zh: "創造力在教育中和識字同等重要,我們應該給予同等地位。" },
      { en: "We don't grow into creativity, we grow out of it.", zh: "我們不是長出創造力,而是把它長丟了。" },
      { en: "Or rather, we get educated out of it.", zh: "更準確地說,是被教育給教掉了。" },
      { en: "Every education system on Earth has the same hierarchy of subjects.", zh: "地球上每個教育體系都有同一套科目位階。" },
    ],
  },

  // ↓ 以下影片的名句由 build_video_sentences.py 從真實字幕擷取(見 js/video_sentences.js)
  { yt: "UNP03fDSj1U", level: "junior", cefr: "A2", tags: ["生活", "習慣"],
    title: "Try Something New for 30 Days", zh: "用 30 天嘗試新事物", by: "TED-Ed", sentences: [] },
  { yt: "h6fcK_fRYaI", level: "junior", cefr: "A2", tags: ["故事", "哲學"],
    title: "The Egg - A Short Story", zh: "蛋:一則短篇故事", by: "Kurzgesagt", sentences: [] },
  { yt: "H14bBuluwB8", level: "senior", cefr: "B1", tags: ["勵志", "TED"],
    title: "Angela Duckworth: Grit", zh: "安琪拉達克沃斯:恆毅力", by: "TED", sentences: [] },
  { yt: "V80-gPkpH6M", level: "senior", cefr: "B1", tags: ["勵志", "演講"],
    title: "Jim Carrey: MIU Commencement", zh: "金凱瑞畢業演說", by: "MIU", sentences: [] },
  { yt: "eIho2S0ZahI", level: "college", cefr: "B2", tags: ["職場", "TED"],
    title: "Julian Treasure: How to Speak", zh: "如何說話讓人想聽", by: "TED", sentences: [] },
  { yt: "8KkKuTCFvzI", level: "college", cefr: "B2", tags: ["心理", "TED"],
    title: "What Makes a Good Life?", zh: "什麼造就美好人生?", by: "TED", sentences: [] },
  { yt: "fLJsdqxnZb0", level: "college", cefr: "B2", tags: ["職場", "TED"],
    title: "Shawn Achor: The Happy Secret", zh: "更好工作的快樂祕訣", by: "TED", sentences: [] },
  { yt: "5MgBikgcWnY", level: "college", cefr: "B2", tags: ["學習", "TED"],
    title: "Josh Kaufman: The First 20 Hours", zh: "學會任何事的前 20 小時", by: "TEDx", sentences: [] },
  { yt: "arj7oStGLkU", level: "master", cefr: "C1", tags: ["心理", "TED"],
    title: "Tim Urban: Master Procrastinator", zh: "拖延大師的腦中世界", by: "TED", sentences: [] },
  { yt: "RcGyVTAoXEU", level: "master", cefr: "C1", tags: ["心理", "TED"],
    title: "Kelly McGonigal: Make Stress Your Friend", zh: "與壓力做朋友", by: "TED", sentences: [] },
  { yt: "rrkrvAUbU9Y", level: "master", cefr: "C1", tags: ["職場", "TED"],
    title: "Dan Pink: The Puzzle of Motivation", zh: "丹尼爾品克:動機之謎", by: "TED", sentences: [] },
  { yt: "F2hc2FLOdhI", level: "master", cefr: "C1", tags: ["心理", "TED"],
    title: "Guy Winch: Emotional First Aid", zh: "情緒急救的練習", by: "TED", sentences: [] },
  { yt: "iCvmsMzlF7o", level: "phd", cefr: "C2", tags: ["心理", "TED"],
    title: "Brené Brown: The Power of Vulnerability", zh: "布芮尼布朗:脆弱的力量", by: "TED", sentences: [] },
  { yt: "MB5IX-np5fE", level: "phd", cefr: "C2", tags: ["社會", "TED"],
    title: "Johann Hari: Depression and Anxiety", zh: "憂鬱與焦慮的真正原因", by: "TED", sentences: [] },
  { yt: "PY9DcIMGxMs", level: "phd", cefr: "C2", tags: ["社會", "TED"],
    title: "Johann Hari: Everything You Know About Addiction", zh: "成癮的真相", by: "TED", sentences: [] },
];
