// 英語冒險王 - 字庫
// 每個等級 50 個單字:w = 英文, c = 中文, p = 詞性
const WORD_BANK = {
  junior: {
    name: "國中", title: "新手草原", emoji: "🌱",
    monsters: ["🐛", "🐸", "🐰", "🦊", "🐗"], boss: "🐺",
    words: [
      { w: "apple", c: "蘋果", p: "n." },
      { w: "breakfast", c: "早餐", p: "n." },
      { w: "weather", c: "天氣", p: "n." },
      { w: "library", c: "圖書館", p: "n." },
      { w: "vacation", c: "假期", p: "n." },
      { w: "museum", c: "博物館", p: "n." },
      { w: "bridge", c: "橋", p: "n." },
      { w: "dictionary", c: "字典", p: "n." },
      { w: "umbrella", c: "雨傘", p: "n." },
      { w: "kitchen", c: "廚房", p: "n." },
      { w: "hospital", c: "醫院", p: "n." },
      { w: "famous", c: "有名的", p: "adj." },
      { w: "dangerous", c: "危險的", p: "adj." },
      { w: "expensive", c: "昂貴的", p: "adj." },
      { w: "comfortable", c: "舒適的", p: "adj." },
      { w: "delicious", c: "美味的", p: "adj." },
      { w: "exercise", c: "運動;練習", p: "n./v." },
      { w: "medicine", c: "藥", p: "n." },
      { w: "restaurant", c: "餐廳", p: "n." },
      { w: "mountain", c: "山", p: "n." },
      { w: "borrow", c: "借入", p: "v." },
      { w: "celebrate", c: "慶祝", p: "v." },
      { w: "decide", c: "決定", p: "v." },
      { w: "finish", c: "完成", p: "v." },
      { w: "forget", c: "忘記", p: "v." },
      { w: "invite", c: "邀請", p: "v." },
      { w: "practice", c: "練習", p: "v./n." },
      { w: "prepare", c: "準備", p: "v." },
      { w: "arrive", c: "到達", p: "v." },
      { w: "believe", c: "相信", p: "v." },
      { w: "magazine", c: "雜誌", p: "n." },
      { w: "holiday", c: "假日", p: "n." },
      { w: "popular", c: "受歡迎的", p: "adj." },
      { w: "special", c: "特別的", p: "adj." },
      { w: "terrible", c: "可怕的;糟糕的", p: "adj." },
      { w: "temperature", c: "溫度", p: "n." },
      { w: "environment", c: "環境", p: "n." },
      { w: "experience", c: "經驗", p: "n." },
      { w: "convenient", c: "方便的", p: "adj." },
      { w: "interview", c: "面試;採訪", p: "n./v." },
      { w: "seldom", c: "很少;不常", p: "adv." },
      { w: "already", c: "已經", p: "adv." },
      { w: "foreigner", c: "外國人", p: "n." },
      { w: "husband", c: "丈夫", p: "n." },
      { w: "engineer", c: "工程師", p: "n." },
      { w: "secretary", c: "秘書", p: "n." },
      { w: "factory", c: "工廠", p: "n." },
      { w: "garbage", c: "垃圾", p: "n." },
      { w: "straight", c: "直的;直接地", p: "adj./adv." },
      { w: "honest", c: "誠實的", p: "adj." },
    ],
  },
  senior: {
    name: "高中", title: "迷霧森林", emoji: "🌲",
    monsters: ["🦉", "🐍", "🦂", "🕷️", "🦇"], boss: "🐻",
    words: [
      { w: "abandon", c: "拋棄;放棄", p: "v." },
      { w: "absorb", c: "吸收", p: "v." },
      { w: "academic", c: "學術的", p: "adj." },
      { w: "accompany", c: "陪伴", p: "v." },
      { w: "accomplish", c: "完成;達成", p: "v." },
      { w: "accurate", c: "精確的", p: "adj." },
      { w: "acquire", c: "獲得;習得", p: "v." },
      { w: "adapt", c: "適應;改編", p: "v." },
      { w: "admire", c: "欽佩;讚賞", p: "v." },
      { w: "advantage", c: "優勢;好處", p: "n." },
      { w: "ambition", c: "抱負;野心", p: "n." },
      { w: "analyze", c: "分析", p: "v." },
      { w: "ancient", c: "古代的", p: "adj." },
      { w: "anxious", c: "焦慮的", p: "adj." },
      { w: "apologize", c: "道歉", p: "v." },
      { w: "appreciate", c: "感激;欣賞", p: "v." },
      { w: "approach", c: "接近;方法", p: "v./n." },
      { w: "appropriate", c: "適當的", p: "adj." },
      { w: "argument", c: "爭論;論點", p: "n." },
      { w: "atmosphere", c: "大氣;氣氛", p: "n." },
      { w: "attitude", c: "態度", p: "n." },
      { w: "available", c: "可用的;有空的", p: "adj." },
      { w: "benefit", c: "利益;獲益", p: "n./v." },
      { w: "calculate", c: "計算", p: "v." },
      { w: "campaign", c: "活動;戰役", p: "n." },
      { w: "candidate", c: "候選人", p: "n." },
      { w: "capacity", c: "容量;能力", p: "n." },
      { w: "challenge", c: "挑戰", p: "n./v." },
      { w: "circumstance", c: "情況;境遇", p: "n." },
      { w: "community", c: "社區;社群", p: "n." },
      { w: "compete", c: "競爭", p: "v." },
      { w: "complain", c: "抱怨", p: "v." },
      { w: "concentrate", c: "專心;集中", p: "v." },
      { w: "confidence", c: "信心", p: "n." },
      { w: "consequence", c: "後果", p: "n." },
      { w: "considerable", c: "相當大的", p: "adj." },
      { w: "contribute", c: "貢獻;促成", p: "v." },
      { w: "curious", c: "好奇的", p: "adj." },
      { w: "definitely", c: "確定地;絕對地", p: "adv." },
      { w: "demonstrate", c: "證明;示範", p: "v." },
      { w: "efficient", c: "有效率的", p: "adj." },
      { w: "eliminate", c: "消除;淘汰", p: "v." },
      { w: "emphasize", c: "強調", p: "v." },
      { w: "essential", c: "必要的;本質的", p: "adj." },
      { w: "evidence", c: "證據", p: "n." },
      { w: "expand", c: "擴展;膨脹", p: "v." },
      { w: "familiar", c: "熟悉的", p: "adj." },
      { w: "frequent", c: "頻繁的", p: "adj." },
      { w: "generous", c: "慷慨的", p: "adj." },
      { w: "hesitate", c: "猶豫", p: "v." },
    ],
  },
  college: {
    name: "大學", title: "峭壁高塔", emoji: "🏔️",
    monsters: ["🗿", "🦅", "⚡", "🌪️", "🧊"], boss: "🐉",
    words: [
      { w: "abstract", c: "抽象的;摘要", p: "adj./n." },
      { w: "accumulate", c: "累積", p: "v." },
      { w: "adequate", c: "足夠的;適當的", p: "adj." },
      { w: "advocate", c: "提倡;擁護者", p: "v./n." },
      { w: "alternative", c: "替代的;選擇", p: "adj./n." },
      { w: "ambiguous", c: "模糊的;歧義的", p: "adj." },
      { w: "arbitrary", c: "任意的;武斷的", p: "adj." },
      { w: "assess", c: "評估", p: "v." },
      { w: "assume", c: "假設;承擔", p: "v." },
      { w: "attribute", c: "歸因於;屬性", p: "v./n." },
      { w: "coherent", c: "連貫的;有條理的", p: "adj." },
      { w: "coincide", c: "一致;同時發生", p: "v." },
      { w: "compensate", c: "補償", p: "v." },
      { w: "comprehensive", c: "全面的", p: "adj." },
      { w: "comprise", c: "包含;構成", p: "v." },
      { w: "conceive", c: "構想;懷孕", p: "v." },
      { w: "controversy", c: "爭議", p: "n." },
      { w: "conventional", c: "傳統的;慣例的", p: "adj." },
      { w: "criteria", c: "標準;準則", p: "n." },
      { w: "crucial", c: "關鍵的", p: "adj." },
      { w: "derive", c: "衍生;源自", p: "v." },
      { w: "deviate", c: "偏離", p: "v." },
      { w: "dimension", c: "維度;尺寸", p: "n." },
      { w: "distinct", c: "明顯不同的", p: "adj." },
      { w: "diverse", c: "多樣的", p: "adj." },
      { w: "dominant", c: "主導的;優勢的", p: "adj." },
      { w: "elaborate", c: "詳盡的;詳細說明", p: "adj./v." },
      { w: "explicit", c: "明確的;直白的", p: "adj." },
      { w: "facilitate", c: "促進;使便利", p: "v." },
      { w: "fluctuate", c: "波動", p: "v." },
      { w: "fundamental", c: "基本的;根本的", p: "adj." },
      { w: "hypothesis", c: "假說;假設", p: "n." },
      { w: "implement", c: "實施;執行", p: "v." },
      { w: "implicit", c: "含蓄的;隱含的", p: "adj." },
      { w: "incentive", c: "誘因;激勵", p: "n." },
      { w: "inevitable", c: "不可避免的", p: "adj." },
      { w: "integrate", c: "整合;融入", p: "v." },
      { w: "interpret", c: "詮釋;口譯", p: "v." },
      { w: "intrinsic", c: "內在的;固有的", p: "adj." },
      { w: "legitimate", c: "合法的;正當的", p: "adj." },
      { w: "manipulate", c: "操縱", p: "v." },
      { w: "notion", c: "概念;想法", p: "n." },
      { w: "objective", c: "客觀的;目標", p: "adj./n." },
      { w: "perceive", c: "感知;認為", p: "v." },
      { w: "phenomenon", c: "現象", p: "n." },
      { w: "preliminary", c: "初步的", p: "adj." },
      { w: "prevail", c: "盛行;獲勝", p: "v." },
      { w: "rational", c: "理性的", p: "adj." },
      { w: "simultaneous", c: "同時的", p: "adj." },
      { w: "subsequent", c: "隨後的", p: "adj." },
    ],
  },
  master: {
    name: "碩士", title: "熔岩秘境", emoji: "🌋",
    monsters: ["👹", "🔥", "💀", "🦖", "🧟"], boss: "😈",
    words: [
      { w: "aggregate", c: "總計;聚集", p: "n./v." },
      { w: "albeit", c: "儘管;雖然", p: "conj." },
      { w: "analogous", c: "類似的;可比擬的", p: "adj." },
      { w: "anomaly", c: "異常;反常", p: "n." },
      { w: "articulate", c: "清晰表達;口齒清晰的", p: "v./adj." },
      { w: "augment", c: "增加;擴大", p: "v." },
      { w: "benevolent", c: "仁慈的", p: "adj." },
      { w: "coalesce", c: "合併;聯合", p: "v." },
      { w: "cognizant", c: "認知的;察覺的", p: "adj." },
      { w: "conducive", c: "有助於的", p: "adj." },
      { w: "conjecture", c: "推測;臆測", p: "n./v." },
      { w: "connotation", c: "言外之意;內涵", p: "n." },
      { w: "consolidate", c: "鞏固;合併", p: "v." },
      { w: "contingent", c: "視情況而定的", p: "adj." },
      { w: "correlate", c: "相關;關聯", p: "v." },
      { w: "culminate", c: "達到頂點;告終", p: "v." },
      { w: "delineate", c: "描繪;勾勒", p: "v." },
      { w: "discrepancy", c: "差異;不符", p: "n." },
      { w: "disseminate", c: "傳播;散布", p: "v." },
      { w: "elucidate", c: "闡明", p: "v." },
      { w: "empirical", c: "實證的;經驗的", p: "adj." },
      { w: "emulate", c: "效仿;模擬", p: "v." },
      { w: "exacerbate", c: "加劇;惡化", p: "v." },
      { w: "exemplify", c: "例證;作為範例", p: "v." },
      { w: "exhaustive", c: "詳盡無遺的", p: "adj." },
      { w: "expedite", c: "加速;促進", p: "v." },
      { w: "extrapolate", c: "推斷;外推", p: "v." },
      { w: "feasible", c: "可行的", p: "adj." },
      { w: "heterogeneous", c: "異質的", p: "adj." },
      { w: "homogeneous", c: "同質的", p: "adj." },
      { w: "juxtapose", c: "並列;並置", p: "v." },
      { w: "meticulous", c: "一絲不苟的", p: "adj." },
      { w: "mitigate", c: "減輕;緩和", p: "v." },
      { w: "nuance", c: "細微差別", p: "n." },
      { w: "paradigm", c: "典範;範式", p: "n." },
      { w: "pervasive", c: "普遍的;遍布的", p: "adj." },
      { w: "plausible", c: "貌似合理的", p: "adj." },
      { w: "pragmatic", c: "務實的", p: "adj." },
      { w: "precedent", c: "先例", p: "n." },
      { w: "proliferate", c: "激增;擴散", p: "v." },
      { w: "quintessential", c: "典型的;精髓的", p: "adj." },
      { w: "reconcile", c: "調和;和解", p: "v." },
      { w: "redundant", c: "多餘的;冗贅的", p: "adj." },
      { w: "rigorous", c: "嚴謹的", p: "adj." },
      { w: "salient", c: "顯著的;突出的", p: "adj." },
      { w: "scrutinize", c: "仔細檢查", p: "v." },
      { w: "substantiate", c: "證實", p: "v." },
      { w: "synthesis", c: "綜合;合成", p: "n." },
      { w: "tangible", c: "有形的;具體的", p: "adj." },
      { w: "viable", c: "可行的;能存活的", p: "adj." },
    ],
  },
  phd: {
    name: "博士", title: "混沌深淵", emoji: "🌌",
    monsters: ["👾", "🛸", "🌑", "☄️", "🕳️"], boss: "👑",
    words: [
      { w: "abstruse", c: "深奧難懂的", p: "adj." },
      { w: "anachronistic", c: "時代錯誤的", p: "adj." },
      { w: "antithetical", c: "對立的;相反的", p: "adj." },
      { w: "apocryphal", c: "真偽可疑的", p: "adj." },
      { w: "assiduous", c: "勤勉的", p: "adj." },
      { w: "axiomatic", c: "不言自明的", p: "adj." },
      { w: "capricious", c: "反覆無常的", p: "adj." },
      { w: "circumlocution", c: "迂迴說法", p: "n." },
      { w: "deleterious", c: "有害的", p: "adj." },
      { w: "desultory", c: "散漫的;無條理的", p: "adj." },
      { w: "dialectical", c: "辯證的", p: "adj." },
      { w: "didactic", c: "說教的;教誨的", p: "adj." },
      { w: "ebullient", c: "熱情洋溢的", p: "adj." },
      { w: "efficacious", c: "有效驗的", p: "adj." },
      { w: "egregious", c: "極壞的;過分的", p: "adj." },
      { w: "ephemeral", c: "短暫的;朝生暮死的", p: "adj." },
      { w: "epistemology", c: "認識論", p: "n." },
      { w: "equivocal", c: "模稜兩可的", p: "adj." },
      { w: "erudite", c: "博學的", p: "adj." },
      { w: "esoteric", c: "只有內行才懂的", p: "adj." },
      { w: "exigent", c: "緊急的;苛求的", p: "adj." },
      { w: "grandiloquent", c: "誇張浮華的", p: "adj." },
      { w: "hegemony", c: "霸權", p: "n." },
      { w: "hermeneutics", c: "詮釋學", p: "n." },
      { w: "heuristic", c: "啟發式的", p: "adj." },
      { w: "iconoclast", c: "打破傳統者", p: "n." },
      { w: "idiosyncratic", c: "特有的;獨特的", p: "adj." },
      { w: "immutable", c: "不可改變的", p: "adj." },
      { w: "inchoate", c: "剛開始的;未成形的", p: "adj." },
      { w: "incontrovertible", c: "無可爭辯的", p: "adj." },
      { w: "ineffable", c: "難以言喻的", p: "adj." },
      { w: "inexorable", c: "不可阻擋的", p: "adj." },
      { w: "insidious", c: "陰險的;潛伏的", p: "adj." },
      { w: "intransigent", c: "不妥協的", p: "adj." },
      { w: "obfuscate", c: "使模糊;混淆", p: "v." },
      { w: "ontology", c: "本體論", p: "n." },
      { w: "panacea", c: "萬靈丹", p: "n." },
      { w: "pedagogy", c: "教育學;教學法", p: "n." },
      { w: "perfunctory", c: "敷衍的", p: "adj." },
      { w: "pernicious", c: "有害的;惡性的", p: "adj." },
      { w: "perspicacious", c: "敏銳的;有洞察力的", p: "adj." },
      { w: "propensity", c: "傾向;癖好", p: "n." },
      { w: "recalcitrant", c: "頑抗的;不服從的", p: "adj." },
      { w: "sanguine", c: "樂觀的", p: "adj." },
      { w: "sycophant", c: "諂媚者;馬屁精", p: "n." },
      { w: "taxonomy", c: "分類學;分類法", p: "n." },
      { w: "tenuous", c: "薄弱的;牽強的", p: "adj." },
      { w: "ubiquitous", c: "無所不在的", p: "adj." },
      { w: "vicissitude", c: "變遷;興衰", p: "n." },
      { w: "zeitgeist", c: "時代精神", p: "n." },
    ],
  },
};

const LEVEL_ORDER = ["junior", "senior", "college", "master", "phd"];
